### ISSUE TITLE
Upgrading to Typescript 4.4.2 breaks Ionicons 5.5.3

### ISSUE THREAD

**Issue by dorontal** [ionic-team/ionicons#1000]
Just upgraded typescript (from version 4.3.5) and got these errors in the Ionicons type definitions, as reported when running `yarn start` inside an Ionic project that uses Ionicons 5.5.3:
```
Error: node_modules/ionicons/dist/types/components.d.ts:66:15 - error TS2320: Interface 'HTMLIonIconElement' cannot simultaneously extend types 'IonIcon' and 'HTMLStencilElement'.
  Named property 'ariaHidden' of types 'IonIcon' and 'HTMLStencilElement' are not identical.

66     interface HTMLIonIconElement extends Components.IonIcon, HTMLStencilElement {
                 ~~~~~~~~~~~~~~~~~~
```
NOTE: Typescript reports similar errors for code within it's own repository (further errors with the above build were reported in ` node_modules/typescript/lib/lib.dom.d.ts`) so this may be a problem with Typescript 4.4.2 itself and who knows, when that is fixed, it may fix this problem automatically. Not sure. 

But the current combination of Typescript version 4.4.2 and Ionicons version 5.5.3 is broken.

**Comment by shivagouraram** [comment]
Yes, I too faced this issue today. I had to downgrade the typescript to make it work.

**Comment by GothShoot** [comment]
Same problem for me.

**Comment by Ripwords** [comment]
The issue can be worked around by adding a config option in tsconfig mentioned [here](https://github.com/ionic-team/ionic-framework/issues/24005#issuecomment-933486049)
