### ISSUE TITLE
Author icon not present

### ISSUE THREAD

**Issue by nishabaruwal576** [ionic-team/ionicons#1001]
I could not find the author icon.

**Comment by akashshyamdev** [comment]
@nishabaruwal576 I don't think we can have an author icon per se. It would probably be similar to a user icon.

**Comment by amandaejohnston** [comment]
Thank you for the request. The existing `person` or `person-circle` should fit the bill here. I'm going to close this out, but if you had something else in mind, please open a new issue with example images.
