### ISSUE TITLE
Is this repo being maintained anymore?

### ISSUE THREAD

**Issue by akashshyamdev** [ionic-team/ionicons#1002]
I have a few issues I'd like to tackle and create a few PRs but it seems like there is no response from maintainers. This really defeats people's enthusiasm and they will move away to other icon libraries. I realise you guys are busy so I'd suggest adding a maintainer to the repo. I'd highly suggest looking into this issue @mlynch @brandyscarney @perrygovier. Looking forward to a reply!

**Comment by liamdebeasi** [comment]
Hey there! We have a new team maintaining this repo now. We are pretty focused on finishing up Ionic 6, so our responses may be delayed. We will respond to issues/PRs as we are able to. Thanks for understanding!

**Comment by akashshyamdev** [comment]
@liamdebeasi Awesome!
