### ISSUE TITLE
HTTPS support for CDN

### ISSUE THREAD

**Issue by zub0r** [ionic-team/ionicons#101]
Hi, 
It would be great if you could add https support for cdn.
Thanks!

https://code.ionicframework.com/ionicons/1.4.1/css/ionicons.min.css

**Comment by thejchap** [comment]
Just started getting this today...is anyone else experiencing this?


Font from origin 'https://code.ionicframework.com' has been blocked from loading by Cross-Origin Resource Sharing policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'https://my-website.parseapp.com' is therefore not allowed access.

**Comment by jeremykendall** [comment]
Me too.  I see two `Access-Control-Allow-Orogin: *` headers coming back from the cdn.

**Comment by mlynch** [comment]
Going to try to fix this on maxcdn right now

On Sat, Mar 7, 2015 at 1:24 PM, Jeremy Kendall <notifications@github.com>
wrote:

> Me too. I see two Access-Control-Allow-Orogin: * headers coming back from
> the cdn.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionicons/issues/101#issuecomment-77705266>.
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/

**Comment by mlynch** [comment]
See #225

**Comment by jeremykendall** [comment]
Thanks @mlynch.

**Comment by mlynch** [comment]
Should be fixed, can you try now?

On Sat, Mar 7, 2015 at 1:35 PM, Jeremy Kendall <notifications@github.com>
wrote:

> Thanks @mlynch <https://github.com/mlynch>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionicons/issues/101#issuecomment-77705825>.
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/

**Comment by thejchap** [comment]
Awesome!

**Comment by jeremykendall** [comment]
Works like a champ.
