### ISSUE TITLE
Please "support icon" !!

### ISSUE THREAD

**Issue by Thaotb90** [ionic-team/ionicons#1012]
![image](https://user-images.githubusercontent.com/91739818/138808893-ba8fdb10-ecb1-43bb-956f-4027e6650450.png)

**Comment by MicheleLucini-infobit** [comment]
<ion-icon name="help-buoy-outline"></ion-icon>

**Comment by MicheleLucini-infobit** [comment]
`<ion-icon name="help-buoy-outline"></ion-icon>`

**Comment by brandyscarney** [comment]
Thank you for the issue, I am going to close this as the following icon is very similar, but let us know if this is not what you meant:

`<ion-icon name="help-buoy"></ion-icon>`

![Screen Shot 2022-09-27 at 12 05 56 PM](https://user-images.githubusercontent.com/6577830/192577959-43ef66ec-4d9d-4020-8e6c-7b1c1eb7b40b.png)
