### ISSUE TITLE
Nintendo Icon

### ISSUE THREAD

**Issue by OGluffy** [ionic-team/ionicons#1017]
I was doing good on building an app with you all till I needed the logo for Nintendo and it wasn't there maybe just make a square with a long oval in it to make up for it. I just ended up using the controller logo to compensate.

**Comment by OGluffy** [comment]
or do the Nintendo switch icon, because that is the one I was actually looking for, and that is why I just settled for the controller icon?

**Comment by brandyscarney** [comment]
Thanks for the issue, closing as a duplicate of https://github.com/ionic-team/ionicons/issues/936
