### ISSUE TITLE
Repeat one ICON

### ISSUE THREAD

**Issue by Child-qjj** [ionic-team/ionicons#1019]

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you please describe what issue you are running into or what feature you are requesting?

**Comment by Child-qjj** [comment]
I want a single loop icon

**Comment by liamdebeasi** [comment]
What is a loop icon? Do you have links to an example?

**Comment by mikemikhaylov** [comment]
Hey @liamdebeasi I think he means an icon like this 
![image](https://user-images.githubusercontent.com/9201284/149296003-ad5cbb31-172b-42bc-8d08-ec7db6ed82c2.png)
For example in Youtube Music player they have 3 repeat states
1) no repeat (just a regular repeat icon)
2) repeat all (same icon with different color)
3) repeat one (icon with 1 digit inside it)

So currently, as I see there is no icon for the 3rd case.

**Comment by vfsfitvnm** [comment]
This is how it could look like (there isn't enough space to put the "1" between the arrows):

<img src="https://user-images.githubusercontent.com/46219656/166098631-5def5665-5b1f-4d7f-894a-0cc62ac94b68.svg" width="200" height="200" />

https://user-images.githubusercontent.com/46219656/166098542-4b4b3a35-37ff-4015-b559-137f4f2beada.mp4

**Comment by NatromeTex** [comment]
So is this icon not going to be added?
