### ISSUE TITLE
can't find all icons

### ISSUE THREAD

**Issue by lievenFlux** [ionic-team/ionicons#1022]
hello, i'm browsing icons here: https://ionic.io/ionicons
but not all icons are found here: https://github.com/oblador/react-native-vector-icons/blob/master/glyphmaps/Ionicons.json

for example 'scale-outline' is not found.

i'm using:
"react-native-vector-icons": "^9.0.0",
"react-native": "0.64.1"

thanks

**Comment by liamdebeasi** [comment]
Thanks for the issue. We do not maintain `react-native-vector-icons` so we are unable to resolve this. I recommend filing an issue on the `react-native-vector-icons` GitHub repo to ask the maintainer to update the `ionicons.json` file: https://github.com/oblador/react-native-vector-icons/
