### ISSUE TITLE
logo-instagram and logo-youtube not visible in live website

### ISSUE THREAD

**Issue by Topiya** [ionic-team/ionicons#1026]
logo-instagram and logo-youtube is not visible in live website.
In localhost, it is visible properly.

Please help to solve this issue.

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. I cannot reproduce this issue anymore, so it appears to be resolved. If this is still an issue, please reply, and I will be more than happy to take another look.
