### ISSUE TITLE
discord icon

### ISSUE THREAD

**Issue by MicrosoftSupport2978686798** [ionic-team/ionicons#1034]
add discord icon

**Comment by shubhayu09** [comment]
Hey @MicrosoftSupport2978686798 ,
Discord icon is there in the 3rd row of logos. So no need to add that.

**Comment by brandyscarney** [comment]
Thanks for the issue, this exists already as:

```
<ion-icon name="logo-discord"></ion-icon>
```

![Screen Shot 2022-09-27 at 12 18 15 PM](https://user-images.githubusercontent.com/6577830/192580447-2ada95d9-35ea-40a7-b8bc-502c3dc2d235.png)

I am going to close this but let me know if this is not what you meant. Thanks!
