### ISSUE TITLE
Spotify Icon 

### ISSUE THREAD

**Issue by RaiderXSkull** [ionic-team/ionicons#1041]
Can you add a spotify logo we can use?

Thanks
Aditya Kumar

**Comment by ChooseGoose001** [comment]
Hello! I would also like to request a Spotify logo - the icons are glorious :)

**Comment by GlxryX** [comment]
A Spotify logo would be nice.

**Comment by ImLowly** [comment]
This has been requested for a long time now.

**Comment by brandyscarney** [comment]
Thanks for the issue, closing as a duplicate of #478
