### ISSUE TITLE
Icons wont load if install as module

### ISSUE THREAD

**Issue by dgateles** [ionic-team/ionicons#1047]
Hi! I'm using the ionicons stencil component to make my own icon components (just for testing) and if I install the component as node modules and load it, the icons don't show. All other components are loaded but the icons do not load. <div class="icon-inner"> is not populated with svg code. 

Using this configuration with Vue: https://stenciljs.com/docs/vue

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. Do you have a GitHub repo I can use to verify this behavior?
