### ISSUE TITLE
feat: ion-icon: ability to override tooltip

### ISSUE THREAD

**Issue by cjorasch** [ionic-team/ionicons#1049]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Ionic icons currently render a child `<title>` element that displays as a tooltip during hover.

There are many cases where the name of the icon is not the same as a meaningful value that should be displayed to the user.

Setting `title` or using other tooltip approaches results in multiple tips being displayed.

<img width="244" alt="image" src="https://user-images.githubusercontent.com/2199401/155431274-1081acd8-cd0a-4b4a-85ff-ceff52199f97.png">

Feature request: Allow the user of the component to override (or suppress) the title.

### Describe the Use Case

Some use cases include:
- Icons used to indicate connection state (online / offline)
- Icons for expanded state (expanded / collapsed)

### Describe Preferred Solution

`<ion-icon title="My custom title" ... />`

Support blank value to prevent title display

**Comment by liamdebeasi** [comment]
Thanks for the report. This has been resolved via https://github.com/ionic-team/ionicons/pull/1166 and a fix will be available in Ionicons 6.1. In this release, developers will be able to set a custom `title` attribute on `ion-icon`. This title will be shown in a tooltip when hovering the icon.
