### ISSUE TITLE
Request China social network icons

### ISSUE THREAD

**Issue by Eric-Miao** [ionic-team/ionicons#1058]
Hi, thanks for the great project.
I wish there could be more icons for social network platforms in China. 
Below are some examples
1. weibo
![weibo](https://user-images.githubusercontent.com/32360942/165906767-b8187b42-81c0-4bc1-8414-b24fc73deb2a.svg)
2. zhihu
![zhihu](https://user-images.githubusercontent.com/32360942/165906757-1df043a2-19ee-4426-b6c2-bdf837078f24.svg)
4. bilibili
![bilibili](https://user-images.githubusercontent.com/32360942/165906770-3afe7906-8d6a-44f9-befb-89d9f57e99fb.svg)

**Comment by xfq** [comment]
See also https://github.com/ionic-team/ionicons/issues/965

**Comment by Eric-Miao** [comment]
thx
