### ISSUE TITLE
[Bug] SVG download failing

### ISSUE THREAD

**Issue by bboynton97** [ionic-team/ionicons#1062]
Attempting to download any SVG on [this page](https://ionic.io/ionicons/v4) fails.

Tested on Brave, Safari and Chrome with MacOS Monterey

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/6846214/168449616-4f34db7e-febe-499c-878f-a08f5898098a.png">

**Comment by raexey** [comment]
It's probably due to the outdated version. Try again on [this page](https://ionic.io/ionicons).

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. Is this issue still happening? I cannot reproduce this on my end.
