### ISSUE TITLE
Pricetag icon dot missing color variables

### ISSUE THREAD

**Issue by NotMyFault** [ionic-team/ionicons#1076]
The pricetag-outline and pricetags-outline dot don't have color attributes which makes theming difficult.

**Comment by brandyscarney** [comment]
Thanks for the issue! Could you provide a code reproduction? I am not sure if I am misunderstanding the issue but I have tried changing the color using both CSS and the `color` property provided in Ionic Framework and I am not able to see an issue: https://stackblitz.com/edit/zxked7?file=index.html

**Comment by liamdebeasi** [comment]
You should be able to use `color` in CSS even if you are not using Ionic Framework. Do you have a reproduction case we can look at?

**Comment by liamdebeasi** [comment]
Hey there,

It seems like this is the same issue as https://github.com/ionic-team/ionicons/issues/1129, so I am going to merge the two threads. Also, if you could provide more context surrounding https://github.com/ionic-team/ionicons/issues/1129#issuecomment-1295538215 that would be really helpful. Let me know if you have any questions.
