### ISSUE TITLE
bug: validation method does not properly check attributes starting with 'on'

### ISSUE THREAD

**Issue by dauriamarco** [ionic-team/ionicons#1088]
I found a bug related to the icon sanitize method that could affect the security of the component.

Basically, in the `isValid` method, where you should check that no attribute starts with `on`, what actually happens is that the value is checked and not the name of the attribute itself. In this way, as shown below, you could render an icon that on click triggers a function:

![image](https://user-images.githubusercontent.com/101181211/180611804-b96157fe-14c2-4b5e-9e17-8ae739153ea7.png)

I would also suggest, as you can see from the image above, to add two new icons to show in the "Sanitized (shouldn't show)" and "Not Sanitized (should show)" sections (e.g. `sanitize-attr.svg` and `no-sanitize-attr.svg`).

_I will open a pull request_ in order to solve this problem. Thank you very much.

**Comment by liamdebeasi** [comment]
Thank you for the issue, and apologies for the delay. Yes, I can confirm that we should be checking `name` instead of `value`. Given an example of `onclick="alert('abc')"`, the sanitizer would look at the value `alert('abc')` instead of `onclick` which is what it should be doing.

**Comment by dauriamarco** [comment]
No worries, no need to apologize. I didn't imagine that you would actually check for the value and not the name of the attribute; it seems a bit strange to me to have this approach, since you could inject functions even if `sanitize = true` and the comment on the `@Prop() sanitize` reads like this:

```js
/**
 * When set to `false`, SVG content that is HTTP fetched will not be checked
 * if the response SVG content has any `<script>` elements, or any attributes
 * that start with `on`, such as `onclick`.
 * @default true
 */
@Prop() sanitize = true;
```

Thank you very much for your response.

**Comment by liamdebeasi** [comment]
I merged your fix in https://github.com/ionic-team/ionicons/pull/1087. I am going to release a patch of Ionicons shortly. I will follow up on https://github.com/ionic-team/ionic-framework/issues/25830 when Ionic has been updated to use the new Ionicons version. Thank you again for the report!

**Comment by dauriamarco** [comment]
Thank you! 😄
