### ISSUE TITLE
Icon names show up as tooltip

### ISSUE THREAD

**Issue by iambozdar** [ionic-team/ionicons#1094]
I am using Ionicons on a web app. When I use v5.1.2 or a prior version, i.e. >3.0.0 & <5.0.0, I do not find the icon names popping up. But in any newer version besides above, a tooltip shows up. I am implementing icons in plain html. 

This code `<a href="#" title="MyTitle"><ion-icon name="logo-tux"></ion-icon></a>` renders the following icon with a tooltip on hover. I'm fetching icons using unpkg cdn.

![image](https://user-images.githubusercontent.com/10697837/185004709-4dc0a692-464d-4e1f-9f14-d019564fc972.png)

Is there any solution that has already been made available here to remove the tooltip and render the title only?

**Comment by iambozdar** [comment]
In [v5.2.0](https://github.com/ionic-team/ionicons/releases?page=2), developers introduced the following change. 
- add `<title>` to each svg, generated from the file name

**Comment by brandyscarney** [comment]
Thanks for the issue, closing this to track in #838.
