### ISSUE TITLE
Tiktok Icon not working with React Native Web

### ISSUE THREAD

**Issue by adherb** [ionic-team/ionicons#1095]
Hello,

This Tiktok icon is undefined when using it in React Native Web. I have tried using the name ```logo-tiktok``` and ```tiktok```, but the package cannot find the icon.

Here's my code:

```
import Ionicons from '@expo/vector-icons/Ionicons'

 <Ionicons name="logo-tiktok" size={30} color="white" />
 <Ionicons name="tiktok" size={30} color="white" />
```

I can see that the Tiktok icon is available, but I'm unsure why its not working.

**Comment by clement-avenel** [comment]
Hello @adherb, since this issue is not related to @ionic-team but to expo/vector-icons#228, it must be closed.
