### ISSUE TITLE
WhatsApp Business Icon

### ISSUE THREAD

**Issue by sirgatsen** [ionic-team/ionicons#1099]
Please consider adding a WhatsApp Business Icon

**Comment by xnousnow** [comment]
[Play store link here](https://play.google.com/store/apps/details?id=com.whatsapp.w4b&hl=ko&gl=US)

**Comment by amandaejohnston** [comment]
Thanks for the request. This has since been added as `logo-whatsapp`. 👍

**Comment by christian-bromann** [comment]
Consolidating into #1449
