### ISSUE TITLE
(ionicons 5/6) Excessive server requests to individual svg files

### ISSUE THREAD

**Issue by dylanharty** [ionic-team/ionicons#1102]
Hey ionic framework community,

We are using just ionicons v5 on our website and one of the on-going todo’s is to increase site speed. We have noticed that ion icons request each SVG file individually on first load which causes an exponential growth of server timings depending on how many are used on a page.

We have used ion icons v2 and v4 in the past and these come bundled with a font .SVG or .WOFF file. The new versions of ion icons use individual SVGs. Is there a way to request all icons in a single request or is this a feature that could be addressed in the future?

Thank you,

(I posted this on the forums with no reply, so posted here hoping for some input)

**Comment by JALabba** [comment]
You can download the designer pack, all the individual .svg files. Then you can repackage them in the format you want.

**Comment by liamdebeasi** [comment]
Thanks for the report. Can you please provide a GitHub repo that I can use to verify this behavior?
