### ISSUE TITLE
icon request: Virtual Private Network (VPN)

### ISSUE THREAD

**Issue by TalesMattos** [ionic-team/ionicons#1108]
### Describe the Icon

A icon for VPN (Virtual Private Network)

**Comment by harshsiri110** [comment]
I am adding an icon for VPN (Virtual Private Network)

**Comment by amandaejohnston** [comment]
Thanks for the request. We have a few existing icons that may work for this:
- `key`
- `lock-closed`
- `document-lock`
- `shield`
- `shield-checkmark`

Did you have something else in mind that isn't covered by those?
