### ISSUE TITLE
bug: Icons are not rendered when using capacitor's server.androidScheme that is not HTTP*

### ISSUE THREAD

**Issue by distante** [ionic-team/ionicons#1127]
### Current Behavior

When enabling a custom `androidScheme`, for example `myapp` all icons are broken.
```
179879a3-e56b-4526-bf9f-e91f4e9f797d:3631 Fetch API cannot load myapp://localhost/svg/ellipsis-vertical.svg. URL scheme "myapp" is not supported.
```

### Expected Behavior

The Icons should still working with custom server schemas.

### Steps to Reproduce

Create any empty Ionic-capacitor project and add this config
```
"server": {
    "androidScheme": "myapp"
  }
```

**Comment by liamdebeasi** [comment]
Thanks for the report. I recommend opening an issue on https://github.com/ionic-team/capacitor as Ionicons does not manage any of your native dependencies. If you think this is still a bug in Ionicons, please provide a GitHub repo with steps to reproduce the issue, and I will be more than happy to reopen this issue.
