### ISSUE TITLE
icon request: 

### ISSUE THREAD

**Issue by Santimartz12** [ionic-team/ionicons#1136]
### Describe the Icon

It would be great to add the logos of the basic programming languages

- Java
- C#
- php
- Ruby 
- etc...

### Links to Examples

https://icon-icons.com/es/icono/logo-taza-de-cafe-de-Java/4844
https://icon-icons.com/es/icono/C/132529
https://icon-icons.com/es/icono/prog-php/50777
https://icon-icons.com/es/icono/prog-ruby/50771
https://icon-icons.com/es/icono/C/132529

**Comment by liamdebeasi** [comment]
Hey there! We already have an open request for this: https://github.com/ionic-team/ionicons/issues/437 I am going to merge the two threads.
