### ISSUE TITLE
icon request: TikTok

### ISSUE THREAD

**Issue by pohek321** [ionic-team/ionicons#1138]
### Describe the Icon

TikTok Icon for TikTok Application

### Links to Examples

https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Fvector-art%2F2557421-tiktok-logo-black-mobile-social-media-icon&psig=AOvVaw08ghwSRCfwkH9rAH_Uhcn6&ust=1666231690987000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCIDJ6PGa6_oCFQAAAAAdAAAAABAE

### Additional Information

As users use your icons to create hyperlinks to their social media sites. This one would be useful.

**Comment by amandaejohnston** [comment]
Thanks for the request. This has since been added as `logo-tiktok`. 👍
