### ISSUE TITLE
Request: Xing icon

### ISSUE THREAD

**Issue by vanniktech** [ionic-team/ionicons#114]
A Xing icon would be great.

[Example](http://a5.mzstatic.com/us/r30/Purple6/v4/58/6d/0e/586d0efe-aad2-7f2d-87cc-812da087308b/mzl.iiydpbaa.175x175-75.jpg)

**Comment by appinio** [comment]
That would be strange - cause thing is the biggest job plattform in germany - 
Having this issue right now - please add it! 

Thanks alot

**Comment by vanniktech** [comment]
Yup that's the reason I wanted to have that icon. In Germany Xing is way more popular than LinkedIn hence most of the Germans only have Xing.
