### ISSUE TITLE
icon request: PIX logo

### ISSUE THREAD

**Issue by gusantoscode** [ionic-team/ionicons#1140]
### Describe the Icon

PIX is a new and very popular Brazilian payment method.

### Links to Examples

https://logospng.org/d/?l=aHR0cHM6Ly9sb2dvc3BuZy5vcmcvZG93bmxvYWQvcGl4L2xvZ28tcGl4LWljb25lLTEwMjQucG5n

**Comment by sean-perkins** [comment]
Hello, thank you for this request. 

This icon request is already tracked here: https://github.com/ionic-team/ionicons/issues/1083

Closing as a duplicate, please upvote that request!
