### ISSUE TITLE
icon request:  Hack The Box

### ISSUE THREAD

**Issue by inithinx** [ionic-team/ionicons#1158]
### Describe the Icon

Hackthebox Website icon.

### Links to Examples

https://app.hackthebox.com/images/logos/logo-htb.svg

**Comment by xnousnow** [comment]
Hackthebox logo is almost same as the box icon, so I think you can just use box icon for that.

**Comment by amandaejohnston** [comment]
Thank you for the request. The existing `cube` icon is identical to this logo, so I would recommend using that.
