### ISSUE TITLE
bug: `<title>` tag still exists in svg icon (ionicons 6.1.0)

### ISSUE THREAD

**Issue by jonz94** [ionic-team/ionicons#1168]
### Current Behavior

It seems like `ionicons` version 6.1.0 published on `npm` still have `<title>` tag inside the svg icon.

Screenshots from https://www.npmjs.com/package/ionicons?activeTab=explore

<img width="1116" alt="Screenshot 2023-01-18 at 04 16 46" src="https://user-images.githubusercontent.com/16042676/213002811-7e0a4145-2777-4772-a20d-e5a9665fb006.png">

So issues described in #838 are not completely resolved.

### Expected Behavior

The svg icon published on `npm` should not have any `<title>` tag by default.

### Steps to Reproduce

1. Create an Ionic Project via ionic cli
2. Update `ionicons` to 6.1.0
3. Add `<ion-icon name="accessibility-outline"></ion-icon>` on the page
4. `npm start`
5. Move mouse cursor on the icon, the `Accessibility` tooltip will show up

<img width="310" alt="Screenshot 2023-01-18 at 04 46 04" src="https://user-images.githubusercontent.com/16042676/213009070-fb0a3fbb-7b0c-4634-9910-deb8449c71c3.png">

### Code Reproduction URL

https://github.com/jonz94/ionicons-issue-1168

### Additional Information

Based on information provided https://github.com/ionic-team/ionicons/issues/838#issuecomment-835827036

Change following lines:

https://github.com/ionic-team/ionicons/blob/8c2a507fcff2cb5f2edff60357ffd7feb70bb987/scripts/build.ts#L169-L172

into:

```typescript
const optimizedCode = optimizedSvg.data.replace(
  /<svg (.*?)>/, 
  `<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512">`, 
); 
```

should be able to resolve the issue.

**Comment by DercilioFontes** [comment]
I'm facing the same issue yet in v6.1.0.

**Comment by liamdebeasi** [comment]
Thanks for letting us know. I will merge https://github.com/ionic-team/ionicons/pull/1169 once CI passes and then will publish a new release.

**Comment by liamdebeasi** [comment]
This has been resolved via https://github.com/ionic-team/ionicons/pull/1169. I will post an update here when the fix has been released.

**Comment by liamdebeasi** [comment]
A fix for this issue has been releases in Ionic 6.1.1. Thanks again for the report and the fix!
