### ISSUE TITLE
Using IonIcon in a Lit Element without CDN

### ISSUE THREAD

**Issue by jrj2211** [ionic-team/ionicons#1175]
I need an icon library for offline use so I can't use the CDN. I've looked back through tons of old issues with people asking how to use ionicons without the CDN script tag but there doesn't seem to be a clear answer. 

I'm trying to use the icon in a Lit Element. Ideally, I'd rather just import the library and have all icons availalbe without having to manually import an icon when I want to use it. I tried a suggestion from an older issue but it did not work:

```
import { defineCustomElements } from 'ionicons/dist/loader';
defineCustomElements(window);
```

I then tried importing the icon I want directly but I don't understand how to use it:

```
import { folderOpenOutline } from 'ionicons/icons';

class DestinationPicker extends LitElement {
  render() {
    return html`
      <ion-icon icon="${folderOpenOutline}"></ion-icon>
      <div>Choose folder</div>
    `;
  }
}
```

If I print out folderOpenOutline I get back
```
data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' class='ionicon' viewBox='0 0 512 512'><path d='M64 192v-72a40 40 0 0140-40h75.89a40 40 0 0122.19 6.72l27.84 18.56a40 40 0 0022.19 6.72H408a40 40 0 0140 40v40' stroke-linecap='round' stroke-linejoin='round' class='ionicon-fill-none ionicon-stroke-width'/><path d='M479.9 226.55L463.68 392a40 40 0 01-39.93 40H88.25a40 40 0 01-39.93-40L32.1 226.55A32 32 0 0164 192h384.1a32 32 0 0131.8 34.55z' stroke-linecap='round' stroke-linejoin='round' class='ionicon-fill-none ionicon-stroke-width'/></svg>
```

But that doesn't make sense as I still haven't imported the ion-icon web component itself. How can I do this?

I love using ion icons but it always is frustrating to try and get it to work on a non internet enabled project. It really would be nice to see this finally added to the usage documentation a there's issues going back to 2019 asking this same thing.

**Comment by liamdebeasi** [comment]
Thanks for the report. Do you have a sample app I can try?
