### ISSUE TITLE
bug: flip-rtl behavior isn't reactive when document dir changes

### ISSUE THREAD

**Issue by FranciskoNeves** [ionic-team/ionicons#1196]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v6.x

### Current Behavior

When I change the app to RTL, the ion-back-button arrow doesn't instantly changes to RTL, I need to change to another page to see the change.

### Expected Behavior

Right after change to RTL, the ion-back-button arrow turns 180 degrees.

### Steps to Reproduce

Navigate to a page with an ion-back-button, change document.documentElement.dir to 'rtl' and you will see that the arrow doesn't change

### Code Reproduction URL

https://github.com/FranciskoNeves/IonBackButtonRTL

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.3 (C:\Users\Francisco.neves\AppData\Roaming\nvm\v16.13.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.6.0
   @angular-devkit/build-angular : 15.1.1
   @angular-devkit/schematics    : 15.1.1
   @angular/cli                  : 15.1.1
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.6.1
   @capacitor/android : not installed
   @capacitor/core    : 4.6.1
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.1.0
   OS     : Windows 10

**Comment by mapsandapps** [comment]
Hi! Thanks for the report. Here's a dev build with a proposed fix if you'd like to test it:
```
npm install @ionic/angular@7.0.8-dev.11684448544.19bd9148 ionicons@7.1.1-dev.11684440744.15dddc23
```
