### ISSUE TITLE
icon request: X

### ISSUE THREAD

**Issue by larsvdd** [ionic-team/ionicons#1249]
### Describe the Icon

It's the new Twitter icon but the X

### Links to Examples

https://twitter.com/home

### Additional Information

Nuf said ;)

**Comment by hahwul** [comment]
Hi👋🏼
It looks like some time has passed since the issue was brought up. Is there any update on its status?

**Comment by mimoudix** [comment]
I need that X logo asap haha

**Comment by foxyyyyyyyyyyyyy** [comment]
Is there anything new on the request?

**Comment by IshanJ25** [comment]
@mapsandapps any update please?

**Comment by 238SAMIxD** [comment]
Will it be considered to add in the near future?

**Comment by abhibhat33** [comment]
Hello, any updates on this?

**Comment by missmerilu** [comment]
Hello! Any update?

**Comment by IshanJ25** [comment]
please provide an update for this

**Comment by liamdebeasi** [comment]
Hi everyone,

This was added in https://github.com/ionic-team/ionicons/pull/1371.
