### ISSUE TITLE
feat: build with `@stencil/core@^4`

### ISSUE THREAD

**Issue by mikaelkaron** [ionic-team/ionicons#1255]
### Describe Problem

At the moment `ionicons` is built with `@stencil/core@2.18.0`, it would be nice to have it built with `@stencil/core@^4` so that typings etc. would work in a `@ionic/core@^7.3` project.
`

### Describe Preferred Solution

Bump `@stencil/core` to `^4.0.5` (or something in the `^4` series)

**Comment by liamdebeasi** [comment]
Thanks for the report. Ionicons 7.2 now used Stencil 4, so I am going to close this.
