### ISSUE TITLE
icon request: block

### ISSUE THREAD

**Issue by richard-flock** [ionic-team/ionicons#1267]
### Describe the Icon

Used to indicate a block feature in icons.

![Screenshot 2023-08-23 at 2 41 01 PM](https://github.com/ionic-team/ionicons/assets/122649267/be8e374e-845b-4485-86e5-dab72b9ceb03)

### Links to Examples

Material Symbols: Block
https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Ablock%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048

Material Icons: Block
https://fonts.google.com/icons?selected=Material+Icons+Outlined:block:&icon.query=block&icon.style=Outlined&icon.set=Material+Icons

### Additional Information

Searched existing icons, but couldn't find a match or equivalent.

**Comment by mapsandapps** [comment]
Hi, it sounds like the `ban` icon will work for what you need. I'm going to close this out.
