### ISSUE TITLE
bug: Style does not work when className is written on the ion-icons tag(5.5.2)

### ISSUE THREAD

**Issue by Hongheesun** [ionic-team/ionicons#1270]
### Current Behavior

 I added <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>" in body tag of index.html of react project. But If I use the <ion-ions> tag and use "className", the class name does not apply, so the style does not work, and the class name is read and the style is applied only when I use "class". Is the cause of this problem appearing as a version of ion-icons?

### Steps to Reproduce

1. react project
2. using ion-icons(version 5.5.2)
3. making a comparison of style between className and class

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionicons, please open a new issue and ensure the template is fully filled out. Thank you!
