### ISSUE TITLE
Request: Zoom in/out icon

### ISSUE THREAD

**Issue by jbrantly** [ionic-team/ionicons#128]
I would like to request a zoom in/out icon, for example a magnifying class with a plus or minus in it.

**Comment by jimitndiaye** [comment]
Was this ever added?

**Comment by bensperry** [comment]
It will not be added in the foreseeable future.

**Comment by mkov88** [comment]
would like to also request zoom in zoom out. It's hardly "specific" as it can be used in a wide variety of cases.

**Comment by rtpHarry** [comment]
I'm implementing a cropper for my profile pic component and have built some buttons to zoom in and out but having to just use + and - at the moment
