### ISSUE TITLE
request: npm package

### ISSUE THREAD

**Issue by aeosynth** [ionic-team/ionicons#129]
i like using a single package manager for my entire stack

**Comment by hawkrives** [comment]
I second this plea for a npm package.

**Comment by sandelius** [comment]
+1

**Comment by jolafrite** [comment]
+1

**Comment by patrickomeara** [comment]
+1

**Comment by michaelhogg** [comment]
+1

**Comment by feltnerm** [comment]
+1! We are using ionicons here at Widen (fellow Madison-ian), and would love to be able to pull the built/distrubted files down using npm (I'd expect the sources would be available via another route such as github). Soon, [npm will be more friendly towards non-javascript bundles](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging) such as this, but for now it is still possible. In fact, we are publishing images, js, and css with [fineuploader](https://www.npmjs.com/package/fine-uploader).

I'm willing to help any way I can.

**Comment by aSoftskillzz** [comment]
+1

**Comment by topaxi** [comment]
I'd like to use ionicons with npm too, bower is not an option. Installing manually implies checking for new releases periodically which is stupid (`npm outdated` ftw).

**Comment by tbranyen** [comment]
FWIW I published this package to NPM.  The project owners locked my thread so if you'd like to request new versions, please post in here or contact me directly.

**Comment by kyrylkov** [comment]
+1

**Comment by omeid** [comment]
Any reason this package isn't on npm?

**Comment by amilajack** [comment]
This can actually be done with:
```bash
npm install ionicons --save
```

but it is not documented :( I'll add make a PR to add this to the readme.

**Comment by tooomm** [comment]
there is a pr: https://github.com/ionic-team/ionicons/pull/425
