### ISSUE TITLE
bug: init error ionIcons. Cannot access 'b' before initialization

### ISSUE THREAD

**Issue by Jodelopa** [ionic-team/ionicons#1295]
### Current Behavior

since ionIcon release v7.2.1 there is an init error on my **release** build of my vite-react project, dev build is runnnig fine.

![ion](https://github.com/ionic-team/ionicons/assets/103248054/ad632752-6b6b-4f6e-96d0-3b80c4fa680b)

downgrade to v7.1.2 solves the error

### Expected Behavior

app initializes correctly 

### Steps to Reproduce

create an ionic vite-react-typscript project and use an ionIcon, do a release build

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionicons, please open a new issue and ensure the template is fully filled out. Thank you!
