### ISSUE TITLE
feat: add Web Types

### ISSUE THREAD

**Issue by piotrtomiak** [ionic-team/ionicons#1300]
### Describe Problem

To improve developers experience in WebStorm and other JetBrains IDEs, `ionicons` library can provide a Web-Types JSON file, which contains metadata of the library's Web Components. Developers will benefit from a code completion for attribute names and for icons:
<img width="729" alt="list of icons" src="https://github.com/ionic-team/ionicons/assets/4244523/9667ea29-00b7-4f86-8118-909f0d344f58">

### Describe Preferred Solution

This issue will be followed by a PR to include Web Types JSON generation in the build and its distribution with the library.

**Comment by liamdebeasi** [comment]
Added in https://github.com/ionic-team/ionicons/pull/1301
