### ISSUE TITLE
bug: Memory Leak with Clusterize.js "Detached Elements"

### ISSUE THREAD

**Issue by viniciuscenci** [ionic-team/ionicons#1307]
### Current Behavior

When using clusterize.js + ionicons module, ionicons keeps references in memory, the list of "Detached Elements" keeps growing.

### Expected Behavior

Elements to be Garbage Collected.

### Steps to Reproduce

1. Create a instance of Clusterize.js with 1000 items, using the tag `<ion-icon name="arrow-forward-circle-outline"></ion-icon>`

![image](https://github.com/ionic-team/ionicons/assets/2103416/29228596-11ef-4640-ae01-d17f2b2fb2ea)

2. Filter the list using the button 
![image](https://github.com/ionic-team/ionicons/assets/2103416/e777e2f8-ac89-4e87-99c2-fdd35d6fdc24)
Or even just by scrolling the list...

3. Check the "Detached Elements" (in Edge) or in Chrome

![image](https://github.com/ionic-team/ionicons/assets/2103416/ce7513f7-887e-47e3-aa38-37e7823c1afd)

### Code Reproduction URL

https://codepen.io/viniciuscenci/pen/RwvvrGL

### Additional Information

In the provided code, by replacing the `<ion-icon>` tag with regular `<svg>` or svg references, the problem is **solved**, but the convenience of `<ion-icon>` tag is lost =(

![image](https://github.com/ionic-team/ionicons/assets/2103416/af89f12a-26c6-4999-9576-c19d3b78cc26)

> [!NOTE]
> It get event worst when there is multiple icons, divs and other elements inside de list item, since the number of detached nodes is basically multiplied.

**Comment by liamdebeasi** [comment]
Hey there,

Apologies for the delay. Are you able to reproduce this issue without Clusterize.js?
