### ISSUE TITLE
incorrect icon: ellipsis-horizontal-circle

### ISSUE THREAD

**Issue by coatesap** [ionic-team/ionicons#1320]
### Describe the Issue

It's expected that the icon is 'filled', whereas it is the same as `ellipsis-horizontal-circle-outline`.

![image](https://github.com/ionic-team/ionicons/assets/1926626/17ffeaec-b93c-47a9-80a8-2d09f014c4ff)

This also is the case for `ellipsis-vertical-circle`.

### Expected Behavior

The icon should be distinct from the outline variant and be 'filled' (possibly looking the same as the current 'sharp' variant).

**Comment by liamdebeasi** [comment]
Hey there,

This is fixed in https://github.com/ionic-team/ionicons/pull/1353. The fix will be available in an upcoming release of Ionicons.
