### ISSUE TITLE
icon request: Bank Account Icon

### ISSUE THREAD

**Issue by AlexIsTripping** [ionic-team/ionicons#1322]
### Describe the Icon

An Icon that is a bank

### Links to Examples

https://fonts.google.com/icons?selected=Material+Symbols+Outlined:account_balance:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=bank

**Comment by amandaejohnston** [comment]
Thank you for the request. I'm going to close this as a duplicate of https://github.com/ionic-team/ionicons/issues/409.
