### ISSUE TITLE
icon request: Mastodon

### ISSUE THREAD

**Issue by compwiz32** [ionic-team/ionicons#1331]
### Describe the Icon

Mastodon is a decentralized social media network. The icon is a logo of an elephant and a chat bubble. 

### Links to Examples

https://www.iconarchive.com/show/fontawesome-brands-icons-by-fa-team/FontAwesome-Brands-Mastodon-icon.html

**Comment by mapsandapps** [comment]
Hi, thank you for your icon request. There is currently an icon available for Mastodon as `logo-mastodon`.

**Comment by compwiz32** [comment]
Hello there! Sorry if it's a duplicate, but I wanted to let you know that when I was searching for icons on your website, I couldn't find any results for Mastodon. So how would I know that there was an icon that exists already? 

![image](https://github.com/ionic-team/ionicons/assets/16006392/5a866a09-bf86-4dd7-bccb-9228f4c0c124)

**Comment by compwiz32** [comment]
I found the issue. I was using the v4 search.... i see it in the v5 search.
