### ISSUE TITLE
Logo request: X

### ISSUE THREAD

**Issue by nilaysarma** [ionic-team/ionicons#1333]
Add the new Twitter logo X
![images (1).png](https://github.com/ionic-team/ionicons/assets/79686507/2c5f4234-7dc3-478a-9502-2e7a2389a56d)

**Comment by mapsandapps** [comment]
Hi, thank you for your logo request. I'm going to close this as a duplicate of #1249

**Comment by nilaysarma** [comment]
> Hi, thank you for your logo request. I'm going to close this as a duplicate of #1249 

Oh, I didn't saw that. Can I get to know when the X logo will be added?
