### ISSUE TITLE
bug: "person-circle-outline" is not affected by "--ionicon-stroke-width"

### ISSUE THREAD

**Issue by ozgurg** [ionic-team/ionicons#1357]
### Current Behavior

When I set a custom stroke value for `ion-icon` with `--ionicon-stroke-width`, [as the docs say](https://ionic.io/ionicons/usage), it works for icons that I test, but `person-circle-outline` is not affected by it.

### Expected Behavior

`person-circle-outline` should change its stroke width like other icons.

### Steps to Reproduce

1) Add this HTML:
```html
<ion-icon name="person-circle-outline"></ion-icon>
<ion-icon name="home-outline"></ion-icon>
<ion-icon name="chatbubbles-outline"></ion-icon>
<ion-icon name="notifications-outline"></ion-icon>
```

2) Add this CSS:
```css
ion-icon {
   --ionicon-stroke-width: 16px
}
```

3) You should see the stroke width differences between these icons.

![2024-03-28_14-10](https://github.com/ionic-team/ionicons/assets/6717356/77c10243-f1af-408a-bff3-6452a983f514)

### Code Reproduction URL

https://codepen.io/ozgurg/pen/RwOZOzE

**Comment by liamdebeasi** [comment]
Thanks for the report. It looks like the `path` elements for the `person-circle-outline` icon are not getting the [`.ionicon-stroke-width` class](https://github.com/ionic-team/ionicons/blob/e81ddbdb4be95c21cb76c86e4230bcbd499fbc02/src/components/icon/icon.css#L23). As a result, `--ionicon-stroke-width` does not apply.

**Comment by liamdebeasi** [comment]
Apologies, it looks like this is the same issue as https://github.com/ionic-team/ionicons/issues/923, so I am going to merge the two.
