### ISSUE TITLE
incorrect icon: Update twitter to X icon

### ISSUE THREAD

**Issue by Diogo-Coding** [ionic-team/ionicons#1364]
### Describe the Issue

Not on date icon of Twitter now known as X

### Expected Behavior

New Icon of X social media

**Comment by amandaejohnston** [comment]
Thank you for the issue. I'm going to close this as a duplicate of https://github.com/ionic-team/ionicons/issues/1249.

**Comment by NewWorldMan** [comment]
How do you get the source code to update these icons? I downloaded ver 5 which appears to be 2020? Is there a newer version somewhere?
