### ISSUE TITLE
feat: Why is your service blocked in Russia?

### ISSUE THREAD

**Issue by inturbodev** [ionic-team/ionicons#1378]
### Describe Problem

Why is your service blocked in Russia? Have you really sold yourself to the politics of the West and are defending stinking crests (Ukrainians), these are extremely vile people who DO NOT give a damn about your services, they only need your money and you will also turn out to be shit in their minds! Come to your senses, people!!!

**Comment by sean-perkins** [comment]
Hatred in any form is not tolerated in our community.
