### ISSUE TITLE
feat: X FORMERLY KNOWN AS TWITTER

### ISSUE THREAD

**Issue by DennyWEBDEV** [ionic-team/ionicons#1397]
### Describe Problem

Hey Admin I'm Denny a web designer for Quik Cart Finds. I use your website for all my icons because i love your work but recently i have this problem of finding the newly updated icon for twitter now known as X....for now i'm currently using the old bird logo and yes I could've gotten the newly updated logo elsewhere but no. I LOVE ION ICONS so whenever you're able to......Just kindly update the older icon. Thanks for considering my request

**Comment by jcesarmobile** [comment]
X logo was added, but twitter logo was maintained
https://github.com/ionic-team/ionicons/pull/1371

**Comment by DennyWEBDEV** [comment]
Awesomeeeeee
