### ISSUE TITLE
icon request: wishlist icon 

### ISSUE THREAD

**Issue by GauravThakur-git** [ionic-team/ionicons#1407]
### Describe the Icon

A wishlist icon should be added to ionic 

### Links to Examples

![image](https://github.com/user-attachments/assets/058613ef-d2ac-4fea-ba77-f9cfcecb0e5c)

**Comment by jlcvp** [comment]
we already have heart icons, including sliced one that you could use for "remove from wishlist" 
<img width="649" alt="image" src="https://github.com/user-attachments/assets/d22495a2-253d-4491-a225-00e73a3fd08d">

**Comment by GauravThakur-git** [comment]
You should add something to the search logic so that searching "wishlist" also brings this heart icon.
