### ISSUE TITLE
Google chrome does not display icons

### ISSUE THREAD

**Issue by Zurgak** [ionic-team/ionicons#146]
Hello there! For some reason google chrome does not display ion icons. Safari displays them fine but chrome not.

What is the problem in here?

Css included in file, 
    <link rel="stylesheet" type="text/css" media="screen" href="css/ionicons.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="css/ionicons.css">

Thank you.

**Comment by superlativo77** [comment]
The same problem here. Works in Firefox but not in Chrome.

**Comment by joshuaalvaro** [comment]
Same problem here. Works only on Firefox but not in chrome, opera, and others.
