### ISSUE TITLE
many icons missing

### ISSUE THREAD

**Issue by calendee** [ionic-team/ionicons#174]
I'm assuming this is really an Ionicons issues vs. Ionic.

There are many missing Ionicons.

Sample Codepen : http://codepen.io/calendee/pen/emJxyv

Releases : Ionic Nightly and Beta 13.

**Comment by geoffw8** [comment]
Yep - this got me too. Thanks for the link.

**Comment by chuglydude** [comment]
ok

**Comment by DavidFrahm** [comment]
Can we expect a refresh to current Ionicons with the next Ionic Framework release?
