### ISSUE TITLE
Add title to result icons

### ISSUE THREAD

**Issue by cfjedimaster** [ionic-team/ionicons#190]
Each icon LI element on the web page should use title="x" so a user can mouseover and see the name of the icon.

**Comment by chuglydude** [comment]
Yep it should

**Comment by bensperry** [comment]
Good idea!

**Comment by chuglydude** [comment]
(:

**Comment by sumitparakh** [comment]
Hi @IonicProSupport . Any update on this issue?

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. I am going to merge this with https://github.com/ionic-team/ionicons/issues/388.
