### ISSUE TITLE
How can I use this fonts in my photoshop while design

### ISSUE THREAD

**Issue by themefisher** [ionic-team/ionicons#249]
Really amazing collection .. But I want to use them in my design. Let me know how can I do that.
Thanks

**Comment by cannap** [comment]
With the Charmap on Windows but is horrible

**Comment by jbraithwaite** [comment]
If you are on a mac: http://www.poynton.com/notes/misc/mac-unicode-hex-input.html

**Comment by dallasbpeters** [comment]
I just activate the font on the system and then use the cheatsheet.html to copy the icon from the "Selectable" bit.

**Comment by cannap** [comment]
omg thanks  I have never seen the Selectable thing :dancer:

**Comment by themefisher** [comment]
Thanks all.I just found their cheat sheet link (http://ionicons.com/cheatsheet.html ) . And it works fine in my computer ...

**Comment by liamdebeasi** [comment]
Hi everyone,

Thanks for the report and apologies for the delay. I am going to close this as the issue as Ionicons uses SVG data instead of fonts now. You can access the SVG data here: https://github.com/ionic-team/ionicons/tree/main/src/svg
