### ISSUE TITLE
Excess whitespace

### ISSUE THREAD

**Issue by eivindfjeldstad** [ionic-team/ionicons#25]
All the icons are padded to the same width, which makes it difficult to control spacing between the icons and other elements. Have you considered cropping the SVGs to get rid of excess whitespace? IMO that would make the icons more flexible.

**Comment by nickwinger** [comment]
actually with ionic 5, this is issue is again here.
There is spacing on the icons so you cannot style things pixel exact. This is actually a really big issue (when it comes to accurate styling)

**Comment by HazzMan2409** [comment]
Yes, I am seeing what nickwinger is seeing with Ionic 5 svgs. A quick workaround is to open the svg in Inkscape, select everything and resize based on the selection (ctrl + shift + r). The svg should (hopefully) now be set to the height and width of the contents of the svg.
