### ISSUE TITLE
Please add VK (social network) icon

### ISSUE THREAD

**Issue by Dennizka** [ionic-team/ionicons#255]
Good day ionicons team!

Please add VK (social network www.vk.com) icon (English letter "B"). 
You can find official logo here - https://vk.com/about?w=wall-47200925_1 (two top links below post). 

Many sites and templates is using our icons and VK icon is very popular in Russia and exUSSR countries.

Thank you!

**Comment by Altglance** [comment]
+1, FontAwesome have nice one http://fontawesome.io/icon/vk/

**Comment by appigram** [comment]
+1, please

**Comment by VladShcherbin** [comment]
+1

**Comment by rustemgareev** [comment]
+1 for this, please!

**Comment by eek4ever** [comment]
+1

**Comment by lis4ever** [comment]
+1

**Comment by Stajor** [comment]
+1

**Comment by isdenya** [comment]
+1

**Comment by artemukolov** [comment]
+1

**Comment by AleksC1976** [comment]
+1

**Comment by Edaks** [comment]
+1

**Comment by romanxbanks** [comment]
+1

**Comment by dumitru05** [comment]
+1

**Comment by slomkae** [comment]
+1

**Comment by Edaks** [comment]
https://vk.com/about

**Comment by bopoda** [comment]
+1
any updates?

**Comment by ivanovevgeny** [comment]
+1

**Comment by bopoda** [comment]
Hey, are you going to do it?
Thx

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. This icon is available in the latest version of Ionicons: https://ionic.io/ionicons
