### ISSUE TITLE
OS X

### ISSUE THREAD

**Issue by mrgudezovic** [ionic-team/ionicons#328]
Hello guys,

I've tried to search before posting but I couldn't quick find anything about it. Question is simple, are we available to use tiff font on Apple products ? I've tried to instal the font and test few from cheatsheet but I keep to get this message :

Could not complete the Paste Text command because the clipboard data is empty or invalid.

Did I miss something ? 

Thank you in advance 
Misa_

**Comment by adamdbradley** [comment]
I would imagine one of our font formats should work, but our focus is really making sure it works on the web platform and haven't tested outside of this.

**Comment by mrgudezovic** [comment]
Thanks for your reply Adam, for some reason, and luckily it works now.

**Comment by liamdebeasi** [comment]
Hi everyone,

Thanks for the report and apologies for the delay. I am going to close this as the issue as Ionicons uses SVG data instead of fonts now.
