### ISSUE TITLE
Request: MS Dos & Terminal icon

### ISSUE THREAD

**Issue by pederjohnsen** [ionic-team/ionicons#333]
I'd be nice to see an ms dos and terminal icon in this pack. Awesome icon font btw! :+1:

**Comment by bensperry** [comment]
Thanks @pederjohnsen. Haha, that ms dos logo tho... won't be adding that. But, I think a terminal icon would be a welcome addition. Thoughts @adamdbradley?

**Comment by pederjohnsen** [comment]
I can live without a ms dos icon :P, but a terminal one would be great :+1:

**Comment by bensperry** [comment]
Cool. Will be making this soon.

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. I am going to close as this should be resolved in the latest version of Ionicons.
