### ISSUE TITLE
Request: Server / Hardware Icon

### ISSUE THREAD

**Issue by mattalco** [ionic-team/ionicons#346]
I had an open issue at https://github.com/driftyco/ionicons/issues/320 but the bot closed it.

I just wanted to follow up and see if this might make it in the next release.
![cd28690a-6b71-11e5-90b9-146132f48cfe](https://cloud.githubusercontent.com/assets/13972013/12431548/0bccaf90-bec4-11e5-9846-aa23a1795275.png)
![capture](https://cloud.githubusercontent.com/assets/13972013/12431556/21d58a46-bec4-11e5-8774-bed74569a9ae.PNG)

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. I am going to close as this should be resolved in the latest version of Ionicons.
