### ISSUE TITLE
builder dir does not appear using bower

### ISSUE THREAD

**Issue by franzz2000** [ionic-team/ionicons#347]
Hi,

I'm using ionicons with "bower install --save ionicons". I see that the builder folder does not install.

Can you tell me how to install ionicons with the builder folder?

Thanks

**Comment by alexdresko** [comment]
I would like the builder folder to be included with bower as well. Importing the less/scss files into my existing less/scss files seems useful.

**Comment by liamdebeasi** [comment]
Hi everyone,

Thanks for the report and apologies for the delay. I am going to close as Ionicons is now installed using NPM or Yarn.
