### ISSUE TITLE
Release 2.0.1 has 2.0.0 version numbers

### ISSUE THREAD

**Issue by hugovk** [ionic-team/ionicons#349]
The CSS files have 2.0.0 as the version number in the 2.0.1 release:

https://github.com/driftyco/ionicons/blob/v2.0.1/css/ionicons.css#L3
https://github.com/driftyco/ionicons/blob/v2.0.1/css/ionicons.min.css#L2

They also refer to 2.0.0: `"../fonts/ionicons.eot?v=2.0.0"`, (which may or not be a problem if they didn't change).

Consider creating a RELEASING.md checklist:

https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fgithub.com%2F+inurl%3ARELEASING.md

**Comment by frg** [comment]
+1

**Comment by alandeg** [comment]
+1

Please fix this, it's currently broken when importing using SASS and JSPM

**Comment by hugovk** [comment]
Closed this old issue, probably no longer relevant.
