### ISSUE TITLE
V3 - Feature Request - "record" icon

### ISSUE THREAD

**Issue by danbucholtz** [ionic-team/ionicons#355]
We make extensive use of colored circles in our apps.  Weird - I know.  Anyway, the "record" ionicon was perfect for this because it was so easy to use with the ion-list components to display on the left, right, etc.  

Much easier for us than generating an image, figuring out size, etc.

Any chance you could make this icon again?

**Comment by poohnikkah** [comment]
Yes

**Comment by amandaejohnston** [comment]
Thank you for the request! It sounds like the `ellipse` icon is what you're looking for; the filled variant is just a solid circle. I'm going to close this out with that in mind, but let me know if you wanted something else.
