### ISSUE TITLE
Didn't work

### ISSUE THREAD

**Issue by mafamac** [ionic-team/ionicons#360]
Hello Guys,

I tried this:
- I Downloaded the file from: http://design.ubuntu.com/wp-content/uploads/logo-ubuntu_cof-orange-hex.svg
- I renemed file to logoteste.svg
- I runned:
  **python ./builder/generate.py Generate Fonts**
  Generate Fonts
  Copyright (c) 2000-2012 by George Williams.
  Executable based on sources from 14:57 GMT 31-Jul-2012-ML.
  Library based on sources from 14:57 GMT 31-Jul-2012.
  Load Manifest, Icons: 736
  New Icon: 
  -logoteste
  -0xf145
  Failed to parse color 
  Failed to parse color 
  Save Manifest, Icons: 737
  Save Build, Icons: 736
  Generate SCSS
  Generate CSS From SCSS
  Generate Minified CSS From SCSS
  Generate LESS
  Generate Cheatsheet
  Generate component.json
  Generate composer.json
  Generate bower.json
- I moved css, font, scss to <workdir>/www/lib/ionic/css/
- In <file>.html i inserted this line:
  <i class="icon ion-logoteste"></i>
  and it didin't work
  if i  change to
  <i class="icon ion-plane"></i>

it's work

**Comment by mokrea** [comment]
worked...

i missed include reference to ionicons.css in my project.

**Comment by liamdebeasi** [comment]
Hi everyone,

Thanks for the report and apologies for the delay. I am going to close as there is not enough information for us to verify this bug. If this is still a problem with the latest version of Ionicons, please reply to this thread with a GitHub repo that we can use to verify the reported behavior.
