### ISSUE TITLE
Set embeddeble to 1 for the ttf-version

### ISSUE THREAD

**Issue by Suven** [ionic-team/ionicons#362]
It seems like you need to provide a special flag inside the ttf-font for WP8 in order to make sure the font is always correctly displayed, otherwise the browser / webview just prints the generic UTF8-Box.

I checked ionicons.ttf with a tool called ttfedit which indeed states that the 'legal right for embedding' are set to 0.

Further reading:
- https://en.wikipedia.org/wiki/TrueType#Embedding_protection
- https://sourceforge.net/projects/ttfedit/ (make sure to switch to View / Show advanced)
- http://stackoverflow.com/a/20573678

**Comment by liamdebeasi** [comment]
Hi everyone,

Thanks for the report and apologies for the delay. I am going to close this as the issue as Ionicons uses SVG data instead of fonts now.
