### ISSUE TITLE
Add card icon

### ISSUE THREAD

**Issue by erswelljustin** [ionic-team/ionicons#368]
Please add:

ion-card as iOS Outline Style
ion-gbp "£"

Great icon set thanks!

**Comment by amandaejohnston** [comment]
Thank you for the requests! I know it's been a while, but do you remember what specific sort of icon you were looking for with the `ion-card` idea? Do you have examples?

We have a couple other open feature requests for the GBP sign. To keep discussion organized, I'll use https://github.com/ionic-team/ionicons/issues/376 as the main one there, and use this one to track the card idea.
