### ISSUE TITLE
Request : Floppy Icon

### ISSUE THREAD

**Issue by guruganeshm** [ionic-team/ionicons#370]
Floppy Icon also known as Save Icon in the web apps. we must have it in this pack.

TIA

**Comment by ginodeis** [comment]
+1

**Comment by CanKattwinkel** [comment]
how can that be missing? +1

**Comment by kabus202** [comment]
+1

**Comment by diegolma** [comment]
+1

**Comment by Langstra** [comment]
This idea has been issued here before https://github.com/driftyco/ionicons/issues/175. Even though I think it should be included, there are also good reasons not to include it. It offers a chance to introduce a symbol that does not exist anymore. Even though a lot of "older" people do recognize it, younger people do not. I think we should use a different symbol for saving things, putting them in the cloud, or maybe a lock or a safe.

**Comment by mebibou** [comment]
Material Design still has this icon though: https://material.io/icons/#ic_save

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. I am going to close as this should be resolved in the latest version of Ionicons.
