### ISSUE TITLE
Can I contribute icons to the set ? 

### ISSUE THREAD

**Issue by designcrumble** [ionic-team/ionicons#374]

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for opening an issue and apologies for the delay. We do accept contributions from the community. We require that each contribution has a GitHub issue associated with it first. For example, if you are fixing a bug in Ionicons, make sure that the bug has an open issue. Please see [our contributing guide](https://github.com/ionic-team/ionicons/blob/main/.github/CONTRIBUTING.md) for more on how to contribute. I am going to close this, but let me know if you have any additional questions.
