### ISSUE TITLE
Request: Suppress (no-smoking icon without the cigarette)

### ISSUE THREAD

**Issue by alexgoldstone** [ionic-team/ionicons#383]
The no-smoking icon in Ionicons 3.0 without the cigarette would make a very useful and general purpose 'suppress' icon.

**Comment by brandyscarney** [comment]
Thank you for the issue! This has since been added as the `ban` icon, you can see it in the documentation [here](https://ionic.io/ionicons).

```
<ion-icon name="ban"></ion-icon>
```

![Screen Shot 2022-09-27 at 7 13 10 PM](https://user-images.githubusercontent.com/6577830/192653610-3499105c-df5a-427d-951a-b21259d1b4bb.png)
