### ISSUE TITLE
@import "ionicons.scss" doesn't work

### ISSUE THREAD

**Issue by guoyunhe** [ionic-team/ionicons#393]
main.scss

```
$ionicons-font-path: "../font";
@import "node_modules/ionicons/dist/scss/ionicons";
```

Folders:

```
css
|-- main.css
|-- main.css.map

font
|-- ionicons.eot
|-- ionicons.svg
|-- ionicons.ttf
|-- ionicons.woff
|-- ionicons.woff2

node_modules
|-- ionicons
    ...

src
|-- sass
    |-- main.scss
```

When compile scss with gulp, output css seems fine but all icons are missing and here is no styles applied to `.icon-*` elements.

**Comment by ananth-chiselkraft** [comment]
same problem occured to me as well.

Apparently the **.icons** class is missing in the compiled css and contains **.ion** instead.
