### ISSUE TITLE
Heterogeneous size in icons (v3)

### ISSUE THREAD

**Issue by deoqc** [ionic-team/ionicons#400]
I finding that the icon sizes are not perfectly homogeneous. This happens inside a _iOS_ and across _iOS_ and _Android_ (aka _md_).

For example, the `ios-help` is much smaller than the other icons in _iOS_ (like `ios-setting`) and also w/ respect to `md-help`. Or `ios-close`, which is much smaller than `md-close`.

Is this the intended behaviour or something that will be fixed?

Thanks

**Comment by mickeyl** [comment]
Agreed. That's one of my major griefs with FontAwesome. It's better (although not perfect yet) with Ionicons, that's why I want to switch from FA to ION when 3.0 comes out.

**Comment by liamdebeasi** [comment]
Hi everyone,

Thanks for the report and apologies for the delay. I am going to close as this issue should be resolved on the latest version of Ionicons.
