### ISSUE TITLE
Design Repeat or Replay icon

### ISSUE THREAD

**Issue by ali-master** [ionic-team/ionicons#404]
Hi Dear,

thanks for sharing ionicons, the ionicons package is very nice. I just use this.
If you have free time, please design the repeat and replay icon for use into the web player.
Thanks to anyway.

Have a good day.

**Comment by amandaejohnston** [comment]
Thank you for the request! We now have a `repeat` icon that should suit your needs, so I'll close this out. Let me know if you needed something different.
