### ISSUE TITLE
Database Icon

### ISSUE THREAD

**Issue by danbucholtz** [ionic-team/ionicons#407]
I think a database icon similar to the old firebase icon would be used frequently.  Is this something we could make an icon for?

Thanks,
Dan

**Comment by designcrumble** [comment]
@danbucholtz If you want I can design one and add it here. I don't know what are the guidelines to contribute here ?

**Comment by bensperry** [comment]
I can add this to the next (v4) version. Stay tuned...

**Comment by liamdebeasi** [comment]
The team felt that there was not enough distinction between a server icon and a database icon to warrant separate icons. As a result, In https://github.com/ionic-team/ionicons/pull/1259 we updated the server icon to help make it usable as a database icon too. This change will be available in an upcoming minor release of Ionicons.
