### ISSUE TITLE
Weird issue with ionicons

### ISSUE THREAD

**Issue by HamzaLJ** [ionic-team/ionicons#411]
I want to show the following icon with this class name:

> ion-iso-search

When I include the CDN in my HTML:

> ```
>    <link rel="stylesheet" type="text/css" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
> ```

It works fine as I want to see the normal version of the icons; however, when I replace the CDN link with the downloaded version I have:

> ```
>  <link rel="stylesheet" type="text/css" href="lib/ionicons/dist/css/ionicons.min.css">
> ```

The `ion-iso-search` shows in bold, even the other icons change, which looks really weird, can you you tell me what's wrong?

**Comment by chander12shekhar** [comment]
@HamzaLJ 
CDN lib contains links for fonts family and its located in folder ../fonts/ionicons.eot?v=2.0.1
So if you download only ionicons.min.css then fonts folder will not be accessible in your local directory.
Please download fonts folder also and place then according to ionicons.min.css

**Comment by liamdebeasi** [comment]
Hi everyone,

Thanks for the report and apologies for the delay. I am going to close as this should be resolved in the latest version of Ionicons.
