### ISSUE TITLE
CDN for ionicons 3.0

### ISSUE THREAD

**Issue by snarf1974** [ionic-team/ionicons#413]
When will http://ionicons.com/ have an updated CDN for ionicons 3.0 please?

**Comment by laurentpayot** [comment]
Is it planned at least?

**Comment by liamdebeasi** [comment]
Hi everyone,

Thanks for the report and apologies for the delay. I am going to close as this issue should be resolved on the latest version of Ionicons. You can access Ionicons from the Unpkg CDK: https://unpkg.com/browse/ionicons

You can also attach a version to the URL to get a specific version: https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js

**Comment by liamdebeasi** [comment]
Hi everyone,

Thanks for the report and apologies for the delay. I am going to close as this issue should be resolved on the latest version of Ionicons. You can access Ionicons from the Unpkg CDK: https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js
