### ISSUE TITLE
Star "jumps" when changed with Star-Outline

### ISSUE THREAD

**Issue by cnothegger** [ionic-team/ionicons#416]
Hi,
I'm writing a rating system and use ionicons. 
When the user rates a product the "star-outline" Ionicon gets replaced with "star" Ionicon. 
The icon then "jumps" some pixels to left. The reverse way from "star" icon to "star-outline" icon the Icon jumps some pixels right.
I assume that the icons are positioned different.
Can you give me hints how to fix this?

Thank you very much

**Comment by brandyscarney** [comment]
Thank you for the issue and sorry for the delay in responding. I am not able to reproduce this using the latest version of Ionicons. Here is a code example: https://stackblitz.com/edit/47hhyf?file=index.html

If you are still running into this, please provide a code reproduction. Thank you!
