### ISSUE TITLE
request: sort icon with both up and down arrow in one

### ISSUE THREAD

**Issue by crazyair** [ionic-team/ionicons#424]
up  and  dowm  is one icon

**Comment by qq645381995** [comment]
sort

**Comment by stanleyxu2005** [comment]
Same question here. I'd vote for adding this icon http://fontawesome.io/icon/sort/
The only reason I have to keep FontAwesome is this icon! Hope ionicons will have this shortly.

**Comment by basvdijk** [comment]
This icon would also allow to make a distinguish between sorting and filtering

**Comment by Frieder-AirLST** [comment]
I would love to have this!

**Comment by liamdebeasi** [comment]
This is available in Ionicons 7.1 under the "chevron-expand" icon.

**Comment by IsaacInsoll** [comment]
Thanks, couldn't figure out how to find it :)
