### ISSUE TITLE
IOS 10 Beta version ionicions some time not showing

### ISSUE THREAD

**Issue by bala8103** [ionic-team/ionicons#426]
IOS 10 Beta version update after ionicions some time not showing

**Comment by springHyc** [comment]
IOS 10.0.1 version has the same black and white phenomenon.

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. I am going to close as there is not enough information for us to verify this bug. If this is still a problem with the latest version of Ionicons, please reply to this thread with a GitHub repo that we can use to verify the reported behavior.
