### ISSUE TITLE
Request: add custom icons

### ISSUE THREAD

**Issue by heddendorp** [ionic-team/ionicons#434]
I'd love to have a way of adding my own icons which will behave like the standard ionicons _change depending on the platform_ if I supply multiple versions

**Comment by MatanYed** [comment]
+1 it's required feature

**Comment by chukwu** [comment]
There should be some kind of icon generator by copying your svgs into a folder and running
a command to generate the icons just like ionic resources generator.

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. This should be resolved in the latest version of Ionicons. You can use the `icon` property to provide either a path to an SVG or the exact SVG data: https://github.com/ionic-team/ionicons/blob/19629000ca1b6b23a96cc45642dc4ae7ccd89a0b/src/components/icon/icon.tsx#L62

However, we removed the platform specific functionality so there are no longer any iOS or MD icons.
