### ISSUE TITLE
Ionicons - Missing Save Icon 

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionicons#435]
_From @baltazaroliveira on October 4, 2016 15:9_

I am missing Save Icons in Ionicons. Please implement in a next release.

_Copied from original issue: driftyco/ionic#8480_

**Comment by ivanhuay** [comment]
+1

**Comment by Chris-Davies** [comment]
+1

**Comment by Rainson12** [comment]
+1

**Comment by LuisHCK** [comment]
+1

**Comment by alexnu** [comment]
+1

**Comment by bensperry** [comment]
There isn't really a save icon I feel comfortable with adding. The antiquated floppy disc design is old fashion and out of date now. Younger generations don't recognize it. 

I'm going to keep thinking on this as I update Ionicons to v4...

**Comment by sirhaplo** [comment]
All the office suites us the "antiquated floppy disk design". 
Maybe now, less softwares use the "save function" but when they use it, the floppy is indeed the right choice.
+1

**Comment by tavuntu** [comment]
+1, younger generations don't need to know the story of this icon, I mean, when you need to learn how to use an app, ones of the simplest things to learn would be "that wierd square" = "save my stuff", not a big deal. that's why tooltips or [https://i.stack.imgur.com/zL9rr.png](these) exist.

**Comment by henkverschoor1994** [comment]
I miss this icon too. Everyone knows what a floppy disk icon means, so it's not antiquated and out of date. Eventually you can add this as 'floppydisk' and not as save icon.

**Comment by sazedulhaque** [comment]
i miss this icon too. for now i am just using "md-disc" or "md-document" .
Thanks

**Comment by grisoliarodrigo** [comment]
+1

**Comment by Galinero** [comment]
+1
the main thing is adding an icon for pizza or nutrition but not for saving files...

**Comment by mobtex** [comment]
+1

**Comment by nonameolsson** [comment]
The floppy icon should definitely be added. It doesn't have to be called `save`. But it should absolutely exist in Ionicons. It should be up to a icon library to decide which icon to be used in a situation. That is up to the designer/developer. The icon library should only provide the icons.

**Comment by rstallings111** [comment]
I agree. Please add the floppy disk icon.

**Comment by AlvaroHerrero** [comment]
+1

**Comment by RafikSM** [comment]
+1

**Comment by cedricseyve** [comment]
+1 Will be using the "checkmark" instead for now.

**Comment by gmilani** [comment]
+1

**Comment by hiepxanh** [comment]
+1

**Comment by jsdussanc** [comment]
+1

**Comment by D3K0** [comment]
+1

**Comment by maxim25** [comment]
+1

**Comment by alaingoodarzi** [comment]
+1

**Comment by vikomall** [comment]
+1

**Comment by marca116** [comment]
The younger generation doesn't recognize the save icon? Give me a break. Of course they do, it's ubiquitous in most desktop software. They might not know what a floppy disk is, nor should they have to. The reason everyone knows what the save icon means is not because they know what a floppy disk is, that metaphor hasn't made sense for decades. No, the reason everyone knows what this icon means is because it's been the standard for so long. Now, because of misguided people like you, this standard might fade away. There won't be a unified save icon anymore and the users will be more confused than ever. Thanks for that.

**Comment by panpsonis** [comment]
+1

**Comment by eduSanfio** [comment]
+1

**Comment by arkabide** [comment]
+1

**Comment by de-mim-1974** [comment]
I do not agree with @bensperry to the younger generations do not recognize it. I agree with @bensperry that some applications get by without a save icon and that's a **good** and **contemporary** thing. This is not the question. 

Requirements must be implemented. I have a requirement from the requesters that a "building verification log" be saved only if this is explicitly requested by the user. In the UI, photos are to be added via an 'add' icon. In the same view, a save icon should be displayed. This different meaning about the icons 'add' and 'save' would be a big help to me now.

Try to 'Post' without a Post-Button ;)

**Comment by NickyTheWrench** [comment]
+1

**Comment by Kaz-** [comment]
+1

**Comment by mihaibalaban** [comment]
+1

**Comment by EugenWagner** [comment]
+1

**Comment by Rawnly** [comment]
+1

**Comment by GaboBrandX** [comment]
+1

**Comment by gonzalezfj** [comment]
+1

**Comment by GitStorageOne** [comment]
+1

**Comment by wvervuurt** [comment]
+1

I understand the sentiment of wanting to see a future with a new save icon that doesn't refer to old-fashioned physical objects that are no longer in use, personally. But it is the role of the application developers to decide on icons and make this move, not the role of the platform developers to enforce their wish on all developers using their platform. Add a floppydisk icon, and add an alternative, more future-proof icon that we can use for saving things, if you're so visionary. Then let us choose what we want to use. You can be sure we all have the interests of the user at heart. Leaving out the floppydisk without having a proper idea for an alternative is just silly.

**Comment by kensodemann** [comment]
Hello!

This was added to IonIcons v4 a while ago and will be available when ionIcons v4 is released. Here is the iOS version: https://github.com/ionic-team/ionicons/blob/4.0/src/svg/ios-save.svg

There is an MD version as well.

I am going to close and lock this issue since it will be included in the future version.

Thank you for using Ionic!!
