### ISSUE TITLE
ionicons v3.0.0 says it's version v3.0.0-alpha.3

### ISSUE THREAD

**Issue by mirkonasato** [ionic-team/ionicons#436]
See e.g. [unpkg.com/ionicons@3.0.0/dist/scss/ionicons-variables.scss](https://unpkg.com/ionicons@3.0.0/dist/scss/ionicons-variables.scss), and that `$ionicons-version` is also passed in the font urls in [scss/ionicons.scss](https://unpkg.com/ionicons@3.0.0/dist/scss/ionicons.scss).

Same for e.g. the comment at the start of [css/ionicons.css](https://unpkg.com/ionicons@3.0.0/dist/css/ionicons.css)

**Comment by yujiahuang** [comment]
+1
this breaks my webpack config :D

**Comment by sherdeadlock** [comment]
this makes webpack work
```js
    }, {
      test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?(-alpha\.[0-9])?$/,
      loader: 'url?limit=10000&minetype=application/font-woff'
    }, {
      // 3.0.0-alpha.3
      test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?(-alpha\.[0-9])?$/,
      loader: 'file'
    }, {

```

**Comment by maximegris** [comment]
You can also override ionicons variable before importing it like this

$ionicons-version: ""; 
@import "~ionicons/dist/scss/ionicons";

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. This should be resolved in the latest version of Ionicons.
