### ISSUE TITLE
Build Process Not Working

### ISSUE THREAD

**Issue by cliffmullis** [ionic-team/ionicons#444]
I am trying to extend the ionicons library for my project and am doing so based on the following:
http://www.omerwazir.com/custom-icons-with-ionicons

When I go through the build process the css is not building correctly. Here is what I am seeing for all icons:

.ion-alert-circled:before { content: ""; }

.ion-android-add:before { content: ""; }

Any idea why it is not building correctly or what might be going on?

**Comment by royipressburger** [comment]
Are you using the v3 branch?

**Comment by cliffmullis** [comment]
I was using the master branch. I was able to get the source to build correctly late last night after downgrading sass to version 3.3.14.

**Comment by royipressburger** [comment]
Nice. In any case if you are working with ionic 2 the right branch is v3

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. I am going to close as we no longer use this build process. Additionally, Ionicons uses SVG data instead of icon fonts.
