### ISSUE TITLE
is it possible to use cursor : pointer on an ionicon

### ISSUE THREAD

**Issue by Pau1fitz** [ionic-team/ionicons#445]
I am trying to use `cursor: pointer `on an ionicon but it only works for a split second.

[see jsfiddle here.](https://jsfiddle.net/f7to9ofp/)

My code looks like this 

HTML

`<i class="ionicons ion-android-bicycle"></i>`

CSS

```
.ionicons {
  cursor: pointer;
}
```

**Comment by heldertb** [comment]
use:
```
.ionicons:hover {
  cursor: pointer;
}
```

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. I am going to close as this is more of a support question. We use this tracker for bug reports and feature requests. However, I am no longer able to reproduce the behavior reported here so it is possible this issue has already been resolved.
