### ISSUE TITLE
Edit icon missing

### ISSUE THREAD

**Issue by pantonis** [ionic-team/ionicons#446]
As forms is one of the most used in mobile apps an Edit icon is a must.

**Comment by dominicdesu** [comment]
Seems like this was added once in 2013, why is it gone? See #39.

**Comment by brandyscarney** [comment]
The edit icon has been added in v4 named `create`: https://ionicons.com/

I am going to close this since I believe that is the solution, but please let me know if this is not what you're looking for and I'll reopen. Thanks!
