### ISSUE TITLE
Can't generate custom icon (generate.py)

### ISSUE THREAD

**Issue by louisdoe** [ionic-team/ionicons#452]
Hi

I am trying to add a custom icon to the Ionicons set.
I cloned ionicons directory.
Installed dependancices (`brew install fontforge ttfautohint`) I am on Ubuntu 16.04.
Generated an SVG icon with inkskape and iconmoon (www.boardlineapp.com/app/img/surfboard.svg).
Copied it in the `src` folder. 
And ran `$ python ./builder/generate.py`

I get this output:
```$ python ./builder/generate.py

Generate Fonts
Copyright (c) 2000-2012 by George Williams.
 Executable based on sources from 14:57 GMT 31-Jul-2012-ML.
 Library based on sources from 14:57 GMT 31-Jul-2012.
Load Manifest, Icons: 733
New Icon: 
 - surfboard
 - 0xf138
Traceback (most recent call last):
  File "/home/louisro/Documents/mobileApps/BoardLine/ionicons-master/builder/scripts/generate_font.py", line 152, in <module>
    subprocess.call(['sfnt2woff', fontfile + '.ttf'])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Generate SCSS
Generate CSS From SCSS
Generate Minified CSS From SCSS
Generate LESS
Generate Cheatsheet
Generate component.json
Generate composer.json
Generate bower.json
```

And I don't see the new icon in `css/ionicons.css`
Can you please help me ?

Thanks

**Comment by royipressburger** [comment]
Are you on 3.0 branch?

**Comment by louisdoe** [comment]
I don't know at all. I just downloaded the zip from github. Can you help me figure out ?

**Comment by royipressburger** [comment]
You need to clone the project and checkout to brach 3.0. Then follow these instructions:
https://github.com/driftyco/ionicons/blob/3.0/builder/readme.md
(you can skip step 6)
This should work

**Comment by louisdoe** [comment]
Hi @royipressburger , I just followed your steps, and I still get an error:

```
$ python ./builder/generate.py
Generate Fonts
Copyright (c) 2000-2012 by George Williams.
 Executable based on sources from 14:57 GMT 31-Jul-2012-ML.
 Library based on sources from 14:57 GMT 31-Jul-2012.
Load Manifest, Icons: 859
New Icon: 
 - surfboard
 - 0xf350
Generate TTF Font File
Generate SVG Font File
Traceback (most recent call last):
  File "/home/louisro/Documents/mobileApps/BoardLine/ionicons/builder/scripts/generate_font.py", line 183, in <module>
    subprocess.call(['sfnt2woff', fontfile + '.ttf'])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Generate Data Files
Generate SCSS
...
```

I added my new icon to the src/ directory, but should I also modify the manifest.json to add this icon to the set ?

Thanks for your help

**Comment by royipressburger** [comment]
You dont have to modify the manifast.json.. but in any case. Did you install woff2? Did you added it to your $PATH variable?

**Comment by louisdoe** [comment]
ok for the manifest.json.

Yes I installed woff2, woff2_compress  and  woff2_decompress are in my PATH.

**Comment by royipressburger** [comment]
Lets try to test the dependensies
type:
`fontforge --version`
`ttfautohint --version`
`sass --version`
`svgo --version`

**Comment by louisdoe** [comment]
Ok thanks for your help.
Let's go then:

$ fontforge --version
Copyright (c) 2000-2012 by George Williams.
 Executable based on sources from 14:57 GMT 31-Jul-2012-ML.
 Library based on sources from 14:57 GMT 31-Jul-2012.
fontforge 20120731
libfontforge 20120731-ML

$ ttfautohint --version
ttfautohint 0.97
Copyright (C) 2011-2013 Werner Lemberg <wl@gnu.org>.
License: FreeType License (FTL) or GNU GPLv2.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ sass --version
Sass 3.4.23 (Selective Steve)

$ svgo --version
0.7.1

Still this error:

$ python ./builder/generate.py
Generate Fonts
Copyright (c) 2000-2012 by George Williams.
 Executable based on sources from 14:57 GMT 31-Jul-2012-ML.
 Library based on sources from 14:57 GMT 31-Jul-2012.
Load Manifest, Icons: 860
removed from manifest: ios-surfboard
New Icon: 
 - surfboard
 - 0xf350
Generate TTF Font File
Generate SVG Font File
Traceback (most recent call last):
  File "/home/louisro/Documents/mobileApps/BoardLine/ionicons/builder/scripts/generate_font.py", line 183, in <module>
    subprocess.call(['sfnt2woff', fontfile + '.ttf'])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Generate Data Files
Generate SCSS
Generate CSS From ionicons
Generate CSS From ionicons-core
Generate SVG Files
Processing directory '/home/louisro/Documents/mobileApps/BoardLine/ionicons/builder/../src':

**Comment by royipressburger** [comment]
Im not really sure what is the problem. But I have newer versions.. maybe thats the problem:

```
fontforge --version
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 14:47 BST  3-Oct-2016-D.
 Based on source from git with hash: 
fontforge 14:47 BST  3-Oct-2016
libfontforge 20161003
```

```
ttfautohint --version
ttfautohint 1.5
Copyright (C) 2011-2016 Werner Lemberg <wl@gnu.org>.
License: FreeType License (FTL) or GNU GPLv2.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

by the way... You said you are running on linux no? so how did you install all the dependencies?

**Comment by louisdoe** [comment]
Hi

I updated to new versions

$ ttfautohint --version
ttfautohint 1.5

$ fontforge --version
libfontforge 20161013



but I still have the issue:

$ python ./builder/generate.py
Generate Fonts
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <
http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read
LICENSE.
 Based on sources from 01:51 UTC 13-Oct-2016-ML-D.
 Based on source from git with hash:
fe1d84b7d05178885a36ba0adce0559a82a493d5
Load Manifest, Icons: 860
removed from manifest: ios-surfboard
New Icon:
 - surfboard
 - 0xf350
Generate TTF Font File
Generate SVG Font File
Traceback (most recent call last):
  File
"/home/louisro/Documents/mobileApps/BoardLine/ionicons/builder/scripts/generate_font.py",
line 183, in <module>
    subprocess.call(['sfnt2woff', fontfile + '.ttf'])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Generate Data Files
^CTraceback (most recent call last):
  File "./builder/generate.py", line 430, in <module>
    main()
  File "./builder/generate.py", line 27, in main
    rename_svg_glyph_names(data)
  File "./builder/generate.py", line 153, in rename_svg_glyph_names
    svg_text = svg_text.replace(org_name, ion_name)

2017-01-14 22:43 GMT+01:00 Royi Pressburger <notifications@github.com>:

**Comment by royipressburger** [comment]
@louisdoe 
Amm Im not sure.
But I can see that the script actually fails [here](https://github.com/driftyco/ionicons/blob/3.0/builder/scripts/generate_font.py#L178)

So please try to comment the try block 
(Add `#` on lines 177 179 183)
and paste here the error you get

**Comment by louisdoe** [comment]
Hi Royi

ok I just did what you suggested and I get a new error:

$ python ./builder/generate.py
Generate Fonts
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <
http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read
LICENSE.
 Based on sources from 01:51 UTC 13-Oct-2016-ML-D.
 Based on source from git with hash:
fe1d84b7d05178885a36ba0adce0559a82a493d5
  File
"/home/louisro/Documents/mobileApps/BoardLine/ionicons/builder/scripts/generate_font.py",
line 178
    subprocess.Popen([scriptPath + '/sfnt2woff', fontfile + '.ttf'],
stdout=subprocess.PIPE)
    ^
IndentationError: unexpected indent
Generate Data Files
Generate SCSS
Generate CSS From ionicons
Generate CSS From ionicons-core
Generate SVG Files
Processing directory
'/home/louisro/Documents/mobileApps/BoardLine/ionicons/builder/../src':

ios-add-circle-outline.svg:
Done in 37 ms!
0.732 KiB - 55.9% = 0.323 KiB

ios-add-circle.svg:
Done in 6 ms!
0.52 KiB - 59% = 0.213 KiB

ios-add.svg:
...


and my new custom icon is not present in the .css.



2017-01-15 20:16 GMT+01:00 Royi Pressburger <notifications@github.com>:

**Comment by royipressburger** [comment]
@louisdoe python is sensitive to indentation.. please fix on line `178` (Because we comment the `try` you should take the like back, so it will be aligned with the other lines)

**Comment by louisdoe** [comment]
Ok I just did that and


2017-01-16 9:52 GMT+01:00 Royi Pressburger <notifications@github.com>:

**Comment by royipressburger** [comment]
And?

**Comment by louisdoe** [comment]
Sorry !

and I still have an error :

$ python ./builder/generate.py
Generate Fonts
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <
http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read
LICENSE.
 Based on sources from 01:51 UTC 13-Oct-2016-ML-D.
 Based on source from git with hash:
fe1d84b7d05178885a36ba0adce0559a82a493d5
Load Manifest, Icons: 860
removed from manifest: ios-surfboard
New Icon:
 - surfboard
 - 0xf350
Generate TTF Font File
Generate SVG Font File
Traceback (most recent call last):
  File
"/home/louisro/Documents/mobileApps/BoardLine/ionicons/builder/scripts/generate_font.py",
line 178, in <module>
    subprocess.Popen([scriptPath + '/sfnt2woff', fontfile + '.ttf'],
stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
Generate Data Files
Generate SCSS
Generate CSS From ionicons
Generate CSS From ionicons-core
Generate SVG Files
Processing directory
'/home/louisro/Documents/mobileApps/BoardLine/ionicons/builder/../src':

ios-add-circle-outline.svg:


2017-01-16 13:57 GMT+01:00 Royi Pressburger <notifications@github.com>:

**Comment by royipressburger** [comment]
Ok this is the last idea i have
https://people.mozilla.com/~jkew/woff/
Check this and make sure after install you have `sfnt2woff` In your `$PATH`

Please also return the script to his previous condition (without the comments we add)

**Comment by louisdoe** [comment]
Hi Royi

ok it works without error now ! Thanks.

But the custom icon I added (attached) renders as the instagram icon with
this code:

<i class="icon ion-surfboard"></i>

Any idea what's happening ?

Thanks

2017-01-16 16:32 GMT+01:00 Royi Pressburger <notifications@github.com>:

**Comment by royipressburger** [comment]
`<i class="icon ion-surfboard"></i>`

This is not the right way to use the icons
try this:
`<ion-icon name="surfboard"></ion-icon>`

**Comment by louisdoe** [comment]
I just tried your way, but no icon is displayed at all.
I am using ionic 1 and they mention the syntax I use in the docs :
https://ionicframework.com/docs/components/#item-input-inset

2017-01-17 15:03 GMT+01:00 Royi Pressburger <notifications@github.com>:

**Comment by royipressburger** [comment]
Huu ok.. i didnt know you use ionic 1
The build process generate an html file that you can see all the icons in it.. can you check that you can your item?

By the way im not sure that ionicons branch 3 is compatible with ionic 1. You might need to checkout to master and build again
