### ISSUE TITLE
Build script doesn't read unicode files correctly

### ISSUE THREAD

**Issue by ncr-moda** [ionic-team/ionicons#453]
The build script fails if the ttf description contains unicode characters such as for the user name:

`python builder/generate.py
Generate Fonts
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 19:51 PST  3-Jan-2017-D.
 Based on source from git with hash:
Load Manifest, Icons: 733
New Icon:
 - mjb-sun
 - 0xf138
Save Manifest, Icons: 734
Save Build, Icons: 734
Traceback (most recent call last):
  File "builder/generate.py", line 318, in <module>
    main()
  File "builder/generate.py", line 19, in main
    rename_svg_glyph_names(data)
  File "builder/generate.py", line 45, in rename_svg_glyph_names
    svg_text = svg_text.replace(org_name, ion_name)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 383: ordinal not in range(128)
`

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. I am going to close as we no longer use this build process. Additionally, Ionicons uses SVG data instead of icon fonts.
