### ISSUE TITLE
some ionic icons are not displayed on iOS 9.3.2, but works on iOS 10 (tested on 10.0.2).

### ISSUE THREAD

**Issue by ghost** [ionic-team/ionicons#457]
Hello,
I'm developing cross-platform photogram app using ionic 2(rc4).
But I faced the following issues, some ionic icons are not displayed, or doesn't work on iOS 9, but works properly on iOS 10 or Web browser (Google chrome or Safari).
Please check the icons on the bellow screenshots.

**1. iPhone 5+ with iOS 9.3.2 (Error)**
![img_0092](https://cloud.githubusercontent.com/assets/22894033/22010456/4e1717ae-dcc4-11e6-9025-f936da07e786.PNG)

**2. iPhone 6+ with iOS 10.0.2 (Works fine)**
![img_5823](https://cloud.githubusercontent.com/assets/22894033/22010459/5016cc20-dcc4-11e6-80b6-de2a9e2ccd3c.PNG)

**3. Web browser( Google Chrome 55.0.x) (Works fine)**
![capture](https://cloud.githubusercontent.com/assets/22894033/22010581/1ee98740-dcc5-11e6-8482-7c02e14fee1f.PNG)

```
# Dev Environment
- ionic cli: 2.1.18
- node.js: 6.9.2
- npm:  3.10.9
- cordova: 6.4.0
- OS: OS X EI Capitan 10.11.6, Windows 10 x64

```

Thanks.

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. I am going to close as this should be resolved in the latest version of Ionicons. In particular, we switched from fonts to using SVG data.
