### ISSUE TITLE
No icon for Houzz?

### ISSUE THREAD

**Issue by flaxton** [ionic-team/ionicons#462]
Houzz is a large social media site used by home designers and contractors, for example Kitchen and Bath projects.

Font Awesome has an icon for it, called: houzz

Ionicons needs to add it.

Their website is just houzz.com

Thanks!

Fred

**Comment by bensperry** [comment]
Will add to v4 release!

**Comment by brandyscarney** [comment]
Closing as a duplicate of #423. Please track this issue there, thanks!
