### ISSUE TITLE
ionicons not shown on first page load?

### ISSUE THREAD

**Issue by denniscohn** [ionic-team/ionicons#466]
Hi,

we've got soms weird issue with IE11 and ionicons.
When we visit our website, all the icons doesn't shown on the first page load. If you go to an other page, then we icons are working correctly.
We're running varnish, tried a lot of things, but no succes yet.

Anyone know if this is a bug?

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. I am going to close as there is not enough information for us to verify this bug. If this is still a problem with the latest version of Ionicons, please reply to this thread with a GitHub repo that we can use to verify the reported behavior.
