### ISSUE TITLE
FR: New icons (expand, collapse, pin) for v3 / ionic2

### ISSUE THREAD

**Issue by mburger81** [ionic-team/ionicons#467]
Your icons v3 for ionic2 looks great!
But I think there are missing some icons, what do you think about to include icons for collapse, expand and pin like this in the screenshots?

the expand one is only your "code" icon rotate per 90°

![image](https://cloud.githubusercontent.com/assets/3778892/23255757/0bda27d0-f9bd-11e6-9744-82683bc793c9.png)

![image](https://cloud.githubusercontent.com/assets/3778892/23255770/19c22b36-f9bd-11e6-8ef7-64a5715b7a9a.png)

**Comment by bensperry** [comment]
Good idea! Will make sure this is added to the v4 release. Stay tuned.

**Comment by amandaejohnston** [comment]
Looks like these have all since been added under `chevron-collapse`, `chevron-expand`, and `pin` respectively. Closing this out. Thank you!
