### ISSUE TITLE
ion-ios-telephone and ion-ios-telephone-outline are cropped/cut off at larger sizes in certain browsers

### ISSUE THREAD

**Issue by kimflournoy** [ionic-team/ionicons#468]
You can see an example of this on http://ionicons.com/cheatsheet.html - these two icons at 64 and 96 are getting cut off on the right side. This happens in Chrome and Firefox - looks ok in Safari and Edge. Screenshot below is from Chrome for Mac 56.0.2924:

![screen shot 2017-02-24 at 4 23 47 pm](https://cloud.githubusercontent.com/assets/94914/23325889/a991ac6e-faad-11e6-9e8c-8dd2319a6d6f.png)

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. I am going to close as there is not enough information for us to verify this bug. If this is still a problem with the latest version of Ionicons, please reply to this thread with a GitHub repo that we can use to verify the reported behavior.

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. I am going to close as this appears to be resolved in the latest version of Ionicons.
