### ISSUE TITLE
ion-eye-disabled not working

### ISSUE THREAD

**Issue by ataraxus** [ionic-team/ionicons#472]
Hey, 

the websites states that `ion-eye-disabled` is the valid identifier for this particular icon but it is actually `ion-eye-off` i don't know which one it should be, but its technically the second one.

**Comment by timhaak** [comment]
Hit the same problem as @ataraxus.

Should be ion-eye-off in the documentation

**Comment by timhaak** [comment]
Looking a bit further 

It's correct here http://ionicframework.com/docs/ionicons/

and incorrect here http://ionicons.com/

**Comment by bensperry** [comment]
Yea, sorry for the confusion. We're going to be cleaning up and fixing this soon. Thanks!

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. This should be resolved in the latest version of Ionicons.
