### ISSUE TITLE
v3.0.0 (latest on npm) is missing some icons in v2.0.1 (latest on github)

### ISSUE THREAD

**Issue by justiceo** [ionic-team/ionicons#476]
Some of them include

- ion-social-usd
- ion-android-done
- ion-chatbubble
- ion-chatbubbles

Also can't switch from v3.0.0 to v2.0.1 because "ionic-angular" imports the icon scss in v3

**Comment by AlexanderMisel** [comment]
I found this too, chatbubble is a very useful icon. And v4.00 missing many outline icons.

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. This should be resolved in the latest version of Ionicons.
