### ISSUE TITLE
Hello, everyone,, I want to fix ionicons problem...

### ISSUE THREAD

**Issue by jamnetkr** [ionic-team/ionicons#480]
My name is Cy Jung. You can call me Cy^^ Hi,,

![ex](https://cloud.githubusercontent.com/assets/24488838/24827185/d8345c16-1c80-11e7-851f-b9e78ba7ee1d.jpg)

Can you see bottom image? I am not 'engineer' but I try to make community website by Wordpress system. And My theme(I bought^^) can use 'ionicons'... However, I try to setup 5 'Social Links Menu' but not exact work... I mean some icon show correct image but some icon is not. 

Anyone can give me advice or teaching me??? I hope so, someone will response to me^^
Thank you for read my word & get a really great Weekend.

from Cy.

**Comment by Deckluhm** [comment]
Can you please show us some code?

**Comment by jamnetkr** [comment]
Hello^^ Arm...^^ Actually I don't know about code^^ But...

![test](https://cloud.githubusercontent.com/assets/24488838/25369886/094af898-29c2-11e7-855f-04a9f70d581d.jpg)

I used ionicons like top image. Which method from my theme information that mean my theme support ionicons^^ I think^^

However, ionicons not exact working...
How can I fix? Could you give me some information?

Thank you very much your response.

**Comment by Deckluhm** [comment]
This is not an Ionicons issue and you don't give us enough information to help you (theme you are using, Ionicons version used).

Please ask the theme creator for help / support.

**Comment by lonalovegood1** [comment]
Please try this class >> ion ion-plus-circled
I think the problem is that you firgit to put (ion) class first
