### ISSUE TITLE
Icon 'android-book' available in png but not in svg

### ISSUE THREAD

**Issue by capitola-dev** [ionic-team/ionicons#485]
The icon [android-book](https://github.com/driftyco/ionicons/blob/master/png/512/android-book.png) is available in png, but not in svg.

Should be at `https://github.com/driftyco/ionicons/blob/master/src/android-book.svg` but is not.
No reference to it on the css neither.

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. This should be resolved in the latest version of Ionicons.
