### ISSUE TITLE
Please add a hourglass icon

### ISSUE THREAD

**Issue by modvd** [ionic-team/ionicons#486]
Could you please add a hourglass icon ?

**Comment by Loxos** [comment]
This issue was already brought up in 2016 ( #265 ). Back then an hourglass icon was announced vor Ionic v3. Unfortunately it's still not included in v3.1.0

**Comment by bensperry** [comment]
Ahh, yes. It was created but did not get added. Sorry about that. It will be included in v4, stay tuned.

**Comment by shyamal890** [comment]
+1

**Comment by bensperry** [comment]
This is live in [v4 ionicons](https://ionicons.com/). 🎉
