### ISSUE TITLE
Use in Android devices

### ISSUE THREAD

**Issue by MahdiPishguy** [ionic-team/ionicons#487]
how can i use this fonts on Android applications?

**Comment by kendrikat** [comment]
https://github.com/mikepenz/Android-Iconics#1-provide-the-gradle-dependency

**Comment by mhartington** [comment]
@MahdiPishguy Hi there! So I think @kendrikat link will be the correct way to include ionicons into your native android app. If you're using Ionic, they're already included when you build. Cheers!
