### ISSUE TITLE
Update ionicons 2.0 to 3.0 on ionicons.com to stop confusion 

### ISSUE THREAD

**Issue by SimonFricker** [ionic-team/ionicons#488]

**Comment by CrazyPython** [comment]
@Fuiste As a designer, the lack of SVGs makes it really difficult to make mockups using ionicons.

**Comment by CrazyPython** [comment]
ion-chatboxes isn't in the `src/` folder.

**Comment by SimonFricker** [comment]
The lack of copyable glyphs for icon icons 3.0 is annoying for designers. Please create something like this, ionicons.com/cheatsheet.html, for ion icons 3.0

**Comment by jiyinyiyong** [comment]
Any...... updates?

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. Ionicons now uses SVG data instead of icon fonts, so this issue should be resolved. If you are running into any other problems please create a new issue. Thanks!
