### ISSUE TITLE
npm and yarn DO NOT install ion-android* icons (bower works just fine!)

### ISSUE THREAD

**Issue by zooduck** [ionic-team/ionicons#492]
Both npm and yarn do not install the ion-android icons (bower works just fine, but its deprecated so we shouldn't be using it anymore).

I had to download the zipped folder from ionicons.com in the end and use that instead.

**Comment by janpio** [comment]
And what version are you talking about? Post your `ionic info` please.

**Comment by zooduck** [comment]
You are right, this has to do with versioning. Bower installs an earlier version (~2.0.1), which matches the current documentation at ionicons.com.

Since both npm and yarn install ^3.0.0. by default, it would make sense for ionicons.com to forward to the latest docs at https://ionicframework.com/docs/ionicons/ or at the very least make it clear that the current page contains an out-of-date set of icons.

Surely old versions should be archived and linked, not the default?

**Comment by janpio** [comment]
I ask you again:
And what version are you talking about?
Post your `ionic info` please.

You talking about Bower makes me think you are not even using the version of Ionic this repository is about.

**Comment by zooduck** [comment]
I did mention the specific versions in my last comment, but I will list the DEFAULT versions that get installed for each package manager:

bower install ionicons: v2.0.1
npm install ionicons:    v3.0.0
yarn add ionicons:       v3.0.0

It's particularly confusing because http://ionicons.com shows the outdated set of icons that you get only with the deprecated bower!

Anyone who installs ionicons using npm or yarn will naturally head over to http://ionicons.com and be presented with an outdated set of icons totally incompatible with their version of ionicons!

Sorry if I did not explain very well before, but hopefully it will make sense to you now.

My suggestion is that http://ionicons.com is updated to show the latest set by default, with links to archived versions (which is pretty much standard practice for all libraries/frameworks).

**Comment by janpio** [comment]
You actually did everything all right - I misread the repo name as "ionic"... Sorry.

You are correct, ionicons.com could use some work and love.

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. This should be resolved on the latest version of Ionicons. Additionally, we do have plans to update the Ionicons website to make the usage clearer.

**Comment by janpio** [comment]
Sometimes it pays to keep an issue open for 5+ years I see 😆
