### ISSUE TITLE
ionicons link not using https

### ISSUE THREAD

**Issue by tecmie** [ionic-team/ionicons#510]
I noticed the CDN Link on ionicons is using an http link instead, and this makes using the link not to work on github pages

**Comment by nicknish** [comment]
Hey @tecmie! Which CDN link are you referring to? I think most CDNs serve their assets under `https`, in addition to `http`. So in the case of the Github Pages users, it's possible that they can still use the CDN if they change the protocol to `https`.

**Comment by tecmie** [comment]
Yeah, thanks a lot, i figured that out

**Comment by tecmie** [comment]
Yeah, thanks a lot, i figured that out
