### ISSUE TITLE
CDN link doesn't work properly

### ISSUE THREAD

**Issue by DenisLapi** [ionic-team/ionicons#513]
I want to use ionicons using CDN link for my web project. When I include the link I'm getting this message in console

`Access to Font at 'https://code.ionicframework.com/ionicons/2.0.1/fonts/ionicons.woff?v=2.0.1' from origin 'https://s.codepen.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://s.codepen.io' is therefore not allowed access. The response had HTTP status code 403.` 

This is my code:

`<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">`

Can somebody help me to fix this issue? I found the CDN link on this website - http://ionicons.com/

**Comment by praisedpk** [comment]
That might be a temporary bug. I can see the relevant header in Dev Tools on Firefox. Also I am using the hosted library on my site without any issue.

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. This should be resolved in the latest version of Ionicons (we use SVG data now instead of icon fonts).
