### ISSUE TITLE
How to use v4 version ? 

### ISSUE THREAD

**Issue by sinsunsan** [ionic-team/ionicons#514]
I am having trouble to understand how to use v4 version of the icons

I have added 
` <script src="https://cdnjs.cloudflare.com/ajax/libs/ionicons/4.0.0-6/collection/icon/icon.js"></script>
`
in my index.html but i I use the class name only it does not seem  to work. 

Any doc ? Idea ? 
Also you speak about v3 and v4 version but v4 is the only one to have tags in github so I supposed v3 is not a real version ?

**Comment by pwespi** [comment]
See https://github.com/ionic-team/ionicons/issues/499.

**Comment by sinsunsan** [comment]
Thanks
