### ISSUE TITLE
Ionicon React Component 

### ISSUE THREAD

**Issue by estebanborai** [ionic-team/ionicons#520]
I would like to use ionicons as components for React.js as the use of Bootstrap Glyphicons.
Im thinking about a complete library to install and create icons components the following way:

`<Ionicon icon="ion-ionic" />`

The **Ionicon** component could be very simple as we just create a component that receive icon prop and apply that icon.

**Comment by philals** [comment]
To save a search: https://zamarrowski.github.io/react-ionicons/
