### ISSUE TITLE
ionicons v4 wrong icon for ios-apps

### ISSUE THREAD

**Issue by brynne8** [ionic-team/ionicons#523]
version: v4.0.0-13
issue: ios-apps (\f10a) looks like logo-buffer (\f22d)

**Comment by askilondz** [comment]
I'm noticing this as well when trying to use `arrow-dropleft-circle` it's giving me `boat` instead on iOS which is actually kind of humorous in the app.

**Comment by baotoan1905** [comment]
same issue

**Comment by danielgregorywilson** [comment]
And arrow-dropright-circle gives bonfire…

**Comment by paulnagle** [comment]
Me too... My ios app displays bonfire instead of arrow-dropright-circle

**Comment by DavidePassafaro** [comment]
Same issue with v4.5.10-0
