### ISSUE TITLE
Ionic Framework 404 svg icons 

### ISSUE THREAD

**Issue by danielehrhardt** [ionic-team/ionicons#546]
![image](https://user-images.githubusercontent.com/19570043/40270230-88c1233c-5b89-11e8-9b6e-e7c5eebfc470.png)
Is it related to https://github.com/ionic-team/starters/commit/9071f27d16c1b32a5eb61d37caa454a20d2c474f ?

**Comment by danielehrhardt** [comment]
I installed ionicons and added this to my angular.json file

```

"assets": [
              {
                "glob": "**/*.svg",
                "input": "node_modules/ionicons/dist/ionicons/svg",
                "output": "./svg"
              }
            ],
```

**Comment by AKosmachyov** [comment]
Another solution

1) Update assets array in `angular.json`
2) Update the scripts in the package.json. [Angular CLI docs/serve ](https://angular.io/cli/serve)
```json
 "scripts": {
        "start": "ng serve app --open",
        "build": "ng build app",
    },
```
3) Clear cache in the browser
4) Run the app using `npm start`

**Comment by amandaejohnston** [comment]
Thank you for the issue. I'm unable to replicate this with the latest version of Ionic after creating a fresh starter app, so I'm assuming this has already been resolved. If you're still running into this, please create a new issue with a link to a minimal reproduction app.
