### ISSUE TITLE
Discord Icon

### ISSUE THREAD

**Issue by Simon-Laux** [ionic-team/ionicons#556]
Here is more information on their logo: https://discordapp.com/branding

**Comment by AdamKernig** [comment]
Yep also vote up, its a massive gaming community surprised this hasn't been covered, font awesome does it.

**Comment by smolstiel** [comment]
Bumping this, since I signed up to GitHub just to see if this icon was in the works yet 👍

**Comment by D3Portillo** [comment]
We want this!

**Comment by ram33z** [comment]
ya please add this one !!!

**Comment by Iwitrag** [comment]
bump

**Comment by DeeperAuto235** [comment]
bump

**Comment by ZakShearman** [comment]
Really looking for this.

**Comment by PabloC** [comment]
bump!

**Comment by cahya1992** [comment]
bump!

**Comment by studio315b** [comment]
Discord icon is in 5.2.3 as `logo-discord`

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. The Discord logo is available in the latest version of Ionicons.
