### ISSUE TITLE
ionicons - ion-android-share icon

### ISSUE THREAD

**Issue by vijeth-ag** [ionic-team/ionicons#558]
Hello,

Im trying to use **ion-android-share** icon from the url [ https://ionicons.com/v1/](url)

but in the app and the codepen the icon looks different.
codepen url below:
https://codepen.io/vijeth-ag/pen/eKpKGG?editors=1010

expecting to see as in the below screenshot from https://ionicons.com/v1/.

<img width="322" alt="screen shot 2018-06-02 at 5 12 53 pm" src="https://user-images.githubusercontent.com/34409546/40874096-a0f823b0-6688-11e8-8161-8605d59a10ab.png">

Please help. Thanks

**Comment by Maistho** [comment]
Well, you are not using v1 of ionicons, you are using some other version included in the nightly.

Here is a fixed version that has the correct icons loaded in the codepen settings
https://codepen.io/Maistho/pen/KBwZOr

**Comment by vijeth-ag** [comment]
Thanks for the help. Ill close the issue.
