### ISSUE TITLE
No folder available for v4 ttf download

### ISSUE THREAD

**Issue by CybageSaloni** [ionic-team/ionicons#561]
Hi,
Can we have similar folder available to download icons for v4 like we've for v1 & v2 ?
I can easily observe that lot of icons aren't available in v4 which were there in v2. Also, style available for v4 is Regular. Can we have v4 Medium like we have for v2?

Thanks.

**Comment by AlexanderMisel** [comment]
you can download from npm

**Comment by CybageSaloni** [comment]
@AlexanderMisel : How do we get/download ttf file from npm ?

Thanks

**Comment by AlexanderMisel** [comment]
Create an empty folder and run 
`npm install ionicons@4.1.2`
and you will see fonts folder in node_modules/ionicons/dist/fonts
