### ISSUE TITLE
Duplication of Icons after usage of Jquery

### ISSUE THREAD

**Issue by Helagon** [ionic-team/ionicons#562]
Hi Ionicon Team
My Issue with your fontpack is that, when I generate lables with your Ionicon, the icons duplicate themself. 

I just updated to the new version. Before I used the new Version it worked perfectly.

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. I am going to close as there is not enough information for us to verify this bug. If this is still a problem with the latest version of Ionicons, please reply to this thread with a GitHub repo that we can use to verify the reported behavior.
