### ISSUE TITLE
v4 Possible memory leak with using IntersectionObserver polyfill

### ISSUE THREAD

**Issue by sbannigan** [ionic-team/ionicons#563]
I'm not sure if this really requires a fix, but I ran into a pretty significant memory leak when using `ion-icon` inside a virtual scroll component. I was also using the [IntersectionObserver polyfill](https://github.com/w3c/IntersectionObserver/tree/master/polyfill) for support on Safari. When testing on device, if I scrolled really fast it seems like the ion-icon component would load, but the intersection observer callback wouldn't fire before it was destroyed again. From my understanding, the native implementation of InteractionObserver handles disconnecting from an element automatically if it is destroyed, but this was not happening with the polyfill. As a result, after scrolling up and down through my virtual scroll collection, the app became increasingly unresponsive and laggy to an unacceptable level. I removed the polyfill and everything functioned as expected. As I said, not really a bug in the ion-icon component, but may be worth disconnecting from the observer on componentDidUnload as a fallback **OR** recommending in the docs that the polyfill _not_ be used.

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. According to https://github.com/ionic-team/ionic-framework/issues/14600#issuecomment-445577141 this issue should be resolved. I am going to close this, but let me know if you are still running into issues on the latest version of Ionicons.
