### ISSUE TITLE
Access to Font blocked by CORS

### ISSUE THREAD

**Issue by kamel1239** [ionic-team/ionicons#570]
Hi guys, so all of sudden the ionicons in my web page not showing up, it says this : 

`Access to Font at 'https://code.ionicframework.com/ionicons/2.0.1/fonts/ionicons.ttf?v=2.0.1' from origin 'https://mywebpage.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://mywebpage.com' is therefore not allowed access. The response had HTTP status code 403.`

I did a small google search and I found that it might be a bug or something, so I want to check if there's anything I can fix? or I should just wait?

NB: it was working really fine like minutes ago.
Thanks very muh for your time.

**Comment by viapek** [comment]
I am getting the same problem on a single, non-unique (as far as I can tell from chrome version numbers) computers.

I am serving all from firebase and all going to the same firebaseapp.com address. The error even reports redirected from and origin to be the same domain and then that it is a CORS error :/

![Error-masked](https://user-images.githubusercontent.com/13717661/63860219-b1d81b80-c9e3-11e9-9a5d-9518a320d354.jpg)

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. This should no longer be an issue in the latest version of Ionicons as we now use SVG data instead of icon fonts.
