### ISSUE TITLE
Npm icon doesn't inherit color

### ISSUE THREAD

**Issue by lesha1201** [ionic-team/ionicons#576]
Npm icon always has a black color.
![image](https://user-images.githubusercontent.com/10157660/42456381-5f0940e2-839d-11e8-9b4b-8d3d9cef5713.png)
For some reason its SVG has <style>.st0{fill:#010101}</style> and paths have classname .st0. I think it should be removed.

    <svg id="Layer_1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"> 
      <style>.st0{fill:#010101}</style>
      <path class="st0" d="M227.6 213.1H256v57.1h-28.4z"></path>
      <path class="st0" d="M0 156v171.4h142.2V356H256v-28.6h256V156H0zm142.2 142.9h-28.4v-85.7H85.3v85.7H28.4V184.6h113.8v114.3zm142.2 0h-56.9v28.6h-56.9V184.6h113.8v114.3zm199.2 0h-28.4v-85.7h-28.4v85.7h-28.4v-85.7H370v85.7h-56.9V184.6h170.7v114.3z"></path>
    </svg>

P.S. I can fix it.

**Comment by peterennis** [comment]
@bensperry 
I can confirm this.
Building an icon display component.
Ref: https://aesvg.adaept.com
Ref: https://github.com/peterennis/ae-svg-components
SVG in journal is not ionic 4 friendly (path.st0 ?)
![capture357](https://user-images.githubusercontent.com/140737/43363418-4489e08e-92b9-11e8-809b-0192ab615982.png)
![capture358](https://user-images.githubusercontent.com/140737/43363420-48cc4718-92b9-11e8-8777-f53182014c24.png)
SVG in npm is not ionic 4 friendly (path.st0 ?)
![capture359](https://user-images.githubusercontent.com/140737/43363438-c25a2852-92b9-11e8-82fc-1d64f7a93866.png)

**Comment by bensperry** [comment]
Very strange! Might need to pull in @kevinports or @adamdbradley for this one. We do some svg magnification before publishing these, so perhaps something got messed up?

**Comment by danielehrhardt** [comment]
![image](https://user-images.githubusercontent.com/19570043/44099819-c3bbbb34-9fe3-11e8-8548-0a731de58735.png)

https://raw.githubusercontent.com/ionic-team/ionicons/master/src/svg/md-image.svg
https://raw.githubusercontent.com/ionic-team/ionicons/master/src/svg/md-journal.svg

**Comment by danielehrhardt** [comment]
https://github.com/ionic-team/ionicons/pull/594

**Comment by danielehrhardt** [comment]
Nothing new here?

**Comment by gezquinndesign** [comment]
Would like to know when this is fixed...

**Comment by redwolf2** [comment]
I can see, that these icons are affected:

logo-bitbucket.svg
logo-npm.svg
md-heart-half.svg
md-gift.svg
md-heart-empty.svg
