### ISSUE TITLE
Documentation and Icon index for v2 and v3

### ISSUE THREAD

**Issue by ackvf** [ionic-team/ionicons#581]
I don't like the graphical changes introduced between versions 2 and 4. Is it possible to access the Icon index for other version than latest?

v2
![image](https://user-images.githubusercontent.com/2313018/42813760-529c4e32-89c2-11e8-804a-cc434c930d82.png)

v4
![image](https://user-images.githubusercontent.com/2313018/42813783-622d06c0-89c2-11e8-9824-cf5497fa0ab1.png)

**Comment by brandyscarney** [comment]
Thanks for the issue! You can still access older versions of Ionicons in the [documentation](https://ionic.io/ionicons). Here is a link to the v2 icons: https://ionic.io/ionicons/v2
