### ISSUE TITLE
md-eye and md-eye-off icons are misaligned

### ISSUE THREAD

**Issue by tomastrejdl** [ionic-team/ionicons#582]
When using md-eye as a switch and changing to md-eye-off the icon jumps up a few pixel because the svgs are misaligned. Switching ios-eye and ion-eye-off works fine.

**Comment by amandaejohnston** [comment]
Looks like this has since been resolved, likely as part of moving away from the `md-`/`ios-` pattern. If you're still running into this, please open a new issue and include a minimal reproduction. Thank you!
