### ISSUE TITLE
compass is showing when specifying square-outline in IOS

### ISSUE THREAD

**Issue by SteveKennedy** [ionic-team/ionicons#585]
I am using v4.2.5

Seems like when I specifiy 

`<ion-icon name="square-outline"></ion-icon>`

it generates:

`<ion-icon item-right="" role="img" class="icon icon-ios item-icon ion-ios-square-outline" aria-label="square outline" ng-reflect-name="square-outline"></ion-icon>`

but it renders a **compass** for iOS devices.

![image](https://user-images.githubusercontent.com/12101125/43117812-6a195eb2-8ed4-11e8-8352-a0a045658138.png)

**Comment by erickbrenesLT** [comment]
I have the same issue in 4.4.3.  I believe the workaround might be to hardcode it with CSS.
