### ISSUE TITLE
Error with Save icon

### ISSUE THREAD

**Issue by edu526** [ionic-team/ionicons#592]
Hi.

I have a error with Save icon
<ion-icon name="save" text-right color="light"></ion-icon>

This show a key icon

### V 4.3.0
<a href="https://ibb.co/bzB41U"><img src="https://preview.ibb.co/nv3v89/Screenshot_6.png" alt="Screenshot_6" border="0"></a>
<a href="https://imgbb.com/"><img src="https://image.ibb.co/cVE2o9/Screenshot_7.png" alt="Screenshot_7" border="0"></a>

Thanks.

**Comment by eduardorossi** [comment]
Hi, I'm with the same error mentioned above, but the version I'm using is 4.4.4

Team Ionic, could you fix this error?

**Comment by dantelent** [comment]
In v4.4.7 the Save icon is a leaf

**Comment by jacargentina** [comment]
Any news on this? Same problem here, having a key when i need a disk for saving!

**Comment by fortuneNext** [comment]
Yeah, this is pretty annoying.... Leaf instead of disk.

**Comment by 3xpedia** [comment]
Same issue here.
Quit annoying :/

**Comment by TomDoesbRUG** [comment]
This is still an issue in v4.6 ...

**Comment by amandaejohnston** [comment]
Looks like this has been resolved in the time since it was posted; icons are all displaying correctly when tested on my end using the latest version of Ionicons. If you're still running into this, please create a new issue and include a minimal reproduction. Thank you!
