### ISSUE TITLE
4.3.0: Business is jet outline

### ISSUE THREAD

**Issue by speedfl** [ionic-team/ionicons#593]
Hello All,

After installing v4.3.0 I found that business is a jet:

```
<ion-icon class="aprimary icon icon-md ion-md-business item-icon" item-start="" name="business" role="img" aria-label="business" ng-reflect-name="business"></ion-icon>
```

In fact it render:

```
<ion-icon name="ios-jet-outline"></ion-icon>
```

By the way if I use: ios-jet-outline nothing appears

Regards

Geoffrey MUSELLI

**Comment by speedfl** [comment]
Same in 4.2.6

**Comment by Theud** [comment]
+1

Same problem with :
`<ion-icon name="information-circle-outline"></ion-icon>`

**Comment by znegva** [comment]
same here, `logo-game-controller-a` renders ios-cafe-outline  
same here, `logo-game-controller-b` renders ios-funnel-outline  

using ionicons v4.4.3

**Comment by speedfl** [comment]
Issues still there in 4.4.2

**Comment by MtheCastro** [comment]
+1

**Comment by darwev0** [comment]
Same.
Also, ios-business seems to be a robot
