### ISSUE TITLE
Are Ionicons custom tags (via web component) actually compatible with IE11?

### ISSUE THREAD

**Issue by mattez** [ionic-team/ionicons#606]
(I know .. IE11 .. omg...)

They should seen [Announcing Ionicons v4!](https://blog.ionicframework.com/announcing-ionicons-v4/) Almost at the end is written:

> Please test it out for yourself on IE11 and above.

Some major issues in IE11:

**Issue 1:** Ionicons are completely missing in some cases:

When I use another inline SVG with `<style>` tag on a page where Ionicons are used Ionicon WebComponent doesn't work in Internet Explorer 11. When I remove `<style>` tag It works again.

See **not working example with** `<style>` tag in IE11 here:
debug mode: https://s.codepen.io/mattez/debug/oPwgoz/NQMzYqKKZRBk
(editor view: https://codepen.io/mattez/pen/oPwgoz)

See **working example without** `<style>` tag in IE11 here:
debug mode: https://s.codepen.io/mattez/debug/eLRZKv/YvAgOnwwmDdA
(editor view: https://codepen.io/mattez/pen/eLRZKv)

**Issue 2:** Ionicons are oversized:

After fixing issue #1 Ionicons emerge but: Custom tag missing some inline CSS so it is in default size.

I have nothing left other than to use the font for now.

**Comment by hades200082** [comment]
Same issue here - icons don't show up in IE11 on Win10 Pro

**Comment by amandaejohnston** [comment]
Thank you for the issue! As of the current version, Ionicons does not support IE11. We have an internal ticket to add an official browser support table to the site. In the meantime, I'm going to go ahead and close this out.
