### ISSUE TITLE
Add Gitlab Icon

### ISSUE THREAD

**Issue by cole-rogers** [ionic-team/ionicons#613]
Would be useful to go with the github icon, for us people who also use gitlab for some reason.

**Comment by LianyanGu** [comment]
Do you mean gitlab logo? I can work on that if its not done yet

**Comment by retiform** [comment]
Yes @LianyanGu I do.

**Comment by mikeanth-dev** [comment]
any updates on this?

**Comment by amandaejohnston** [comment]
This has since been added as `logo-gitlab`. Thank you!
