### ISSUE TITLE
Firefox does not load your icons

### ISSUE THREAD

**Issue by ConsoleTVs** [ionic-team/ionicons#615]
Just letting you know ^^

![image](https://user-images.githubusercontent.com/6124435/46205375-a63a2b80-c320-11e8-934f-37065ed4e7b6.png)

**Comment by gaggle** [comment]
Yep, not working in Firefox here either.

**Comment by ebinion** [comment]
Confirmed. I just ran into the same thing.

**Comment by NiklasMerz** [comment]
I can confirm this. The ionicons website does not work in firefox. It worked a few days ago...

Error: `TypeError: e is undefined 9jntnwf0.es5.entry.js:2:14954 `

**Comment by perrygovier** [comment]
Fixed in https://github.com/ionic-team/ionicons/commit/4c07e02372c9b8e14c9a36aef2d6f780097e0a2a
(not live yet)
