### ISSUE TITLE
Use ionicons as web-components in doc site

### ISSUE THREAD

**Issue by juanmiguelbesada** [ionic-team/ionicons#626]
Hi guys.

I'm a bit confused. I was watching the ionicons website https://ionicons.com/ and you promote to use web-components (and I really do agree).

But, checking the website I realize that you are not using the ion-icon webcomponent.
https://github.com/ionic-team/ionicons/blob/f3e720c1292563c366ee4bda069c9ae7a6c65347/src/docs/site/components/icon-list/icon-list.tsx#L169

Is it in purpose or do you missed it?

Anyway I think is not cool that you dont practise what you preach.

Glad to send a PR if you want.

**Comment by peterennis** [comment]
@juanmiguelbesada 
Ionicons are used in ionic core.
I understand the design allows for backwards compatibility with other ionic versions.
Here is a test example extending them as a component: https://aesvg.adaept.com/
Code: https://github.com/peterennis/ae-svg-components/tree/master/src/ae-icons-component
and
https://github.com/peterennis/ae-svg-components/blob/master/src/index.html
I have been testing this for Ionic 4 development.

Here is the standalone stencil component: https://github.com/adaept/ae-ionicons

Maybe it helps with what you want to do.
Feedback welcome.

**Comment by juanmiguelbesada** [comment]
hi @peterennis

I didn't mean about how to use ionicons as a web components. Just that the docs site (https://ionicons.com/) is not using the icons as web-component but as a font.

**Comment by brandyscarney** [comment]
It can be used as either. We recommend using it as a font when you are displaying hundreds of icons on one page (like the site is), see the [README](https://github.com/ionic-team/ionicons#using-the-font-icon) excerpt here:

> However, if a webpage has to show many icons at once (such as this website's homepage which is showing 700+ icons on one page), the font icon may be a better choice.

We use ionicons as a web component in the Ionic Framework, so it isn't like we are never using it. 🙂

**Comment by brandyscarney** [comment]
Also, there is more information on that on this issue: https://github.com/ionic-team/ionicons/issues/499
