### ISSUE TITLE
icon selection

### ISSUE THREAD

**Issue by explorewhisky** [ionic-team/ionicons#633]
Is it possible to upload your own icons instead of using the image of icons. The lack of selection is leaving my site looking very dull and bland.

**Comment by brandyscarney** [comment]
I don't fully understand the question, are you looking for this: https://ionicons.com/usage#basic-usage?

> To use a custom SVG, provide its url in the src attribute to request the external SVG file. The src attribute works the same as `<img src="...">` in that the url must be accessible from the webpage that's making a request for the image. Additionally, the external file can only be a valid svg and does not allow scripts or events within the svg element.
>
> ```
> <ion-icon src="/path/to/external/file.svg"></ion-icon>
> ```
