### ISSUE TITLE
[cli v4] App size too big, all ionicons v4 packed into bundle

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionicons#637]
**Description:**
In an Ionic v4 app, when building it with the cli v4, all ionicons will be integrated in the bundle regardless of their use or not which leads to a too big app size

When I run `ionic cordova build android --prod --release` the `app-release.apk` will contains a folder `www/svg` with all ionicons

**Steps to Reproduce:**

     ionic start test-icons --type=angular
     cd test-icons
     ionic cordova build android --prod
     cd platforms/android/app/build/outputs/apk/debug/
     unzip app-debug.apk
     cd assets/www/svg/
     ls -ltr

or

    ls -ltr | wc -l 

which will count 697 icons

**Output:**

<img width="637" alt="capture d ecran 2018-08-16 a 21 11 41" src="https://user-images.githubusercontent.com/16886711/44229773-5e5cac00-a199-11e8-9909-0fdb6982dcff.png">

**My `ionic info`:**

> Ionic:
> 
>    ionic (Ionic CLI)          : 4.0.3 (/usr/local/lib/node_modules/ionic)
>    Ionic Framework            : @ionic/angular 4.0.0-beta.3
>    @angular-devkit/core       : 0.7.3
>    @angular-devkit/schematics : 0.7.3
>    @angular/cli               : 6.1.3
>    @ionic/ng-toolkit          : 1.0.6
>    @ionic/schematics-angular  : 1.0.5
> 
> Cordova:
> 
>    cordova (Cordova CLI) : 8.0.0
>    Cordova Platforms     : android 7.0.0
> 
> System:
> 
>    Android SDK Tools : 26.1.1
>    ios-deploy        : 1.9.2
>    ios-sim           : 5.0.13
>    NodeJS            : v10.4.0 (/usr/local/bin/node)
>    npm               : 6.2.0
>    OS                : macOS High Sierra
>    Xcode             : Xcode 9.4.1 Build version 9F2000

**Comment by bkarv** [comment]
I just did a PWA production build (ionic build --prod) and in the WWW folder the SVG's add up to 6.9mb. Surely something must be going wrong??

I am using Ionic Icons 4.5.1 and snapshot fo the SVG. 
<img width="832" alt="screen shot 2018-12-24 at 1 46 26 am" src="https://user-images.githubusercontent.com/10624315/50384787-de81b800-071d-11e9-8a82-53c97a8231f9.png">

**Comment by pitamash** [comment]
go to platforms folder ,
search png or jpg ,
delete all images you think you added and don't want.,
Or delete images you dont neeed in your assets/imgs/ folder,

**Comment by yash-mistry** [comment]
I have solved problem by removing www folder from project and then build.

**Comment by gdinn** [comment]
> I have solved problem by removing www folder from project and then build.

It worked, but in my case I also removed plaforms, plugins and node_modules because removing www lead me to another issue, which after removing these aditional folders (and doing npm install and all that) resolved.

**Comment by guillemmateos** [comment]
Are there any updates on this or workarounds? I'm having the same issue that others have mentioned. Building a Vue app that uses `@ionic/vue` and I get about 800 svg files bundled on my app. Even worse as @peterpeterparker mentioned, the serviceworker tries to cache them all, which is a non-sense.

**Comment by peterpeterparker** [comment]
If I'm not wrong I thing that this is solved with Ionicons v5 or this isn't a thing anymore in v5.

Therefore I close my issue.

**Comment by Kataklism** [comment]
I upgraded to v5 and still get every single icon bundled with the app. It's getting even worse with over 1200 icons (~648kB) in Ionicons v5. Am I missing something?

**Comment by nucklehead** [comment]
Yeah the problem is still there. I had to create a script to delete unused icons so I can deploy as web app and not have 1200+ icons.
https://gist.github.com/nucklehead/b568dc13d01b18b902c524754a7c9cd4

Maybe this can help someone for now.

**Comment by amjadyahya1** [comment]
In my case (ionic 5 app) the svg folder inside www is 6MB (1230 svg files)

**Comment by sylvinrodz** [comment]
**Do the following steps**

1. ng build --prod
2. delete www before building from the root folder
3. ionic cordova build android --prod --release

my app size was 24 MB after doing above steps it reduces to 9 MB

**Comment by sandipdutta1993** [comment]
> **Do the following steps**
> 
> 1. ng build --prod
> 2. delete www before building from the root folder
> 3. ionic cordova build android --prod --release
> 
> my app size was 24 MB after doing above steps it reduces to 9 MB

Followed your steps but problem is still there. Ionic 5 app, 1227 icons are still present, where i'm using only 17-20 icons.

**Comment by amjadyahya1** [comment]
The issue of unnecessary svg icons has to be addressed, we are talking 5-6MB. My app size in total is 9MB, this means the icons are almost 60% of the total size of the binary.

**Comment by aaronwJordan** [comment]
@sylvinrodz @sandipdutta1993 I can't seem to find the `www` folder, what's the exact pathing on that for both iOS and Android?

**Comment by sylvinrodz** [comment]
@aaronwJordan it is the inside root folder

**Comment by andrecadete** [comment]
Every similar tool avoids copying files that are unused in the project. Why do we have to have thousands of files in total if 80% of them are not used? Please give this priority, I'm playing around with static hosting and it's insane to sync 1500+ files.
