### ISSUE TITLE
cellular icon not showing

### ISSUE THREAD

**Issue by kevin554** [ionic-team/ionicons#639]
<ion-icon name="cellular" item-start></ion-icon>

For some reason this icon is not showing either in md o ios styles 

It should work according to the docs: https://ionicons.com/usage#md-cellular

**Comment by brandyscarney** [comment]
Could you please provide some code of how you are using this icon? I can see this working within Ionic:

<img width="55" alt="screen shot 2019-01-17 at 12 38 31 pm" src="https://user-images.githubusercontent.com/6577830/51337355-e3076b00-1a54-11e9-9ef5-e633b922b762.png">
<img width="54" alt="screen shot 2019-01-17 at 12 38 42 pm" src="https://user-images.githubusercontent.com/6577830/51337357-e3076b00-1a54-11e9-8d52-0797085cd15b.png">


```
<ion-icon name="cellular" color="danger"></ion-icon>
```

**Comment by daneyexpo** [comment]
`<ion-icon name="md-add"></ion-icon>`

I can get a background color for the icon to render but not the icon itself. 4.00.

**Comment by brandyscarney** [comment]
Please provide a way for me to reproduce. I cannot reproduce it using Ionicons alone in a Codepen (version `4.5.5` of ionicons): https://codepen.io/brandyscarney/pen/Vgerea

If you can, please fork that and modify the code to reproduce the problem, or, if it only happens in Ionic, provide a small sample project (or create an issue over there: https://github.com/ionic-team/ionic). Thanks!
