### ISSUE TITLE
Icon Request: Edit Icon

### ISSUE THREAD

**Issue by janhesters** [ionic-team/ionicons#645]
Add iOS / Androids default edit icon:

<img width="43" alt="edit" src="https://user-images.githubusercontent.com/31096420/49720670-b5aeec80-fc60-11e8-9547-2aac6bcdcc5c.png">

**Comment by pwespi** [comment]
Maybe `<ion-icon name="create"></ion-icon>` is what you're looking for?

**Comment by brandyscarney** [comment]
Could you please let us know if the `create` icon is sufficient? Thanks!

**Comment by pwespi** [comment]
@brandyscarney Sometimes it's hard to find the right icon with the search on https://ionicons.com/
Maybe you could take a look at this PR https://github.com/ionic-team/ionicons/pull/539 to improve it? Thanks!

**Comment by brandyscarney** [comment]
@pwespi Thank you! I was actually just getting ready to add some tags, so this is great!

**Comment by janhesters** [comment]
@brandyscarney Unfortunately, no, `create` is not the right one even though it is close. But the actual edit icon has is outlined just like in my post above.

**Comment by Langstra** [comment]
Checkout the iOS style icon of create.

**Comment by amandaejohnston** [comment]
Thanks for the request. `create-outline` matches when you're looking for, so I'll close this out 👍
