### ISSUE TITLE
journal icon does not change color

### ISSUE THREAD

**Issue by Eraldo** [ionic-team/ionicons#657]
If I try to change the color of the journal icon (md version), I get a black icon.
```html
<ion-icon name="journal" color="primary"></ion-icon>
```

This happens no matter what color I set.
It is also the only one that is black if I do not set any color property at all.

My guess is that the svg has a fixed color set or something like that.

**Comment by brandyscarney** [comment]
Thanks for the issue! Could you try with the `ionicons@next` version `ionicons@4.5.2-0`? This should be fixed there!

**Comment by brandyscarney** [comment]
Glad it's working! I just released `4.5.2` by the way if you want to update (again). It's exactly the same I just wanted to pre-release to make sure I didn't break anything before updating latest. 🙂
