### ISSUE TITLE
close-circle-outline icon does not show

### ISSUE THREAD

**Issue by Genarito** [ionic-team/ionicons#658]
Hi, i have the following code:
```

<ion-list no-lines>
    <ion-item>
        <strong>Anything</strong>
	<button ion-button icon-only clear color="danger" item-end (click)="something()" [disabled]="!something">
	    <ion-icon name="close-circle-outline"></ion-icon>
	</button>
    </ion-item>
</ion-list>
```

And the icon is not displayed, with _trash_ icon for example, it works normally.
Tested on **Android** only.

My `ionic info` output:

> Ionic:
> 
>    ionic (Ionic CLI)  : 4.9.0 (/opt/node-v8.10.0-linux-x64/lib/node_modules/ionic)
>    Ionic Framework    : ionic-angular 3.9.2
>    @ionic/app-scripts : 3.2.1
> 
> Cordova:
> 
>    cordova (Cordova CLI) : 8.0.0
>    Cordova Platforms     : android 7.0.0
>    Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 16 other plugins)
> 
> System:
> 
>    Android SDK Tools : 26.1.1 (/home/genaro/Android/Sdk)
>    NodeJS            : v8.10.0 (/opt/node-v8.10.0-linux-x64/bin/node)
>    npm               : 6.7.0
>    OS                : Linux 4.18
> 

Thanks in advance

**Comment by jrtibbetts** [comment]
You forgot the `e` at the end of the icon's name.

`<ion-icon name="close-circle-outlin"></ion-icon>`

**Comment by Genarito** [comment]
Unfortunately It was a spelling error. In the code I'm writing well and It's still not working. I've edited to fixed that error and added my env info

Also, I noted that the icon is only available for iOS in ionicons.svg

`<glyph glyph-name="ion-ios-close-circle-outline" unicode="&#xf14d;`

It's the only line referencing that icon

**Comment by Genarito** [comment]
Ok, I realised that the icon is not available in [ionicons v3](https://ionicframework.com/docs/v3/ionicons/) I thought that there were the same icons for both versions
