### ISSUE TITLE
arrow-up and a few others missing

### ISSUE THREAD

**Issue by JerryBels** [ionic-team/ionicons#659]
Hello,

In the last version of ionic `v4.0.0`, the `arrow-up` icon doesn't show.

I found as well that `log-out` doesn't show, as well as `people`, `alarm`, `paper-plane`, and so on.

**Comment by MELAS007** [comment]
All icons aren't show at all in ionic 4!!!
Any suggestions?

**Comment by JerryBels** [comment]
See here for more info - https://github.com/ionic-team/ionic/issues/17366
