### ISSUE TITLE
ionicons.com - Only navbar is shown

### ISSUE THREAD

**Issue by mehmetalpsumer** [ionic-team/ionicons#661]
When I try to visit (supposing icons are displayed there) "ionicons.com", only the navbar is displayed. Tried both Firefox and Chrome, turning off all plugins, tried with DNS as well. Am I missing something?

**Comment by perrygovier** [comment]
Hey @mehmetalpsumer, could you show us the network panel? @mesutcakir is having trouble in issue #663 too and it looks like you're both from Turkey. Are any other sites acting up? Does code.ionicframework.com load ok? It's hosted in the same place as ionicons.com

**Comment by perrygovier** [comment]
I was mistaken. It wasn't a block, it had to do with a bug in the Stencil router and how the Turkish language handles lower case "I". [This commit](https://github.com/ionic-team/stencil-router/commit/8b474181b5f73e5860ff5e698b32846cb68f173e) in the router fixes it. 

After setting my computer to Turkish, I was able to reproduce the issue. Updating the router and a hard refresh fixes it. Should be good now. Thanks for the issue!

**Comment by perrygovier** [comment]
I was mistaken. It wasn't a block, it had to do with a bug in the Stencil router and how the Turkish language handles lower case "I". [This commit](https://github.com/ionic-team/stencil-router/commit/8b474181b5f73e5860ff5e698b32846cb68f173e) in the router fixes it. 

After setting my computer to Turkish, I was able to reproduce the issue. Updating the router and a hard refresh fixes it. Should be good now. Thanks for the issue!
