### ISSUE TITLE
https://ionicons.com/ Not Working.

### ISSUE THREAD

**Issue by mesutcakir** [ionic-team/ionicons#663]
Ctrl+f5, disable cache, secure new tab.  I try it but not working.

![image](https://user-images.githubusercontent.com/4125460/52649127-c4cc4800-2ef8-11e9-9f04-4ffea6478975.png)

**Comment by mesutcakir** [comment]
![image](https://user-images.githubusercontent.com/4125460/52912037-e775ac80-32bc-11e9-96cd-5f441674a8c1.png)
Not fixed problem.

**Comment by mesutcakir** [comment]
https://ionicons.com/cheatsheet.html

I follow to icons this link.

**Comment by perrygovier** [comment]
Hey @mesutcakir, could you show us the network panel? @mehmetalpsumer is having trouble in issue #661 too and it looks like you're both from Turkey. Are any other sites acting up? Does code.ionicframework.com load ok? It's hosted in the same place as ionicons.com
