### ISSUE TITLE
Ionic icons do not work in the latest version

### ISSUE THREAD

**Issue by marlonwesleysimon** [ionic-team/ionicons#664]

**Comment by Xawery94** [comment]
Just tested in my project and it's working fine. If You are using 4.5.5 version of ionic icons you need also add this one:
```
<script src="https://unpkg.com/ionicons@4.5.5/dist/ionicons.js"></script>
```

to the index.html in your project. After that changes it should be working fine.

**Comment by SherifMoShalaby** [comment]
not all icons are working.
**looks like some svg images are removed**
`<ion-icon slot="icon-only" name="arrow-back"></ion-icon>` not working giving an error
"http://localhost:8100/svg/md-arrow-back.svg 404 (Not Found)"

but icons like settings, md-medical, md-information-circle are working properly.

**Comment by SherifMoShalaby** [comment]
@brandyscarney

**Comment by SherifMoShalaby** [comment]
okay i got the problem
chrome browser is caching
just clean chrome caching and everything now is working well

**Comment by aleksander351** [comment]
I cleared caching, but still... After upgrading Ionic to @Ionic/angular 4.0.2

![ionicons-1](https://user-images.githubusercontent.com/7508670/53437378-a8063900-39fd-11e9-8a8e-c32979d86cb4.png)

**Comment by SherifMoShalaby** [comment]
> I cleared caching, but still... After upgrading Ionic to @Ionic/angular 4.0.2
> 
> ![ionicons-1](https://user-images.githubusercontent.com/7508670/53437378-a8063900-39fd-11e9-8a8e-c32979d86cb4.png)

then you are no upgrading in a right way
you have to follow this
https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#breaking-changes-2

**Comment by aleksander351** [comment]
Awesome, it worked. Thanks @SherifMoShalaby
