### ISSUE TITLE
Icons do not appear on ios websites

### ISSUE THREAD

**Issue by HeribertoRB** [ionic-team/ionicons#667]
I built a website and I have tested on macos, android, and ios. Only ios browsers do not show the icons. I was looking to see if I am missing something but I did not find anything.

I have this script line:
    <script src="https://unpkg.com/ionicons@4.2.2/dist/ionicons.js"></script>

And this is my icon:
<ion-icon size="large" name="logo-github"></ion-icon>
        <a href="https://bitbucket.org/berna052" />

**Comment by bswank** [comment]
@HeribertoRB This may be related to #692 – any chance you figured it out?
