### ISSUE TITLE
.scss files ares missing

### ISSUE THREAD

**Issue by hugobqd** [ionic-team/ionicons#669]
Is there a reason why **ionicons-common.scss** and **ionicons-icons.scss** are missing from the sources ?

In `src/scss/ionicons.scss` : 

```
@import "ionicons-common";
@import "ionicons-icons";
```

**Comment by hugobqd** [comment]
@pwespi  sorry but I can't understand your point. The files are still missing in branch **master** and **4.1** (v3 look complete)

**Comment by pwespi** [comment]
> 
> 
> @pwespi sorry but I can't understand your point. The files are still missing in branch **master** and **4.1** (v3 look complete)

@hugobqd what point are you referring to?

**Comment by hugobqd** [comment]
I'm refering to your answer that you delete : 
`$ionicons-font-path: "~ionicons/dist/fonts";
@import "~ionicons/dist/scss/ionicons.scss";

in the global.scss`

**Comment by amandaejohnston** [comment]
Thanks for the report. It looks like the code has since been restructured to avoid this problem, so I'll close this out. If you're still running into issues, please open a new ticket. Thank you!
