### ISSUE TITLE
Icons being fetched from wrong URL

### ISSUE THREAD

**Issue by NunoSav** [ionic-team/ionicons#673]
I'm using Ionic v4 with VueJS and for pages with nested routes like `/x/y` the component `ion-icon` will make a request to `localhost:8080/x/svg/...` instead of `localhost:8080/svg/...`.

The end result is me not being able to see the icons on such pages.
If there's need for clarification please let me know.

**Comment by riderx** [comment]
@NunoSav i got the same did you found a solution ?

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. There's not a lot of information regarding the issue you are encountering, so I am going to close this. If you are still running into this please feel free to open a new issue and include a reproduction.
