### ISSUE TITLE
CORS on web ios < 12

### ISSUE THREAD

**Issue by juliengloria** [ionic-team/ionicons#674]
Hi, 
I got a CORS error when i go to my website with an ios device < 12.0.0.
All icons are failing : Fetch API cannot load "...svg" Origin is not allowed by Access-Control-Allow-Origin.

No problem with my desktop computer

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. I am going to close as there is not enough information for us to verify this bug. If this is still a problem with the latest version of Ionicons, please reply to this thread with a GitHub repo that we can use to verify the reported behavior.
