### ISSUE TITLE
arrow-forward direction in android 6 or above difference in android 5 or below

### ISSUE THREAD

**Issue by shomid** [ionic-team/ionicons#679]
ion-icon with arrow-forward direction in android 6 or above difference in android 5 or below.
in android 6 or above is direction to left but in android 5 or below is direction to right.
why ?

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. There's not a lot of information regarding the issue you are encountering, so I am going to close this. If you are still running into this please feel free to open a new issue and include a reproduction.
