### ISSUE TITLE
Ionicons for Vue - Best way to register as a component?

### ISSUE THREAD

**Issue by eddiejibson** [ionic-team/ionicons#680]
Hello,

So I'm currently using Ionicons within a VueJS application. I've loaded the icons via the Javascript script. However, because I obviously haven't registered the <ion-icon> component, lots of errors like "Unknown custom element: <ion-icon>" appear (as expected).

I know you don't support VueJS and I'm also aware other libraries exist for implementing this into Vue but the general syntax changes so I wasn't so keen. Anyway, despite this, wondering if anyone has any ideas on how best I could register it as a component to stop errors like this from happening?

Cheers.

**Comment by AlbatiQue** [comment]
Hey,

Did you have solution for this problem?

**Comment by devmount** [comment]
It isn't exactly solving the problem, but to make Vue ignore these custom elements, you could add this to your `main.js`:

```javascript
Vue.config.ignoredElements = [/^ion-/]
```

I would love to get to know the proper way of registering the recently released IonIcons 5.0.0 as component in Vue too!

**Comment by amandaejohnston** [comment]
Hi folks, support for this has since been added. You can see example code for all supported frameworks including Vue here: https://ionicframework.com/docs/api/icon#basic-usage
