### ISSUE TITLE
v4.5.6 CDN still loads v4.5.5?

### ISSUE THREAD

**Issue by TheDigitalOrchard** [ionic-team/ionicons#683]
v4.5.6 version still seems to load v4.5.5 from the CDN.

Furthemore, the readme.md references a very old version, 4.2.2.

**Comment by brandyscarney** [comment]
Thanks for the issue! How are you seeing `4.5.5`? I see `4.5.6` in the package file: https://unpkg.com/ionicons@4.5.6/package.json

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. I am going to close as there is not enough information for us to verify this bug. If this is still a problem with the latest version of Ionicons, please reply to this thread with a GitHub repo that we can use to verify the reported behavior.
