### ISSUE TITLE
There used to be a placeholder/spinner option

### ISSUE THREAD

**Issue by drannex42** [ionic-team/ionicons#686]
Does anyone know where this has gone for the new js loading system? Currently my interface is jumping around because the icons take a .2 seconds to load after the rest of the UI, and the spinner class allowed me to have an icon in its place before they fully loaded.

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. There's not a lot of information regarding the issue you are encountering, so I am going to close this. If you are still running into this please feel free to open a new issue and include a reproduction.
