### ISSUE TITLE
ionicons.com website: v3 link redirects back to main page

### ISSUE THREAD

**Issue by janhaertel** [ionic-team/ionicons#691]
At the **bottom** of **ionicons.com** there are some links (v1, v2 and v3). Unfortunately **v3** **redirects** **back to** the **main page** so it is not possible to see the icons version 3. "v1" and "v2" work fine..

**Comment by NiklasMerz** [comment]
I encountered the same issue. Where can I find the website? I would like to submit a PR.

The correct URL is: https://ionicframework.com/docs/v3/ionicons/

**Comment by rtpHarry** [comment]
I just foudn this as well. It seems the site was removed via a pull request [not long ago](https://github.com/ionic-team/ionicons/commit/ce43b6c4afd502d8875845fc2dc859c24158a167). 

It doesn't seem to be in a public repo any more.

**Comment by NiklasMerz** [comment]
Yes V3 was removed from the ionicons-site repo. But it still available as part of the v3 docs. https://ionicframework.com/docs/v3/ionicons/

**Comment by rtpHarry** [comment]
What we are reporting is this link in the footer of https://ionicons.com/

![image](https://user-images.githubusercontent.com/1038062/61101163-67362a80-a49b-11e9-9603-cb03f2efbecd.png)

Points at:

https://ionicframework.com/docs/ionicons/

But should point at:

https://ionicframework.com/docs/v3/ionicons/

**Comment by amandaejohnston** [comment]
Thanks for the report. Looks like this has since been resolved -- the v3 footer link currently points to https://ionicframework.com/docs/v3/ionicons/ -- so I'll close this out.
