### ISSUE TITLE
Document release version scheme

### ISSUE THREAD

**Issue by ainola** [ionic-team/ionicons#695]
Was there a mistaken release of 4.5.9-0? I see that it's part of the `stencil-one` branch and not master.

Incidentally, is there a reason that the version scheme keeps switching back and forth between X.x.y and X.x.y-z? 

Thanks!

**Comment by ainola** [comment]
Hi, I'm still confused as to how your team tags releases. This makes it difficult to package in a reliable manner. Can some light be shed on this issue, please?

**Comment by amandaejohnston** [comment]
Thanks for the issue. This has since been resolved; we've been using regular semver style (`major-minor-patch`) for a couple major releases now. I'm going to close this out, but let me know if you have any additional questions.
