### ISSUE TITLE
Slack icon refresh

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionicons#696]
Hi,

I think Slack changed their branding, therefore the "logo-slack" might need a refresh.

Thx in advance

Current Slack's Ionicon:

![_ionicons_svg_logo-slack](https://user-images.githubusercontent.com/16886711/58639997-6df84c00-82f8-11e9-8393-48a5bc34f7a6.png)

Current Slack's branding logo:

![Slack Mark Monochrome Black](https://user-images.githubusercontent.com/16886711/58640043-7ea8c200-82f8-11e9-9e32-57a920cea468.png)

More Slack logos: https://brandfolder.com/slack/logos

**Comment by georgioupanayiotis** [comment]
picking this one!

**Comment by georgioupanayiotis** [comment]
PR opened for this [https://github.com/ionic-team/ionicons/pull/729](url)

**Comment by peterpeterparker** [comment]
Solved with v5
