### ISSUE TITLE
[bug?] icon was not resolved

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionicons#698]
I use the `ionicons` in a PWA developed with `Stencil One` and `Ionic One`

When I use icons like the following:

```
<ion-icon ios="md-trash" md="md-trash"></ion-icon>
```

I face time to time the following error at runtime in the browser (Chrome at least):

```
icon was not resolved
```

if I then set the property `name` it solves the issue

```
<ion-icon name="trash" ios="md-trash" md="md-trash"></ion-icon>
```

But I'm not sure that's the intended behavior as it isn't what's described in the usage section: https://ionicons.com/usage

Demo:

https://www.dropbox.com/s/b5qkdh3yml180q9/ionicon.mov?dl=0

**Comment by cmer4** [comment]
Have the same issue, exactly the same.

**Comment by tiagosilveiraa** [comment]
Hi, I'm facing the same issue.

**Comment by diyarfaraj** [comment]
facing same issue here.

**Comment by giuliopanda** [comment]
The post is closed but...
If you clone an element with <ion-icon ...></ion-icon>
Google Chrome shows this error in the console: 'icon was not resolved'.
This happens because the element <ion-icon></ion-icon> has already rendered a shadow element inside. 
I resolved before clone:

    $clone.find('ion-icon').each(function() {
        console.log($(this).attr('class'));
        $(this).removeClass('md').removeClass('hydrated');
        $(this).after($("<ion-icon name=" + $(this).attr('name') + " class=" + $(this).attr('class') +"></ion-icon>"));
        $(this).remove();
    });
