### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by 9mm** [ionic-team/ionicons#701]
Why do some icons not work.....?

https://unpkg.com/ionicons@4.5.5/dist/ionicons/svg/md-return-left.svg

![image](https://user-images.githubusercontent.com/1386207/60142875-9dbc3780-9770-11e9-8191-57ea7519cfaa.png)

**Comment by 9mm** [comment]
Now that one works and this one doesnt.. whats goin on here?

https://unpkg.com/ionicons@4.5.5/dist/ionicons/svg/ios-construct.svg

**Comment by amandaejohnston** [comment]
This appears to have been resolved in the time since this was posted, so I'll close it out. If you're still having problems, please open a new issue. Thank you!
