### ISSUE TITLE
Is there any explanation why with React >16.8.5 ionicons take class instead of className

### ISSUE THREAD

**Issue by NickolasBenakis** [ionic-team/ionicons#702]
I had className in my JSX as usual but it was never read properly by browser so I changed the directive's name  to class and it worked . Why is this happening? Supposing that in React we always use className instead of class.
![image](https://user-images.githubusercontent.com/32495928/60211931-d2abb580-9868-11e9-88c2-36a05320f19e.png)

**Comment by Psvensso** [comment]
Why do you use <ion-icon /> directive directly and not the react component <IonIcon/>?

**Comment by NickolasBenakis** [comment]
@Psvensso  Thank you.
