### ISSUE TITLE
provide unicode in data.json

### ISSUE THREAD

**Issue by oudi** [ionic-team/ionicons#718]
I have to have the unicode of each icons that to show in windows controls! because windows controls only can darwing the icons from ttf with unicode. but i can not know the code! https://github.com/ionic-team/ionicons/blob/master/src/data.json

**Comment by oudi** [comment]
I find the code from https://github.com/ionic-team/ionicons/blob/master/scripts/manifest.json close the Issue!

**Comment by saixin** [comment]
https://github.com/ionic-team/ionicons/blob/master/scripts/manifest.json this url is now http 404 error, what's the new address?

**Comment by oudi** [comment]
> https://github.com/ionic-team/ionicons/blob/master/scripts/manifest.json this url is now http 404 error, what's the new address?

you can see the history: https://github.com/ionic-team/ionicons/blob/883934186022812214c5ba584cad31dbe209ab00/scripts/manifest.json
