### ISSUE TITLE
[Icon request] Greater & Less than

### ISSUE THREAD

**Issue by fancydev18** [ionic-team/ionicons#724]
Please add 2 icons: Greater & Less than
(eg to be used in breadcrumbs)

**Comment by mapsandapps** [comment]
Hi, it sounds like the `chevron-forward` and `chevron-back` icons should work for what you need.
<img width="87" alt="Screenshot 2023-05-25 at 2 37 34 PM" src="https://github.com/ionic-team/ionicons/assets/14926794/a7bd2c00-9bdc-43df-8bb4-1b639a34ed77">

If not, please let us know more specifically what you're looking for. Thank you!

**Comment by amandaejohnston** [comment]
I'm going to close this per the above; if you had something else in mind, please open a new request with example images. Thank you!
