### ISSUE TITLE
Bug - share icon on ios looks like MD icon

### ISSUE THREAD

**Issue by JerryBels** [ionic-team/ionicons#726]
I'm using 

    <ion-icon name="share"></ion-icon>

But it doesn't matter if I'm on Android or Ios, I always get MD icon.

    "@ionic/angular": "4.1.1"

**Comment by brandyscarney** [comment]
Thanks for the issue and sorry for the delay in responding. In the latest version of Ionicons the icon does not change based on the platform. You can change it based on the mode by using the following:

```
<ion-icon md="share" ios="share-sharp"></ion-icon>
```

See the [Ionicons website](https://ionic.io/ionicons) for all of the icons to use. We are working on updating the usage for Ionicons to better showcase this.
