### ISSUE TITLE
[Icon request] Bitcoin Cash

### ISSUE THREAD

**Issue by georgengelmann** [ionic-team/ionicons#730]
Looks like the B for Bitcoin, but tilted the other way.

Usage: for online payment, merchants, donations, exchanges

Example:

https://user-images.githubusercontent.com/10384436/66921504-468eeb00-f01d-11e9-8352-4730f56cd2fb.png

**Comment by constantinosgeorgiou** [comment]
Added bitcoin cash icon. [PR here!](https://github.com/ionic-team/ionicons/pull/731)

**Comment by georgengelmann** [comment]
Thank you!
