### ISSUE TITLE
Link to script not working

### ISSUE THREAD

**Issue by Utshaw** [ionic-team/ionicons#733]
Currently the readme suggests to use the below code to be added inside the html: 
`<script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>`
But the link is broken. I get this error:
`Failed to load resource: the server responded with a status of 404 ()`
Whereas the below code is working:
`<script src="https://unpkg.com/ionicons@4.6.3/dist/ionicons.js"></script>`

**Comment by ericakfranz** [comment]
I ran into a similar problem, but I get this message instead when trying to open the package directly in the browser:

`Cannot find package ionicons@5.0.0`

**Comment by amandaejohnston** [comment]
Thanks for the issue! The link now looks to be working, so I'll close this out. If you're still having trouble with the latest version of Ionicons, please open a new issue.
