### ISSUE TITLE
more icon is missing

### ISSUE THREAD

**Issue by askona** [ionic-team/ionicons#747]
In latest version <ion-icon name="more"></ion-icon> cannot be used, and more.svg file is missing in repository

**Comment by DavidWiesner** [comment]
This is a breaking change mentioned in the [CHANGELOG.md](https://github.com/ionic-team/ionicons/blob/0d757ad96aa42847da80853ac1c0c3d43ac6a641/CHANGELOG.md)

> `more` `deleted` use "ellipsis-horizontal" for ios and "ellipsis-vertical" for md
