### ISSUE TITLE
Loading local svg is very slow ( 3 seconds to load one image)

### ISSUE THREAD

**Issue by AndrWeisR** [ionic-team/ionicons#748]
In my ionic 4 code, I use an arrow icon within an ion-item:

`<ion-icon size="small" slot="end" name="arrow-forward">`

The `http://localhost/svg/md-arrow-forward.svg` resource takes about 3 seconds to load (on a physical Android device), visibly slowing down the page on entry. The same thing happens if I use the SVG as the src of an ion-img.

**Comment by webfletch** [comment]
Did you find a solution to this? I have the same thing on Android device (Samsung Galaxy S8) with Ionic 5, first load of SVG files taking 5 seconds.

![Capture](https://user-images.githubusercontent.com/55058365/80483445-01456180-894e-11ea-821f-a23e92695a7b.PNG)
