### ISSUE TITLE
[Feature Request] Export web component without default icons

### ISSUE THREAD

**Issue by sem4phor** [ionic-team/ionicons#749]
Hello,

I have the use case that i want to build a custom design system with custom svg icons rendered inline.
I want to make use of the ionicon web component and register icons with the exported `addIcons` function to use icons in this style in my stenciljs app (pseudo code):

```
// my-icon-component.tsx
import { addIcons } from 'ionicons';
import building from './building.svg'
addIcons({  'md-building': building });
<ion-icon name="building">
```

This works fine with 2 drawbacks:
- When using addIcons i have to prefix the name with either 'md-' or 'ios-' to make this work
- All default svg assets are bundled into my stencil dist instead of only my custom icons i add with addIcons

It would be really nice if only the web component without default assets could be exposed.

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. With Ionicons v5 we got rid of the MD/iOS specific icons, so the prefix issue should not be happening anymore.

I'm not sure why all SVG assets are being bundled into your application, but using `addIcons` to only import the icons you need should cause only the icons imported to be bundled. There's not a lot of information to go off regarding this, so I'm not able to help much here.

I am going to close this, but please feel free to open a new issue with a reproduction if you are still running into issues. Thanks!
