### ISSUE TITLE
Icon Request: Outline Text Icon

### ISSUE THREAD

**Issue by mikev10** [ionic-team/ionicons#753]
It would be great to have the text icon as an outline icon instead of filled for both iOS and Material.

Here is the icon I am referring to: `<ion-icon class="comment-icon" name="text"></ion-icon>`

**Comment by brandyscarney** [comment]
Thank you for the issue! This has been added in the latest Ionicons, you can find it by searching `chat` on the [Ionicons site](https://ionic.io/ionicons).

![Screen Shot 2022-09-27 at 7 17 29 PM](https://user-images.githubusercontent.com/6577830/192653983-2d80473d-107e-4d1e-bc36-e8670e4db837.png)
