### ISSUE TITLE
Testing 5.0.0-16 and Stencil 1.9.0-12 - female icon wrong

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionicons#761]
@brandyscarney 

Compare:

![Capture796](https://user-images.githubusercontent.com/140737/72641968-33433280-3920-11ea-880f-2ecfca4ae5b2.PNG)

![Capture797](https://user-images.githubusercontent.com/140737/72642142-8a490780-3920-11ea-8978-efd513cfe49d.PNG)

https://aeicon5.firebaseapp.com/

Repo: https://github.com/adaept/ae-icon5-component

**Comment by brandyscarney** [comment]
Thanks! I let @kevinports know. He's going to take a look.

**Comment by kevinports** [comment]
Good catch. Will be fixed when bc14bfea993e6e46fae2b824cc17ca73764ccac9 is released
