### ISSUE TITLE
v5.0.0-16 enter/exit vs. log-in/log-out

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionicons#762]
The icons are the same.
Duplication.
Bug or feature?

![Capture798](https://user-images.githubusercontent.com/140737/72643805-5ec81c00-3924-11ea-96e7-dd0044b2e0bd.PNG)

**Comment by kevinports** [comment]
@peterennis It is a feature. They are drawn differently, though you're fair in saying they look awfully similar. Keeping as is but will raise the duplication question to the team.
