### ISSUE TITLE
Collection of Sports Icons

### ISSUE THREAD

**Issue by EyadIT94** [ionic-team/ionicons#764]
It's good to add Collection of Sports Icons such as summing pool, gym, and other that helps us.

Thank you Ionic Team :).

Regards,
Eyad Al-Hamza

**Comment by amandaejohnston** [comment]
Thank you for the requests. Gym should now be covered under `barbell`, and we have a few other issues already for other types of sports:
- https://github.com/ionic-team/ionicons/issues/744
- https://github.com/ionic-team/ionicons/issues/904
- https://github.com/ionic-team/ionicons/issues/602

I'm going to close this out, but if you had any other specific needs that aren't already covered by existing issues, please open new request(s). Thank you!
