### ISSUE TITLE
[bug] logo icons do not show up

### ISSUE THREAD

**Issue by lucasrleandro** [ionic-team/ionicons#767]
The logo icons, on https://ionicons.com/, are all invisible.
When we select the icon, the svg model beside the ion-icon tag is invisible. Also, when we use it in the code, it wont render. 

_zone.js:1127 GET http://localhost:8100/svg/logo-google-playstore-outline.svg 404 (Not Found)_

**Comment by DannyFullComms** [comment]
The issue seems to be with the docs. Drop "-outline" from the logo ones and they should load just fine. Just had the same issue since updating to v5.

**Comment by jolugama** [comment]
I have the same problem.  When i do ionic serve is ok, but when i run in a www (builded)  ion-icon - shadow-root - icon-inner  <-- here there It should have added the svg, but it's not like that. nothing about any svg embedded.

**Comment by lucasrleandro** [comment]
It looks like it was fixed. At least in ionicons.com they are showing up

**Comment by brandyscarney** [comment]
Thanks for the issue, I am going to close this as it seems it was resolved but please let me know if not!
