### ISSUE TITLE
Ionic 4: Icons do not fit Documentation

### ISSUE THREAD

**Issue by magic-77** [ionic-team/ionicons#770]
I'm using the latest Ionic 4 Version with Angular 8.32.5
But it seems that Icons are missing

Like:
```
<ion-icon name="timer-sharp"></ion-icon>
```
will throw
```
http://localhost:8100/svg/ios-timer-sharp.svg 404 (Not Found)
```

in this case i can only use
```
<ion-icon name="timer"></ion-icon>
```
this loads the outline Icon, but not the filled one

**Comment by syfqpie** [comment]
are you using ionicons v4 or v5? i think `timer-sharp` is for ionicons v5.

but i've upgraded to ionicons v5 and now i cannot use any of the icons. anyone having the same problem?

**Comment by magic-77** [comment]
@syfqpie checking package.json at node_module folder gives me the version 4.6.3 for ionicons.
Do you know how to integrate the v5 ionicons without using the
```
<script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
```

**Comment by brandyscarney** [comment]
Thanks for the issue! The documentation seems to reflect the proper usage for timer in [v4](https://ionic.io/ionicons/v4) and [latest](https://ionic.io/ionicons) so I am going to close this but let me know if I am misunderstanding it.
