### ISSUE TITLE
logo icons 404 (Not Found)

### ISSUE THREAD

**Issue by djabif** [ionic-team/ionicons#771]
**App Icons** work fine in my ionic 5 angular app, however, **Logo icons** throw _404 (Not Found)_.
Tried with different logo icons in different browsers and also tried clearing the cache but the error is still there. 

<img width="1255" alt="Screen Shot 2020-02-12 at 12 04 25" src="https://user-images.githubusercontent.com/1735814/74347462-e40de780-4d8f-11ea-938a-548d1398da93.png">

**Comment by kensodemann** [comment]
When I do a build, it appears that most icons have `-outline` and `-sharp` variants, but logo icons do not.

```
~/Projects/Training/training-deck/www/svg (feature/newLabApplication ✘)✹ ᐅ ls -1 earth*
earth-outline.svg
earth-sharp.svg
earth.svg
~/Projects/Training/training-deck/www/svg (feature/newLabApplication ✘)✹ ᐅ ls logo-firebase*
logo-firebase.svg
```

This is made confusing by the fact that the Ionicons page implies that the variants should at least exist for the logos, even if the don't follow the pattern visually.

**Comment by kensodemann** [comment]
The web-site has been fixed such that the logos will only show with their base variant, so if you are on the "outline" or "sharp" segments and click on the "logo-firebase" icon, it will always tell you to use "logo-firebase" and not the incorrect "logo-firebase-outline" or "logo-firebase-sharp" variants which don't exist.

Closing this issue.
