### ISSUE TITLE
Fonts missing from Ionicons v5.0.0

### ISSUE THREAD

**Issue by ckegley** [ionic-team/ionicons#772]
We are using the newest version of Ionicons packaged with Ionic 5.  Prior to upgrading to Ionic 5, we were able to use Ionicons in CSS as follows:

```
font-family: "Ionicons";
content: '\f119';
```

The font path referenced the Ionicons fonts in the ionicons/dist/fonts dir of node_modules.  Now, it seems that the fonts are no longer present in the Ionicons package.  How can we use the Ionicons font-family in the new release?

We are using:  `@ionic/angular 5.0.0-rc.5` with `ionicons 5.0.0`.

**Comment by ZdrowyGosciu** [comment]
+1
Is there a way to import 5.x as stylesheet (like 4.x ionicons.min.css)?

**Comment by MorenoDD** [comment]
+1

**Comment by rodrigoGA** [comment]
+1

**Comment by augustovicente** [comment]
+1

**Comment by liamdebeasi** [comment]
Hey there,

With Ionicons 5 we moved to using SVGs instead of icon fonts. This reason for this is the icon font required developers to bundle several megabytes of font data with every app, even if they were not using all the icons. With SVGs, developers can include only the icons they need to use in their app. At the moment, we do not have plans to re-introduce the icon font. Thanks for understanding!

**Comment by dkniffin** [comment]
The rationale for removing the font icons definitely makes sense for those apps that do not need the font icons. However, as someone who has recently switched from fontawesome to ionicons and is using them regularly, in many circumstances it is much easier to apply the icons via fonts and CSS than to inject a SVG.

For example, we have a custom checkbox that uses ionicons, and our current solution requires us to have both icons (checked and unchecked) in the HTML, then hide or show them based on the checkbox. It works, but it's clunky.

What if there was a second package like `ionicons-fonticons` that adds the fonticon versions?

**Comment by macCesar** [comment]
Is there a way to generate the font files with ionicons v6.0 ??

Or how can we use the `generate_font.py` script from v4 ??
