### ISSUE TITLE
Published to npm icons are not the same as their source in v5

### ISSUE THREAD

**Issue by talamaska** [ionic-team/ionicons#776]
Particularly 
node_modules/ionicons/dist/ionicons/svg
is different from
node_modules/ionicons/dist/svg

the first one can change colors, but the outline icons are not outlined like in the second source, but are filled in

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. There's not a lot of information regarding the issue you are encountering, so I am going to close this. If you are still running into this please feel free to open a new issue and include a reproduction.
