### ISSUE TITLE
[bug] "export 'reorder' was not found in 'ionicons/icons'

### ISSUE THREAD

**Issue by ehoraizon** [ionic-team/ionicons#777]
I am trying to use i**onic-vue@0.0.9** with **ionicons@5.0.0** when I start the development server giving me two alerts that say **"export 'reorder' was not found in 'ionicons/icons'.**

I know that if I install ionicons@4.5.9-1 the icons run properly, but I want to use the latest version of ionicons in vue.

![ionicons_bug](https://user-images.githubusercontent.com/37258656/74584091-59e69e80-4f9c-11ea-9f84-492cea87f1fb.png)

**Comment by ehoraizon** [comment]
sorry, the easiest way without using any hack, to run ionicons with ionic-vue is to install **ionicons@4.5.9-1** with **ionic-vue@0.0.4**

NOTE: using **ionicons@5.0.0** with **ionic-vue@0.0.4** does not work either

**Comment by SanderMuller** [comment]
I experience this issue as well using ionic-vue@0.0.9 with ionicons@5.0.0

**Comment by franckysolo** [comment]
hello,
ionicons@5.0.0 is working with ionic-vue@0.0.9 
you need to install @ionic/core to get it work!

**Comment by SanderMuller** [comment]
It works with @ionic/core 5.0 but not with @ionic/core 4.6, which ionic-vue@0.0.9 allows ("@ionic/core": "^4.6.0")
