### ISSUE TITLE
CSS color and text-shadow not working

### ISSUE THREAD

**Issue by rzooff** [ionic-team/ionicons#778]
CSS style do not affect icons apperance. Icons are still black and there is no shadow.
All this worked without a problem in v4.

ps. I've used filter: invert(1) to change icons color to white.

Best regards, Maciej

Edit: Above issue applies to "outline" icons only.

**Comment by rzooff** [comment]
Nice surprise - problem has been fixed today.
Thanks a lot for the ionic-team!

Best regards, Maciej

**Comment by Jerige** [comment]
It worked for sometime today but now again icons are black. Are icons load on demand? Seems they are not part of apk installation since I didn't touch app and icons apoear different after few hours??!!

**Comment by Jerige** [comment]
Just to clarify my previous comment. I installed my apk few days ago and icons were black. Today they aooear white and now again black and that hapen without reinstalling or changing anything on my Huawei nova 5T

**Comment by brandyscarney** [comment]
Thanks for the issue! This does not appear to be an issue anymore in latest: https://stackblitz.com/edit/svyepq-rhbk7y?file=index.html

If you are still having problems please create a new issue with a code reproduction, thanks! 🙂
