### ISSUE TITLE
woff files are missing from npm package (v5.0.0)

### ISSUE THREAD

**Issue by hawkeye64** [ionic-team/ionicons#785]
The v5.0.0 NPM package no longer contains the web font (*.woff) files. These files now exist in "docs/font" which are not part of the NPM package as defined by this:
```
  "files": [
    "dist/",
    "icons/"
  ],
```
in `package.json`

Also missing appropriate css file.

Is it the intention to go away from having a web font?

**Comment by webnoob** [comment]
This is severely affecting our ability to provide the latest package in our projects - is there any update on this?

**Comment by MorenoDD** [comment]
+1

**Comment by liamdebeasi** [comment]
Hey there! Apologies for the delay. In Ionic v4 we removed web fonts in favor of SVG elements. The technical reasons of why we did this can be read [here](https://ionic.io/blog/announcing-ionicons-v4?_gl=1*ie8jo0*_ga*MjAxMzM2NTU2Mi4xNzA5MDczMDY4*_ga_REH9TJF6KF*MTcxMDQyNDM0OS4xMi4xLjE3MTA0MjQ0NjguMC4wLjA.).
