### ISSUE TITLE
Style issue: Ionicons not properly resized in Internet Explorer 11

### ISSUE THREAD

**Issue by andreas-aeschlimann** [ionic-team/ionicons#789]
When I'm looking at an Ionicon in IE11, the icon size is 512 pixels. It looks like that CSS settings for the web component are ignored.

Could anyone reproduce and/or fix this issue?

Note: I'm not an IE 11 user, but in the business world, it's still widely used on Windows and must not be completely ignored.

**Comment by andreas-aeschlimann** [comment]
I was able to "fix" it by applying global (s)css:

```
ion-icon svg {
    max-width: 100%;
}
```

**Comment by domschmidt** [comment]
same happens for edge. Thanks for sharing the workaround!

**Comment by liamdebeasi** [comment]
Hi there,

Apologies for the delay. Ionicons no longer supports IE11, so I am going to close this.
