### ISSUE TITLE
bug: Ionic 5.01, Android 6.0, Chrome 44, Icon can't be rendered correctly.

### ISSUE THREAD

**Issue by netsesame2** [ionic-team/ionicons#790]
Works in Ionic 4.4. Not in ionic 5.01.

HTML code:
```
<div class="rbuttons">
    <div class="rbutton" routerLink="/photo">
        <div class="rbutton-in">
            <ion-icon name="desktop-outline" large></ion-icon>
            <ion-ripple-effect></ion-ripple-effect>
        </div>
    </div>
    <div class="rbutton">
        <div class="rbutton-in">
            <ion-icon name="camera-outline" large></ion-icon>
            <ion-ripple-effect></ion-ripple-effect>
        </div>
   </div>
</div>
```
SCSS code:
```
.rbuttons {
    display: flex;
    position: absolute;
    left: 0;
    right: 0;
    bottom: 20px;
    justify-content: center;
    
    .rbutton {
        padding: 0 40px;
        text-align: center;
        .rbutton-in {
            display: flex;
            background: #fff;
            width: 70px;
            height: 70px;
            border-radius: 50%;
            border: 4px solid #e4dfdf;
            justify-content: center;
            align-items: center;
            margin-bottom: 5px;
            ion-icon {
                font-size: 40px;
                color: #e97723;
            }
        }
    }
}
```
It render as:
<img width="299" alt="QQ20200224-233843@2x" src="https://user-images.githubusercontent.com/22102518/75166598-0bd15800-575f-11ea-8f4f-e5f5507dcaa8.png">

It should be:
<img width="304" alt="QQ20200224-234317@2x" src="https://user-images.githubusercontent.com/22102518/75166791-67034a80-575f-11ea-9baa-4c346fe2b33a.png">

**Envoirement:**
Ionic:
   Ionic CLI                     : 6.1.0 
   Ionic Framework               : @ionic/angular 5.0.1
   @angular-devkit/build-angular : 0.900.3
   @angular-devkit/schematics    : 9.0.3
   @angular/cli                  : 9.0.3
   @ionic/angular-toolkit        : 2.1.2

Capacitor:
   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Android in Emulator:
Andriod 6.0
Chrome: 44.0.2403.119

<img width="526" alt="QQ20200224-234923@2x" src="https://user-images.githubusercontent.com/22102518/75167415-47205680-5760-11ea-9268-0747ab92c01a.png">

**Comment by liamdebeasi** [comment]
Thanks for the issue. I transferred this to the Ionicons repository. I was able to reproduce this issue in a blank Capacitor app without Ionic Framework:

```
<ion-icon name="desktop-outline" large></ion-icon>
<ion-icon name="camera-outline" large></ion-icon>
```

**Comment by netsesame2** [comment]
Thanks for your rapid reply.
In fact, there are many other icons have the same issues in above test, like:
```
<ion-icon name="information-circle-outline" color="primary">
```
Hope it can help.

**Comment by sverdlov** [comment]
Hi. Any progress?

**Comment by HealthyPizza** [comment]
Same issue in with android 7.0 
`<ion-icon  name="calendar-outline" > </ion-icon>
<ion-icon  name="pricetags-outline" > </ion-icon>
<ion-icon  name="location-outline" > </ion-icon>`

**Comment by netsesame2** [comment]
@liamdebeasi any results?

**Comment by liamdebeasi** [comment]
Hi there,

Apologies for the delay. Ionicons no longer supports the noted version of Chrome, so I am going to close this.
