### ISSUE TITLE
[bug]: IE11 Add icons aren't displayed

### ISSUE THREAD

**Issue by keo9ren** [ionic-team/ionicons#792]
Following Icons aren't displayed properly in IE11 and old Edge.

Browser:
IE11
Microsoft Edge: 44.18362.449.0
Microsoft EdgeHTML:  18.18362

Icons:
name: add
name: add-circle-outline
Haven't tested other icons yet.

Using:
@stencil/core: 1.8.9
@ionic/core: 5.0.1

Steps to reproduce:
Checkout this repo:
https://github.com/keo9ren/ie11addsign

Execute and open in IE11
```
npm run startie11
```
Left screenshot is from chrome, on the right IE11
![image](https://user-images.githubusercontent.com/15822428/75229368-136e1c80-57b2-11ea-9281-493423db6c59.png)

**Comment by joaovictorr19** [comment]
Hii, Try this:

in src\index.html

<body>
  <app-root></app-root>
  <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
</body>

**Comment by Scan0815** [comment]
Hi @joaovictorr19  on my site, i test with ie edge your script not work. I have the same problems like @keo9ren

**Comment by keo9ren** [comment]
@joaovictorr19  solution doesn't solve my problem either.

**Comment by Scan0815** [comment]
@manucorporat can someone tell us if this a bug been recognized. On the ionicicon.com page the icons will work in ie11 and edge. Many thanks for you response!

**Comment by fritee-test** [comment]
Same issue for me on IE 11

**Comment by viniciuscenci** [comment]
Same problem here, version 5.1.0:

![Screen Shot 2020-06-25 at 3 37 39 PM](https://user-images.githubusercontent.com/2103416/85779337-df701d00-b6f9-11ea-99a5-e3392eb54960.png)

Seems that something is missing, if I put some fill and stroke, it works:

![Screen Shot 2020-06-25 at 3 37 47 PM](https://user-images.githubusercontent.com/2103416/85779553-16dec980-b6fa-11ea-9337-370e64b2522d.png)

![Screen Shot 2020-06-25 at 3 42 55 PM](https://user-images.githubusercontent.com/2103416/85780076-9bc9e300-b6fa-11ea-8855-1b0ef249532a.png)

**Comment by tmwrnr** [comment]
@viniciuscenci's solution works fine, but one note. You need to put these styles on the `svg` itself, if you were wondering like me where to put these styles.

**Comment by amandaejohnston** [comment]
Thank you for the issue. IE11 and old versions of Edge are not supported. I did notice that the Ionicons site doesn't have an official browser support table, though; I've raised this with the team internally so we can get one added. In the meantime, referencing the browser support for Ionic Framework is a safe bet: https://ionicframework.com/docs/reference/browser-support#desktop-browsers
