### ISSUE TITLE
ionicons@5.0.0 not showing in mobile devices!

### ISSUE THREAD

**Issue by beratgashi** [ionic-team/ionicons#794]
Hi community,

Does anyone has issues with ionicons v5 in mobile devices that not showing icons as i could see the `ion-icon` element does not get populated with `hydrated` class!

**Comment by skmohammadi** [comment]
Hi. i have this problem, too.

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. Does this issue still reproduce using the latest version of Ionicons? If so, is there a sample app I can try?
