### ISSUE TITLE
Ionic 4/5: from src content?

### ISSUE THREAD

**Issue by mrtungdev** [ionic-team/ionicons#795]
Hi there,
I'm wondering  can we set icon from src="svg_path" to src="svg_content"?
or another attribute?

**Comment by brandyscarney** [comment]
Thanks for the issue and apologies for the delay. You can use the `icon` property to provide either a path to an SVG or the exact SVG data: https://github.com/ionic-team/ionicons/blob/19629000ca1b6b23a96cc45642dc4ae7ccd89a0b/src/components/icon/icon.tsx#L62
