### ISSUE TITLE
In this folder "docs\fonts\ionicons.ttf" it is not ionicons-5 version fonts files. In this folder it is 4th versions fonts files 

### ISSUE THREAD

**Issue by natiq2004** [ionic-team/ionicons#796]
I download ionicons-5.0.0 release version. But in this folder "docs\fonts\ionicons.ttf" it is not ionicons-5 version fonts files. In this folder it is 4th versions fonts files. When the 5th versions fonts files will be updated?

**Comment by dsheard** [comment]
Also have the same question - love the icons, but please can you share the ttf file as there are missing icons in the v4 ttf? Thanks!

**Comment by natiq2004** [comment]
https://github.com/ecdo/ionicons
