### ISSUE TITLE
bug: Outline and sharp variants are filled on older versions of Firefox and IE11 or Edge

### ISSUE THREAD

**Issue by ohh2ahh** [ionic-team/ionicons#799]
# Bug Report

**Ionicons version:**
[x] **5.0.0**

**Current behavior:**
Outline and sharp variants are filled on older versions of Firefox and IE11 or Edge. It seems that the classes `ionicon-fill-none` and `ionicon-stroke-width` are not applied correctly.

**Expected behavior:**
All variants should be displayed correctly.

**Steps to reproduce:**
1. Install Ionicons as described in https://ionicons.com/usage
2. Add outlined or sharp icon:
```
<ion-icon name="heart-outline"></ion-icon>
```

**Related code:**
CodePen (https://codepen.io/ohh2ahh/pen/OJVOOGr)

**Other information:**
Tested with Firefox 60.9.0esr (Extended Support Release) 64-Bit

**Comment by Scan0815** [comment]
@ohh2ahh hi think it´s the same problem like  https://github.com/ionic-team/ionicons/issues/792
test the "add-outline" icon.

**Comment by liamdebeasi** [comment]
Hi there,

Apologies for the delay. Ionicons no longer supports IE11 and the noted version of Firefox, so I am going to close this.
