### ISSUE TITLE
Icons don't work in Firefox

### ISSUE THREAD

**Issue by mlynch** [ionic-team/ionicons#8]
Might be a corrupted font format generated from icon moon that firefox doesn't like.

**Comment by praveenscience** [comment]
This issue with CDN and Firefox haven't been fixed yet. Have a look at my awesome app! :(

![image](https://cloud.githubusercontent.com/assets/1830380/7219860/1a57c82e-e6ac-11e4-9824-b59da2af4467.png)

Please re-open the issue @mlynch!!! All the other fonts do work!!!

**Comment by pj-c0d3r** [comment]
> Yay, fixed!. Just added code to tell my app to place the font files (.svg, .ttf, .eot .woff) on the primary domain.

What's the code please? I'm experiencing same issue
