### ISSUE TITLE
ios and md properties are not reactive

### ISSUE THREAD

**Issue by kyawswarthwin** [ionic-team/ionicons#802]
<ion-icon
      slot="end"
      [ios]="expanded ? 'caret-up-outline' : 'caret-down-outline'"
      [md]="expanded ? 'caret-up-sharp' : 'caret-down-sharp'"
      size="small"
    ></ion-icon>

Platform specificity not work correctly but work with [name].

**Comment by brandyscarney** [comment]
Thanks for the issue! I was able to reproduce this on latest: https://stackblitz.com/edit/angular-xpcx4t?file=src%2Fapp%2Fexample.component.html

Marking this as a bug as the `name` property is reactive.

**Comment by liamdebeasi** [comment]
Thanks for the report. This was fixed via https://github.com/ionic-team/ionicons/pull/1174.
