### ISSUE TITLE
migrating to ionic5 - some icons appear black

### ISSUE THREAD

**Issue by Jerige** [ionic-team/ionicons#804]
Just migrated from Ionic4 to 5 and icons are messed up. Before all icons were white and now mixed with black color (see pics)

![ionic5](https://user-images.githubusercontent.com/16308423/76564549-05eead00-64a9-11ea-8f9b-4bb3e8c216c4.PNG)

![ionic5-1](https://user-images.githubusercontent.com/16308423/76564944-e1470500-64a9-11ea-9b82-0d3f5679d234.PNG)

Adding pic of code since below not all code is displayed... don't get it why??

Here is the HTML:

<ion-segment>
	<ion-segment-button style="margin: 1px; border-radius: 8px; background-color: #339933; color: snow; "
	color="primary" size="small" class="ion-text-capitalize" (click)="saveData(item.id)">
	<ion-icon name="save"></ion-icon>Save
	</ion-segment-button>

	<ion-segment-button style="margin: 1px; border-radius: 8px; background-color: #003cb3; color: snow; "
	color="primary" size="small" class="ion-text-capitalize" (click)="changeDate(item.id,-1)">
	<ion-icon name="calendar"></ion-icon>Date-1
	</ion-segment-button>

	<ion-segment-button size="small"
	style="margin: 1px; border-radius: 8px; background-color: #003cb3; color: snow;" color="primary"
	size="small" class="ion-text-capitalize" (click)="changeDate(item.id,1)">
	<ion-icon name="calendar"></ion-icon>Date+1
	</ion-segment-button>

	<ion-segment-button style="margin: 1px; border-radius: 8px; background-color: #397EFF; color: snow;"
	color="primary" size="small" class="ion-text-capitalize" (click)="changeAmount1(item.id,'up')">
	<ion-icon name="arrow-up"></ion-icon>{{amountChange}} €
	</ion-segment-button>

	<ion-segment-button style="margin: 1px; border-radius: 8px; background-color: #397EFF; color: snow;"
	size="small" class="ion-text-capitalize" (click)="changeAmount1(item.id,'down')">
	<ion-icon style="color: white;" name="arrow-down"></ion-icon>{{amountChange}} €
	</ion-segment-button>
</ion-segment>

Does anyone else experience the same issue?
Best, 
J.

**Comment by rzooff** [comment]
Yes, same here:
https://github.com/ionic-team/ionicons/issues/778
https://github.com/ionic-team/ionicons/pull/805

**Comment by brandyscarney** [comment]
Thanks for the issue! This should no longer be an issue after https://github.com/ionic-team/ionicons/commit/98fa89ea5731f546f2bc88f53818a3f304d4195a and I am not able to reproduce it using latest: https://stackblitz.com/edit/svyepq?file=index.html

If you are still having problems please create a new issue with a code reproduction, thanks! 🙂
