### ISSUE TITLE
[Icon Request] Please add TikTok Logo

### ISSUE THREAD

**Issue by JPaulMora** [ionic-team/ionicons#808]
Thanks in advance.

**Comment by bensperry** [comment]
This was added. Thanks!

**Comment by KhaledBadarna** [comment]
"logo-tiktok" is not a valid icon name for family "ionicons"

**Comment by Bellarose143** [comment]
This is not working. I get the same error as @KhaledBadarna 

"logo-tiktok" is not a valid icon name for family "ionicons"
