### ISSUE TITLE
Outlined icons aren't working on Ionic4

### ISSUE THREAD

**Issue by marsonvida** [ionic-team/ionicons#812]
I tried to put outlined icons several times on the tab section using this sample tag <ion-icon name="person-outline"></ion-icon> but it didn't work after.

**Comment by aaronksaunders** [comment]
Seeing same issue?

**Comment by nickvorie** [comment]
`
cd node_modules
rm -r ionicons
cd ..
npm i -s ionicons@latest
`

**Comment by brandyscarney** [comment]
Thanks for the issue! I am not able to reproduce this using the latest Ionicons: https://stackblitz.com/edit/2zbn5w?file=index.html

If you are still having issues, please provide a code reproduction for us. Thanks!
