### ISSUE TITLE
Modify the color of the icon ?

### ISSUE THREAD

**Issue by LouisJS** [ionic-team/ionicons#817]
I keep trying to change the colours of my icons via

ion-icon {
  color: blue;
}

They keep appearing black

**Comment by tomasSlouka** [comment]
I have the same problem ... colour of an icon is possible to change only on SVG itself

**Comment by mikekoro** [comment]
Seems like its selective. For instance, I can change the colour of `<ion-icon name="people-circle-outline"></ion-icon>` using css but not `<ion-icon name="megaphone-outline"></ion-icon>` or 

> <ion-icon name="medal-outline"></ion-icon>

**Comment by penhold3r** [comment]
Same here, rolling back to 4.5

**Comment by 0utlandish** [comment]
same here, just can change the filled icons color ! so annoying.

**Comment by tpuleo** [comment]
Same issue with:
`<ion-icon name="infinite-outline" class="icon-big"></ion-icon>`
`<ion-icon name="stopwatch-outline" class="icon-big"></ion-icon>`
`<ion-icon name="rose-outline" class="icon-big"></ion-icon>`
`<ion-icon name="cart-outline" class="icon-big"></ion-icon>`

Using CSS:
`.icon-big {
    font-size: 300%;
    display: block;
    color: blue;
    margin-bottom: 10px;
}`

The other attributes such as font-size change correctly but color does not. Also tried "fill" instead of color and also didn't work.

**Comment by hades200082** [comment]
Same issue here. Also rolled back to 4.5

**Comment by jonathanconway** [comment]
Same issue :(

**Comment by Abdurahmanm2020** [comment]
**may be you can try**

**` <ion-icon name="link" color="danger"></ion-icon>`**

**an it might work**
**_but i don't know for sure_**

**Comment by tomasSlouka** [comment]
> **may be you can try**
> 
> **` <ion-icon name="link" color="danger"></ion-icon>`**
> 
> **an it might work**
> **_but i don't know for sure_**

yes but what if you want purple icon?

**Comment by Abdurahmanm2020** [comment]
> > **may be you can try**
> > **` <ion-icon name="link" color="danger"></ion-icon>`**
> > **an it might work**
> > **_but i don't know for sure_**
> 
> yes but what if you want purple icon?

**if purple is the color you want then may be look up the purple one or just try to type** 

**`<ion-icon name="link" color="purple"></ion-icon>`**

or  the hex

**Comment by tomasSlouka** [comment]
> > > **may be you can try**
> > > **` <ion-icon name="link" color="danger"></ion-icon>`**
> > > **an it might work**
> > > **_but i don't know for sure_**
> > 
> > 
> > yes but what if you want purple icon?
> 
> **if purple is the color you want then may be look up the purple one or just try to type**
> 
> **`<ion-icon name="link" color="purple"></ion-icon>`**
> 
> or the hex

what if you have all of your 100 icons in your application purple and after a week you decide that you want them to be orange.

**Comment by Abdurahmanm2020** [comment]
> > > > **may be you can try**
> > > > **` <ion-icon name="link" color="danger"></ion-icon>`**
> > > > **an it might work**
> > > > **_but i don't know for sure_**
> > > 
> > > 
> > > yes but what if you want purple icon?
> > 
> > 
> > **if purple is the color you want then may be look up the purple one or just try to type**
> > **`<ion-icon name="link" color="purple"></ion-icon>`**
> > or the hex
> 
> what if you have all of your 100 icons in your application purple and after a week you decide that you want them to be orange.

then it will be harder to get it all again but this time orange so when you start get purple, orange, black and all the colors you might want later

**Comment by tomasSlouka** [comment]
> > > > > **may be you can try**
> > > > > **` <ion-icon name="link" color="danger"></ion-icon>`**
> > > > > **an it might work**
> > > > > **_but i don't know for sure_**
> > > > 
> > > > 
> > > > yes but what if you want purple icon?
> > > 
> > > 
> > > **if purple is the color you want then may be look up the purple one or just try to type**
> > > **`<ion-icon name="link" color="purple"></ion-icon>`**
> > > or the hex
> > 
> > 
> > what if you have all of your 100 icons in your application purple and after a week you decide that you want them to be orange.
> 
> then it will be harder to get it all again but this time orange so when you start get purple, orange, black and all the colors you might want later

that's why it's better to do it with CSS and not with an element prop.

**Comment by Abdurahmanm2020** [comment]
> > > > > > **may be you can try**
> > > > > > **` <ion-icon name="link" color="danger"></ion-icon>`**
> > > > > > **an it might work**
> > > > > > **_but i don't know for sure_**
> > > > > 
> > > > > 
> > > > > yes but what if you want purple icon?
> > > > 
> > > > 
> > > > **if purple is the color you want then may be look up the purple one or just try to type**
> > > > **`<ion-icon name="link" color="purple"></ion-icon>`**
> > > > or the hex
> > > 
> > > 
> > > what if you have all of your 100 icons in your application purple and after a week you decide that you want them to be orange.
> > 
> > 
> > then it will be harder to get it all again but this time orange so when you start get purple, orange, black and all the colors you might want later
> 
> that's why it's better to do it with CSS and not with an element prop.

**then do the hex colors** and it will probably work

**Comment by Abdurahmanm2020** [comment]
> > > > > > > **may be you can try**
> > > > > > > **` <ion-icon name="link" color="danger"></ion-icon>`**
> > > > > > > **an it might work**
> > > > > > > **_but i don't know for sure_**
> > > > > > 
> > > > > > 
> > > > > > yes but what if you want purple icon?
> > > > > 
> > > > > 
> > > > > **if purple is the color you want then may be look up the purple one or just try to type**
> > > > > **`<ion-icon name="link" color="purple"></ion-icon>`**
> > > > > or the hex
> > > > 
> > > > 
> > > > what if you have all of your 100 icons in your application purple and after a week you decide that you want them to be orange.
> > > 
> > > 
> > > then it will be harder to get it all again but this time orange so when you start get purple, orange, black and all the colors you might want later
> > 
> > 
> > that's why it's better to do it with CSS and not with an element prop.
> 
> **then do the hex colors** and it will probably work

like this **` <ion-icon name="link" color=" #316956"></ion-icon>`**

**Comment by hades200082** [comment]
@Abdurahmanm2020 How does that solve the issue? It's still an element attribute.

CSS allows it to be defined in one place and affect all. Props don't allow that.

**Comment by Abdurahmanm2020** [comment]
> @Abdurahmanm2020 How does that solve the issue? It's still an element attribute.
> 
> CSS allows it to be defined in one place and affect all. Props don't allow that.

yes that is right but if you cant do it with **css** then you take the **time** to do it with all the Props am I right

**Comment by Abdurahmanm2020** [comment]
```
css
ion-icon {
  font-size: 64px;
  color: blue;
  --ionicon-stroke-width: 16px;
}

html
<ion-icon name="heart-outline"></ion-icon>
<ion-icon name="heart"></ion-icon> <!--filled-->
<ion-icon name="heart-outline"></ion-icon> <!--outline-->
<ion-icon name="heart-sharp"></ion-icon> <!--sharp-->
<ion-icon ios="heart-outline" md="heart-sharp"></ion-icon>
<ion-icon size="small"></ion-icon>
<ion-icon size="large"></ion-icon>

<ion-icon name="logo-pinterest"></ion-icon>
```

![Untitled-5](https://user-images.githubusercontent.com/60320088/81804486-75206600-9519-11ea-8a6f-f7497d131aba.jpg)

**Comment by Abbazz2020** [comment]
I usually use [Font Awesome](https://fontawesome.com/) icons with them you can change the color normally,
but there is another way to change the color, 

`ion-icon{
    filter: invert(100%) sepia(100%) saturate(100%) hue-rotate(100deg) brightness(100%) contrast(100%);
}`

try this

> Follow Me

**Comment by hades200082** [comment]
@Abdurahmanm2020 having an inferior and harder to maintain work-around does not invalidate this issue. It still needs fixing so that ALL icons can be coloured with CSS.

In your example all three of the outline icons fail to show the colour specified in CSS.

We are not looking for a work-around, we are looking for it to be fixed so that CSS can be used in all situations to colour the icons.

@Abbazz2020 That's a slightly better work-around in that it allows it to be managed in one place, but it's not very readable. What colour is that?

I'd suggest that the acceptance criteria for this issue to be resolved would be to allow CSS `colour` property to be applied correctly to the icons. For outline icons this means applying the CSS colour to the stroke. For filled/normal icons it means applying it to the fill.

The inner SVG elements should also be selectable and colour-able in CSS.

**Comment by Abdurahmanm2020** [comment]
> @Abdurahmanm2020 having an inferior and harder to maintain work-around does not invalidate this issue. It still needs fixing so that ALL icons can be coloured with CSS.
> 
> In your example all three of the outline icons fail to show the colour specified in CSS.
> 
> We are not looking for a work-around, we are looking for it to be fixed so that CSS can be used in all situations to colour the icons.
> 
> @Abbazz2020 That's a slightly better work-around in that it allows it to be managed in one place, but it's not very readable. What colour is that?
> 
> I'd suggest that the acceptance criteria for this issue to be resolved would be to allow CSS `colour` property to be applied correctly to the icons. For outline icons this means applying the CSS colour to the stroke. For filled/normal icons it means applying it to the fill.
> 
> The inner SVG elements should also be selectable and colour-able in CSS.

I fixed is  

```
css
ion-icon {
  font-size: 64px;
  color: blue;
  --ionicon-stroke-width: 16px;
}

html
<ion-icon name="heart-outline"></ion-icon>
<ion-icon name="heart"></ion-icon> <!--filled-->
<ion-icon name="heart-outline"></ion-icon> <!--outline-->
<ion-icon name="heart-sharp"></ion-icon> <!--sharp-->
<ion-icon ios="heart-outline" md="heart-sharp"></ion-icon>
<ion-icon size="small"></ion-icon>
<ion-icon size="large"></ion-icon>

<ion-icon name="logo-pinterest"></ion-icon>
```

![Untitled-5](https://user-images.githubusercontent.com/60320088/81804486-75206600-9519-11ea-8a6f-f7497d131aba.jpg)

this works [go here](https://ionicons.com/usage)

and [go here](https://github.com/Abdurahmanm2020)

this way you can change the color using CSS so the issue is fixed

> Follow me Please !!!

**Comment by jongbonga** [comment]
One work around (if using ionic) would be to generate a [New color](https://ionicframework.com/docs/theming/colors#new-color-creator) (e.g: iconColor) then prop it to your icons

**Comment by avramchuk** [comment]
Try this:

```
[ionicons] Deprecated script, please remove: <script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>
To improve performance it is recommended to set the differential scripts in the head as follows:
<script type="module" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule="" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.js"></script>
```

**Comment by dzpt** [comment]
@avramchuk Please update the homepage.
I've been searching for hours to get these

**Comment by Abbazz2020** [comment]
This here is what you need.

[CSS filter generater](https://codepen.io/sosuke/full/Pjoqqp).

You paste the hex code for the colour you want then when you press [Compute filters](url) the filter code will come at the bottom.

> Follow me

**Comment by samandeggs** [comment]
> Try this:
> 
> ```
> [ionicons] Deprecated script, please remove: <script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>
> To improve performance it is recommended to set the differential scripts in the head as follows:
> <script type="module" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.esm.js"></script>
> <script nomodule="" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.js"></script>
> ```

Thanks for this. This worked - however this is clearly unideal as it is not documented, and ionic needs to resolve this.

**Comment by Abbazz2020** [comment]
> > Try this:
> > ```
> > [ionicons] Deprecated script, please remove: <script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>
> > To improve performance it is recommended to set the differential scripts in the head as follows:
> > <script type="module" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.esm.js"></script>
> > <script nomodule="" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.js"></script>
> > ```
> 
> Thanks for this. This worked - however this is clearly unideal as it is not documented, and ionic needs to resolve this.

Are you supposed to drop this in the header of your HTML

**Comment by Eebzie** [comment]
This isn't a perfect fix, but I used classes to separate the colouring of the ionicon in my header vs the ionicons in the menu links. 
Note: The .nav-link class has its own styling which is where the ionicon got its colour from.
```
/* ===== IONICONS CSS ===== */
.header-button ion-icon{
    font-size: 35px;
    color: white;
}

.nav-link ion-icon {
    font-size: 20px;
}

/* ===== MAIN CSS ===== */
.nav-link{
    display: flex;
    align-items: center;
    color: #606060;
    font-size: 14px;
    font-weight: bold;
    text-decoration: none;
    padding: 12px 15px;
}
```
![image](https://user-images.githubusercontent.com/38483435/108427245-dd1f7d80-720a-11eb-87dd-93341f307c90.png)
_Fig 1_. The white header button of size 35px

![image](https://user-images.githubusercontent.com/38483435/108427181-ca0cad80-720a-11eb-9551-083447d9ca2f.png)
_Fig 2_. The grey nav links of size 20px (green on hover)

**Comment by Ivan-Sanchez-Diaz** [comment]
> > @Abdurahmanm2020 having an inferior and harder to maintain work-around does not invalidate this issue. It still needs fixing so that ALL icons can be coloured with CSS.
> > In your example all three of the outline icons fail to show the colour specified in CSS.
> > We are not looking for a work-around, we are looking for it to be fixed so that CSS can be used in all situations to colour the icons.
> > @Abbazz2020 That's a slightly better work-around in that it allows it to be managed in one place, but it's not very readable. What colour is that?
> > I'd suggest that the acceptance criteria for this issue to be resolved would be to allow CSS `colour` property to be applied correctly to the icons. For outline icons this means applying the CSS colour to the stroke. For filled/normal icons it means applying it to the fill.
> > The inner SVG elements should also be selectable and colour-able in CSS.
> 
> I fixed it
> 
> ```
> css
> **ion-icon {
>   font-size: 64px;
>   color: blue;
>   --ionicon-stroke-width: 16px;
> }**
> 
> html
> <ion-icon name="heart-outline"></ion-icon>
> <ion-icon name="heart"></ion-icon> 
> <ion-icon name="heart-outline"></ion-icon> 
> <ion-icon name="heart-sharp"></ion-icon> 
> <ion-icon ios="heart-outline" md="heart-sharp"></ion-icon>
> <ion-icon size="small"></ion-icon>
> <ion-icon size="large"></ion-icon>
> 
> <ion-icon name="logo-pinterest"></ion-icon>
> ```
> 
> ![Untitled-5](https://user-images.githubusercontent.com/60320088/81804486-75206600-9519-11ea-8a6f-f7497d131aba.jpg)
> 
> this works [go here](https://ionicons.com/usage)
> 
> and [go here](https://github.com/Abdurahmanm2020)
> 
> this way you can change the color using CSS so the issue is fixed
> 
> > Follow me Please !!!

Thanks a lot!

**Comment by rhettclinton** [comment]
I applied css like this as the class for the ion-icon and it works.

.contact-channel-icon {
  color: white;
  --color: white;
}

**Comment by Sampath-Lokuge** [comment]
Yes, I have the same issue. i.e. cannot change the custom SVG `fill` color. :https://stackoverflow.com/questions/71399424/change-the-fill-color-of-an-svg-path-with-css-on-shadow-root

**Comment by brandyscarney** [comment]
Thanks for the issue! I am not seeing any issues with updating colors for the latest Ionicons: https://stackblitz.com/edit/ct8pwx?file=index.html

If you are still having this issue, please send us a code reproduction so we can look into it. Thanks!

**Comment by krsameer** [comment]
ion icons color don't appear to have the same html script as like others.
To set an ion icon color you have different codes rather than just writing down the color names -
<ion-icon name="mail" color="light "></ion-icon>           - For white color
<ion-icon name="mail" color="dark "></ion-icon>           -For black color
<ion-icon name="mail" color="danger "></ion-icon>       -For red color
etc.....

**Comment by aayushvashistha** [comment]
There are different color options that ion-icon use : 

Below is the screenshot attached for reference and a link--> 

https://ionicframework.com/docs/theming/colors

![ion-icon](https://github.com/ionic-team/ionicons/assets/66149367/5aba486e-4813-4e91-8117-0d496af3cedf)

You can call the same like --> 

`<ion-icon` size="large" name="logo-twitter" color="primary"></ion-icon>`
