### ISSUE TITLE
ionic cordova resources  

### ISSUE THREAD

**Issue by doubleCoolG** [ionic-team/ionicons#820]
D:\project\armp-work>
D:\project\armp-work>
D:\project\armp-work>
D:\project\armp-work>ionic  cordova  resources
√ Collecting resource configuration and source images - done!
√ Filtering out image resources that do not need regeneration - done!
(node:7716) ExperimentalWarning: The http2 module is an experimental API.
\ Uploading source images to prepare for transformations
HTTP Error 503: POST https://res.ionic.io/api/v1/upload

<!DOCTYPE html>
        <html>
          <head>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta charset="utf-8">
                <title>Application Error</title>
                <style media="screen">
                  html,body,iframe {
                        margin: 0;
                        padding: 0;
                  }
                  html,body {
                        height: 100%;
                        overflow: hidden;
                  }
                  iframe {
                        width: 100%;
                        height: 100%;
                        border: 0;
                  }
                </style>
          </head>
          <body>
                <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
          </body>
\ Uploading source images to prepare for transformations

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. I am going to close as there is not enough information for us to verify this bug. If this is still a problem with the latest version of Ionicons, please reply to this thread with a GitHub repo that we can use to verify the reported behavior.
