### ISSUE TITLE
Wechat and alipay

### ISSUE THREAD

**Issue by 66plus3** [ionic-team/ionicons#824]

**Comment by elshaddae** [comment]
@bensperry Supporting the author of this issue without description, I am requesting that the logo of Wechat and Alipay should be added. I saw the logos of Xing and TikTok & couldn't find Wechat's logo (1 Billion+ users) I thought I was missing something. 

Thank you in advance!

**Comment by bensperry** [comment]
This will go live in the next release (mid-October)

**Comment by bensperry** [comment]
These have now been added in the most recent release. Thanks!
