### ISSUE TITLE
v4 vs v5 - issues in @quasar/extras

### ISSUE THREAD

**Issue by dukhevych** [ionic-team/ionicons#826]
Ionicons v4 were simple and great - there were no problems with them at all. But v5 seems incompatible with other frameworks which use raw svg path data from ionicons and insert this data to their own skeleton (without any additional attributes).

Shouldn't svg icons be as simple as possible? In v5 some icons are made not via raw paths/lines/circles, but with styles addition. Most of build systems usually strip away these style attributes.

So who's wrong?

Should **ionicons** be more developer-friendly (without any strokes etc.)?

or

Should @quasar/extras adapt to these changes, if possible?

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. There's not a lot of information regarding the issue you are encountering, so I am going to close this. If you are still running into this please feel free to open a new issue and include a reproduction.
