### ISSUE TITLE
is:issue is:open my ion icons keep disappearing 

### ISSUE THREAD

**Issue by HeleneFG** [ionic-team/ionicons#829]
Hi, I hope someone can help me. It's like the fairies get into my WordPress site at night and mess around with the icons, making them disappear! I've added this code to Customise / Theme settings / Header/Footer / Footer scripts:

<script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>

The icons show up for awhile, and then one day, I notice they're gone! I add the widget code back on, and go through the same cycle.

<img width="436" alt="Screen Shot 2020-05-12 at 6 20 03 pm" src="https://user-images.githubusercontent.com/62190874/81659891-7f8d2200-947d-11ea-86f1-bd5da76730ac.png">

Any ideas?

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. Does this issue still reproduce using the latest version of Ionicons? If so, is there a sample app I can try?
