### ISSUE TITLE
Can we have typings for every icon?

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/ionicons#830]
In our app we created our own icon component which in a wrapper for ion-icon, so we can add our own icons. Our own icons are stored in an `enum` so we can easily access them. I now want that this enum extends ionic icons so when I select an icon manually with `Icon.AlarmOutline` I don't need to remember the string itself. In another file I have an icon map where strings from our API are mapped to icons from IonIcon. To prevent developers from spelling mistakes I want the key:value to be string:IonIcon.

**Comment by amandaejohnston** [comment]
Thank you for the request! I'm going to merge this with https://github.com/ionic-team/ionicons/issues/1269.
