### ISSUE TITLE
JS erro on IOS.

### ISSUE THREAD

**Issue by alvesbdanilo** [ionic-team/ionicons#836]
Hi, i'm using Ionicons without Ionic Framework. 
Just added  <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>  before the closing </body>.

On desktop and android devices works fine, but in IOS browsers (chrome and safari) the icons don't show.

Using browserstack i was able to identify the erro:
"Strict mode does not allow function declarations in a lexically nested statement." on line 229.

how can i solve this?

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. I am going to close as there is not enough information for us to verify this bug. If this is still a problem with the latest version of Ionicons, please reply to this thread with a GitHub repo that we can use to verify the reported behavior.
