### ISSUE TITLE
toggle-outline is wonky and not the same shape as toggle

### ISSUE THREAD

**Issue by quarfie** [ionic-team/ionicons#837]
toggle-outline is wonky and not the same shape as toggle

**Comment by bensperry** [comment]
Can you share a screenshot? I'm not seeing any issues with it.

**Comment by brandyscarney** [comment]
Thanks for the issue! Closing due to a lack of reproduction. If you are still seeing problems with the latest version of Ionicons please create a new issue with a code reproduction.
