### ISSUE TITLE
Unlink icon

### ISSUE THREAD

**Issue by whoacowboy** [ionic-team/ionicons#842]
Hi,

I needed an unlink icon, the opposite of the link icon, so I created it. I can send you a pull request if you would like to add it.

<img src="https://raw.githubusercontent.com/whoacowboy/ionicons/unlink-icon/src/svg/unlink.svg" height="100px" width="100px"/>
<img src="https://raw.githubusercontent.com/whoacowboy/ionicons/unlink-icon/src/svg/unlink-outline.svg" height="100px" width="100px"/>
<img src="https://raw.githubusercontent.com/whoacowboy/ionicons/unlink-icon/src/svg/unlink-sharp.svg" height="100px" width="100px"/>

**Comment by bensperry** [comment]
That'd be great!

**Comment by whoacowboy** [comment]
Here you go. #846

**Comment by amandaejohnston** [comment]
Closing this out as the PR has been merged.
