### ISSUE TITLE
Could not resolve './components' from ./node_modules/ionicons/dist/collection/index.js

### ISSUE THREAD

**Issue by Scan0815** [ionic-team/ionicons#848]
Hello, after the update to
@ ionic / core ":" ^ 5.2.2 "
ionicons was updated too, unfortunately there is now a build error from stenciljs.

```
[ERROR] Rollup: Unresolved import
           Could not resolve './components' from ./node_modules/ionicons/dist/collection/index.js
```

an export has apparently been added here
export * from './components';

in the directory components, there are only sub directories.

if i remove the export from index.js, it works!

Best greetings

**Comment by jwillmer** [comment]
I have the same issue. Could you give me more details on how you fixed it?

**Comment by Scan0815** [comment]
@jwillmer go to 
./node_modules/ionicons/dist/collection/index.js

 remove export * from './components';,

 this is only a temp fix 

or you make a fork.

Best greetings

**Comment by jwillmer** [comment]
I hoped there was another way since it is braking in my build pipeline :(

**Comment by Scan0815** [comment]
@jwillmer 
only fork and make your own build, 
maybe @liamdebeasi see the problem and provide a new version.

**Comment by jwillmer** [comment]
I already got the error with `"@ionic/core": "5.0.7"`
![image](https://user-images.githubusercontent.com/1503577/85740569-05012480-b702-11ea-8da8-db36f9070030.png)

**Comment by jwillmer** [comment]
I looked in the old `package-lock.json` and see that version `5.0.1` works but not version `5.1.0`
![image](https://user-images.githubusercontent.com/1503577/85741591-d9326e80-b702-11ea-9818-3349c33f0911.png)

**Comment by Scan0815** [comment]
yes thats right with 5.0.1 it works

**Comment by peterpeterparker** [comment]
pinning v5.0.1 in my stencils pwa also fixing the problem

**Comment by adamdbradley** [comment]
This was fixed with ionicons 5.1.1. Thanks for the report!
https://github.com/ionic-team/ionicons/commit/3a2ab6ec277234e49adfe7ed35ce1fb9d5fe7133

**Comment by jwillmer** [comment]
can confirm. it works again :)

**Comment by Scan0815** [comment]
perfect thanks @adamdbradley
