### ISSUE TITLE
Unable to download v5.1.0 - "Failed - No file"

### ISSUE THREAD

**Issue by thedoglett** [ionic-team/ionicons#850]
Tried several different browsers to try and download v5.1.0 but no luck.

Each time it says "Failed - No file".

Is there an alternative link to download it from?

**Comment by NikolaPeevski** [comment]
@thedoglett Does this work https://www.npmjs.com/package/ionicons/v/5.1.0-0 ?

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. I am going to close as there is not enough information for us to verify this bug. If this is still a problem with the latest version of Ionicons, please reply to this thread with a GitHub repo that we can use to verify the reported behavior.
