### ISSUE TITLE
Color not wokring on downloaded icons

### ISSUE THREAD

**Issue by infira** [ionic-team/ionicons#855]
When i use downloaded icons then ion-icon  color doens not work anymore
```
<!DOCTYPE html>
<html lang="et" class="no-js">
<head>
	<style>
		ion-icon {
			color: blue !important;
		}
	</style>
</head>
<body>
<ion-icon src="cart-outline.svg"></ion-icon>
<script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>
</body>
</html>
```
But as soon as i use 
`<ion-icon name="cart-outline"></ion-icon>` then it works.

How can i get it work with local svg files?

**Comment by Yohandah** [comment]
I encountered the same issue a while ago. 

- Open the downloaded SVG with the text editor of your choice
- Find all the css properties `stroke: #000`
- Set the value to `currentColor`

You are then able to customize the color of the svg with the color css attribute.

```
<ion-icon src="./assets/icons/my-icon.svg" class="my-icon"></ion-icon>

.my-icon {
  color: blue;
}
```

**Comment by infira** [comment]
Thanks, it worked

**Comment by brandyscarney** [comment]
Thanks for the issue! I am not seeing any issues with updating colors for the latest Ionicons: https://stackblitz.com/edit/ct8pwx?file=index.html

If you are still having this issue, please send us a code reproduction so we can look into it. Thanks!
