### ISSUE TITLE
Not able to change color of icons

### ISSUE THREAD

**Issue by sc0rp10n-py** [ionic-team/ionicons#864]
I want to change color of icon so i added a class to it but that doesn't work at all.
Even changing color by using ion-icon `{ color: white; }` doesn't seem to work at all.

**Comment by brandyscarney** [comment]
Thanks for the issue! I am not seeing any issues with updating colors for the latest Ionicons: https://stackblitz.com/edit/ct8pwx?file=index.html

If you are still having this issue, please send us a code reproduction so we can look into it. Thanks!
