### ISSUE TITLE
Indices of some icons are incorrect 

### ISSUE THREAD

**Issue by rkim-mits** [ionic-team/ionicons#867]
For example, the "md-create" icon shows a github branch type of icon. This is tested with "react native run-ios" command

**Comment by rkim-mits** [comment]
This is occurring with version "^4.6.4"

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. We removed the MD versus iOS styles in Ionicons v5, so this issue may no longer apply to Ionicons. I am going to close this, but let me know if you have any questions.
