### ISSUE TITLE
Request: Discord, DeviantArt and Mastodon logo icons 

### ISSUE THREAD

**Issue by vasanthdeveloper** [ionic-team/ionicons#872]
Kudos 👏 to everyone for maintaining and contributing to this open-source icon library.
Every icon, my projects require already exists in this 😍 fabulous icon library, except 🙂 3 logos.

**Discord** (chatting platform designed for gamers)
[Example](https://iconmonstr.com/discord-1-svg) | [Original Branding](https://discord.com/branding)

**DeviantArt** (art website)
[Example](https://iconmonstr.com/deviantart-1-svg) | [Original Branding](https://www.deviantartsupport.com/en/article/where-can-i-find-deviantarts-official-logo-and-media-files)

**Mastodon** (blockchain-based, open-source, Twitter-like social media)
[Example](https://icons8.com/icon/SjG6BzZwdP2-/mastodon) | [Original Branding](https://joinmastodon.org/press-kit.zip) `Download`

I would really appreciate 🤗 it if someone can contribute these three icons to the library.

Thank you 👋

**Comment by bensperry** [comment]
This was added in the latest release!

**Comment by vasanthdeveloper** [comment]
Thank you @bensperry 😀
