### ISSUE TITLE
Request: ban, no-access, not-allowed icon

### ISSUE THREAD

**Issue by basvdijk** [ionic-team/ionicons#873]
The current set of icons misses an icon representing: ban, no-access or not allowed like:
![image](https://user-images.githubusercontent.com/644550/91189197-748b9400-e6f2-11ea-9a04-529b8d2e17d8.png)

https://fontawesome.com/icons/ban?style=solid

**Comment by bensperry** [comment]
This was added in the latest release!

**Comment by basvdijk** [comment]
@bensperry Great! Could it be that it is not packed in Ionic (Angular) itself yet?
