### ISSUE TITLE
Request: Extension Puzzle Icon

### ISSUE THREAD

**Issue by billygerhard** [ionic-team/ionicons#874]
The standard "extension" icon seems to be a puzzle.

From Chrome: ![image](https://user-images.githubusercontent.com/2285204/91508058-7301cd80-e8a4-11ea-81c9-35b6c4f13db7.png)

From Twitch: ![image](https://static-cdn.jtvnw.net/badges/v1/ea8b0f8c-aa27-11e8-ba0c-1370ffff3854/3)

**Comment by bensperry** [comment]
This was added in the latest release!
