### ISSUE TITLE
Warning using Ionicons Script

### ISSUE THREAD

**Issue by ppedrazzi** [ionic-team/ionicons#875]
Trying to use ionicons with the typical script in the head tag, but they aren't loading on the page.

Getting this error in the console.

<img width="1278" alt="Screen Shot 2020-09-01 at 9 09 15 AM" src="https://user-images.githubusercontent.com/587780/91877534-f586e600-ec32-11ea-90a3-b5f98dc8fb3e.png">

**Comment by liamdebeasi** [comment]
Thanks for the report, and apologies for the delay. This issue is happening because you are using a deprecated way of importing Ionicons. To fix this, I recommend following the [installation steps on the Ionicons website](https://ionic.io/ionicons/usage).
