### ISSUE TITLE
SVG icon dark mode

### ISSUE THREAD

**Issue by Vitiumartis** [ionic-team/ionicons#881]
I have two icons from the ionic library. Same name and design. But in dark color mode the SVG icon has different color. What am I doing wrong?

`<ion-icon slot="start" name="today-outline"></ion-icon>`
`<ion-icon slot="start" src="/assets/icon/today-outline.svg"></ion-icon>`
![Bildschirmfoto vom 2020-09-09 17-38-55](https://user-images.githubusercontent.com/31731886/92625399-e0602600-f2c8-11ea-9a55-e892d3ff24db.png)
![Bildschirmfoto vom 2020-09-09 17-38-41](https://user-images.githubusercontent.com/31731886/92625400-e0f8bc80-f2c8-11ea-9966-0d61614bb3aa.png)

**Comment by bensperry** [comment]
I don't think you're doing anything wrong—it's an issue with how this icon was built. I'm planning on fixing it in the next release (targeting mid-October).

**Comment by bensperry** [comment]
This will be fixed in the next release, FYI.

**Comment by bensperry** [comment]
This should be fixed in the most recent release. Can you check and let me know?

**Comment by Vitiumartis** [comment]
It works. Thx.
