### ISSUE TITLE
Request: Shop Icon

### ISSUE THREAD

**Issue by elnath78** [ionic-team/ionicons#882]
Incredibly missing a store front icon similar to this one (Google):
http://share.creoweb.it/b2577c20.jpg

**Comment by bensperry** [comment]
can you share a new link? that one doesn't work.

**Comment by elnath78** [comment]
Hello, it is part of the Google Material Design, here is the page: https://material.io/resources/icons/?icon=store&style=baseline

Here is the download link (svg): https://fonts.gstatic.com/s/i/materialicons/store/v5/24px.svg?download=true

**Comment by bensperry** [comment]
This was added in the latest release!

**Comment by elnath78** [comment]
Thanks!
