### ISSUE TITLE
Facebook icon not displaying correctly.

### ISSUE THREAD

**Issue by fs-projects** [ionic-team/ionicons#892]
Hello Team,

Good day!

This is to inform that facebook icon <ion-icon name="logo-facebook"></ion-icon> is not displaying as expected. 

**Details** - 

Below is how 5 social icons looks when I used them in my project. Please notice the **different look of facebook icon** as compared to other icons. Any custom class that I have used on these icons, I have made sure that each of these icons have the  same class applied.

![image](https://user-images.githubusercontent.com/42044009/96370613-102e0380-117c-11eb-8427-5348bedbd234.png)

On inspecting I could observe that facebook icon has difference in <svg .... value as compared to other icons(say twitter) respectively. Please see below -

![image](https://user-images.githubusercontent.com/42044009/96370906-18d30980-117d-11eb-83f3-55d1e412aeaf.png)

![image](https://user-images.githubusercontent.com/42044009/96370929-28525280-117d-11eb-92f4-f702a5e0716f.png)

**Note** : I have a hover effect also that looks like below that works fine for all other icons except for this facebook icon. I don't know if it is due to this issue. Hover effect looks like below that doesn't work for facebook icon only.

![image](https://user-images.githubusercontent.com/42044009/96371046-90089d80-117d-11eb-8ac9-6128b2ac3e71.png)

Please look into this issue and let me know if I can help you guys in any better way. Thank you.

**Comment by brandyscarney** [comment]
Thanks for the issue! This does not appear to be an issue anymore in latest: https://stackblitz.com/edit/svyepq-cksqd4?file=index.html

If you are still having problems please create a new issue with a code reproduction, thanks! 🙂
