### ISSUE TITLE
Ionicon Library Outline Issue

### ISSUE THREAD

**Issue by IONICNERD1234** [ionic-team/ionicons#907]
The ionic icon for library-outline has a different icon than expected, so it flips between the two when you try to use it. Library books and an icon with an equal sign and a leaning rectangle...
![library-outline_issue](https://user-images.githubusercontent.com/74978783/100120314-d076cd80-2e45-11eb-9e79-1b8d06139658.PNG)

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. This issue appears to be resolved, so I am going to close the thread:

![image](https://user-images.githubusercontent.com/2721089/200671966-8a1a6353-ad27-43db-932a-61da6ae68c66.png)


Let me know if you have any questions.
