### ISSUE TITLE
Figma icon not working

### ISSUE THREAD

**Issue by kemiljk** [ionic-team/ionicons#913]
Is anyone else utilising the Figma icon in their builds? All other icons I've used are working as expected for me in test apart from the Figma one. Could really do with it! 😊.

**Comment by bensperry** [comment]
Can you share a demo or elaborate more on this?

**Comment by brandyscarney** [comment]
Thanks for the issue. I am going to close this as there hasn't been any reproduction provided, but if you are still running into this please include a code reproduction for us. Thank you!
