### ISSUE TITLE
Ion Icons access control checks in ionic Cordova platform OS X

### ISSUE THREAD

**Issue by pedrumgolriz** [ionic-team/ionicons#917]
I've been scouring the internet and can't find anything relevant to ionic 5 and OS X platform. I'm getting the following errors when adding ion icons to my build:

JavaScript error: polyfills.js:4515: Fetch API cannot load file:///Users/pedrumgolriz/Documents/dev/testapp/platforms/osx/build/testapp.app/Contents/Resources/www/svg/reader-outline.svg due to access control checks.

I get this for each ion icon used. Can someone point me in the right direction?

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. Can you please provide a GitHub repo that I can use to verify this behavior?
