### ISSUE TITLE
Not able to change color for outline icons

### ISSUE THREAD

**Issue by vivekcontentstack** [ionic-team/ionicons#918]
Hi

I'm trying to change the color for outline icons but adding
```
ion-icon {
     color: 'blue'
}
```

but it doesnot work for outline icons works fine for solid icons, can anyone help me to fix this issue
**ionicons version - 5.2.3v**

Thanks,
Any help is appreciated

**Comment by danny-englander** [comment]
I was able to do this like this:

```
.foo {
  &:before {
    content: "\f36a";
    font-size: 100px;
    color: blue;
  }
}
```

![2020-12-24_13-17-50](https://user-images.githubusercontent.com/609623/103106459-99354100-45ea-11eb-940d-ab1c5cd1fcdc.jpg)

**Comment by Varun514-code** [comment]
I tried like 
      HTML code-
           <ion-icon name="code-outline" class="icon big"></ion-icon>
           
      CSS code- 
           .icon {
                 color: #00a8ff;
            }

       The color changed as I wanted.
       The difference is, give a class to the tag and then add the CSS properties.

**Comment by brandyscarney** [comment]
Thanks for the issue! I am not seeing any issues with updating colors for the latest Ionicons: https://stackblitz.com/edit/ct8pwx?file=index.html

If you are still having this issue, please send us a code reproduction so we can look into it. Thanks!

**Comment by Varun514-code** [comment]
I did not comment on this, I have not even visited Ionicons since a
long time.
