### ISSUE TITLE
 src="https://svgshare.com/i/6r_.svg" not working with ion-icon 

### ISSUE THREAD

**Issue by amrit-kumar** [ionic-team/ionicons#924]
I am sharing a stackblitz link which shows that  ion-icon  with a src having external link does not works .[https://stackblitz.com/edit/ionicons-v4-atqxdt?file=pages%2Fhome%2Fhome.html](https://stackblitz.com/edit/ionicons-v4-atqxdt?file=pages%2Fhome%2Fhome.html)

**Comment by ccosmincc** [comment]
Any updates on this one? I'm facing the same issue.

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. Ionicons does not support loading arbitrary SVG elements from the web. When providing a URL to an SVG asset, the asset must be defined in your local project. I am going to close this, but let me know if you have any questions.
