### ISSUE TITLE
[Icon Request] NFC Technology Icon

### ISSUE THREAD

**Issue by maxbauer** [ionic-team/ionicons#929]
Hi Ionic-Team,

I'm missing an icon for the nfc technology.
Something like [this](https://thumbs.dreamstime.com/b/nfc-icon-white-background-illustration-109707756.jpg) or [this](https://cdn3.iconfinder.com/data/icons/computers-programming/512/NFC-512.png) for example.

Thanks a lot for your work!

**Comment by calvintam236** [comment]
Duplicate of #833

**Comment by brandyscarney** [comment]
Closing as a duplicate of #833, thank you!
