### ISSUE TITLE
"barbell-outline" icon missing graphics on varying font-sizes

### ISSUE THREAD

**Issue by AdrianoCucci** [ionic-team/ionicons#930]
This is a very minor visual-bug report with the "barbell-outline" icon that I happened to come across while developing an app.
The larger-bell graphics of the icon seem to disappear when the icon is rendered at varying font-sizes.

Here is how it should look:
![proper](https://user-images.githubusercontent.com/26356180/105923596-9cb55100-600a-11eb-90c8-b64d7f94a31a.png)

Here is how it can end up looking:
![missing](https://user-images.githubusercontent.com/26356180/105923763-d7b78480-600a-11eb-85ef-25712d40ee8b.png)

I have a small demo project repository of the issue here, where it shows the three icon variants animating between small-large font sizes:
https://github.com/AdrianoCucci/Barbell-Icon-Demo

To view the issue in the project, simply clone & run it with `ionic serve`. 

Additional details:
- Ionic CLI version: 6.12.3
- @ionic/angular version: ^5.0.0
- Angular version: ~10
- Node.js version: 14.15.3

**Comment by liamdebeasi** [comment]
Thanks for the report and apologies for the delay. This issue appears to be resolved, so I am going to close the thread. Here is a demo of the barbell outline icon rendering as expected: https://codepen.io/liamdebeasi/pen/XWYpbEd

Let me know if you have any questions.
