### ISSUE TITLE
Version 4 icons not showing on Safari Version 14.1 (16611.1.10.1.5)

### ISSUE THREAD

**Issue by kurrle** [ionic-team/ionicons#934]
Version 4 Icons no longer show in Safari Version 14.1.  It looks like the v5 icons do.

**Comment by kurrle** [comment]
We're loading the icons externally but Safari is trying to load the svg files locally it looks like.  I've attached a screen from my local host but it does the same think on AWS

<img width="1680" alt="Screen Shot 2021-02-08 at 12 22 29 PM" src="https://user-images.githubusercontent.com/18465071/107265956-8051e500-6a0a-11eb-9e3d-ebd475ee2da6.png">

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. Can you please provide a GitHub repo that I can use to verify this behavior?
