### ISSUE TITLE
Ionicons star-half icons have interior stroke

### ISSUE THREAD

**Issue by pdugan20** [ionic-team/ionicons#935]
Portions of the Ionicons set have an interior stroke on their half-stars. Assuming this should be a filled interior to match the rest of the set?

<img width="1227" alt="Screen Shot 2021-02-04 at 5 48 29 PM" src="https://user-images.githubusercontent.com/1837100/106978487-3965a600-6711-11eb-9fc8-52b88ce395af.png">

**Comment by amandaejohnston** [comment]
Thanks for the report. It looks like this has since been resolved, as I no longer see the interior stroke when looking at the latest version of the site. I'm going to close this out, but let me know if you're still having problems on the latest version of Ionicons.
