### ISSUE TITLE
Paper icon 404 error

### ISSUE THREAD

**Issue by George-Ogden** [ionic-team/ionicons#940]
I am getting a 404 error requesting to get the `paper.svg` icon
```
GET https://unpkg.com/ionicons@5.4.0/dist/ionicons/svg/paper.svg 404
```
And if you look at the page https://unpkg.com/ionicons@5.4.0/dist/ionicons/svg/paper.svg, you'll see that it's not there.

**Comment by calvintam236** [comment]
https://ionic.io/ionicons

Do you mean `document` or `paper-plane`? I don’t think there is `paper`.
