### ISSUE TITLE
Problem loading icons

### ISSUE THREAD

**Issue by cigaai** [ionic-team/ionicons#944]
I am using the script: 
**<script type = "module" src = "https://unpkg.com/ionicons@5.0.0/dist/ionicons/ionicons.esm.js"> </script>**

But when loading any icon "bag" **<ion-icon name = "bag-handle-outline"> </ion-icon>** 
does not load and the error occurs:
**VM100033: 1 GET https://unpkg.com/ionicons@5.0.0/dist/ionicons/svg/bag-handle-outline.svg 404**

**Comment by suture** [comment]
I noticed the same issue with the bag icon

**Comment by cigaai** [comment]
> I noticed the same issue with the bag icon

Is there a solution already?

**Comment by nashr** [comment]
As of today (July 5), the bag icon is working (`<ion-icon name="bag"></ion-icon>`). However, I cannot make it work with these arrow icons:

- `<ion-icon name="arrow-dropdown-circle"></ion-icon>` 
- `<ion-icon name="arrow-dropdown"></ion-icon>`
- `<ion-icon name="arrow-round-down"></ion-icon>`

Got **https://unpkg.com/ionicons@5.5.2/dist/ionicons/svg/arrow-round-down.svg 404** too (and for the other two as well).

**Comment by nashr** [comment]
Oops, found the culprit. I was browsing icons from the older version of Ionicons (https://ionic.io/ionicons/v4) instead of the newest one (https://ionic.io/ionicons). It looks like they have a different set of icons and hence the icon names too.

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. Is this issue still happening? I cannot reproduce this on my end.
