### ISSUE TITLE
Disabling default tooltips

### ISSUE THREAD

**Issue by franciscojdev** [ionic-team/ionicons#949]
When I hover over an icon, the default tooltip shows up on the bottom right.
Is there any way to disable this ? "pointer-events: none" works but it disables my hover animations.
![tooltip](https://user-images.githubusercontent.com/62097765/110850365-9bcd3b80-82a7-11eb-98e3-2a90cf10ac66.jpg)

**Comment by Siedlerchr** [comment]
It seems to be directly coming from the svg https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title

**Comment by franciscojdev** [comment]
So, in this case, how do I go into the svg to change it ? Because I don't have them downloaded, I have them in my HTML through the code provided in the ion-icons website. Thanks :)

**Comment by martinklepsch** [comment]
> "pointer-events: none" works but it disables my hover animations.

if you put the hover on the parent element and not the `ion-icon` element the color change should still work.

**Comment by ariscol** [comment]
Would really appreciate a way to disable the tooltip as well. I definitely don't want a tooltip every time I place one of these, since in many cases the icon is the root element for a custom (complex) tooltip or other functionality.

**Comment by peterpeterparker** [comment]
Tooltip comes from the `<title>....</title>` inside the `<svg/>`.

Question is: do we need the title for any reason, like accessibility? or is the title irrelevant?

If irrelevant, then can't we "just" remove it?

If yes, can be removed, then I guess it can be removed in the [build script](https://github.com/ionic-team/ionicons/blob/8c2a507fcff2cb5f2edff60357ffd7feb70bb987/scripts/build.ts#L171).

**Comment by ariscol** [comment]
It seems to me that if good accessibility were a motivator, you'd be even _more_ obligated to provide a way to remove/disable/override the title, because in many cases the name of the icon may be confusing or even misleading. Accessibility can only be effectively supported by the site designer, and these titles, quite literally, get in the way of that effort.

Oh, and another reason I think it's a bad idea to have the title in the SVG: Internationalization.

**Comment by kaigon** [comment]
I got around the hover tooltip with CSS:

```
ion-icon:before {
    content: '';
    position: absolute;
    width: 100%;
    height: 100%;
}
```

Which prevents the tooltip from being triggered without affecting other hover effects (at least none that I'm using).

**Comment by MicheleLucini-infobit** [comment]
is this problem so difficult to solve and ship? has been open for more than 180 days

**Comment by brandyscarney** [comment]
Thanks for the issue, closing this to track in #838.

**Comment by SurajanShrestha** [comment]
> I got around the hover tooltip with CSS:
> 
> ```
> ion-icon:before {
>     content: '';
>     position: absolute;
>     width: 100%;
>     height: 100%;
> }
> ```
> 
> Doesn't resolve any accessibility issues that may be caused by having a non-applicable title tag, but it at least prevents the tooltip from being triggered without impacting other hover effects (at least none that I'm using).

@kaigon Thank you so much. This solved it for me 😌🙏.

**Comment by multijek** [comment]
ion-icon {
        pointer-events: none;
      }

**Comment by sujallimje** [comment]
HTML
`<a
                href="https://www.github.com/sujallimje"
                class="social-link"
                target="_blank"
                title="Go to GitHub"
              >
                <ion-icon name="logo-github"></ion-icon>
              </a>`
