### ISSUE TITLE
Icon Suggestion - Telegram

### ISSUE THREAD

**Issue by fbalbinoribeiro** [ionic-team/ionicons#950]
We have several social Ionicons for the most important message technologies. I'd like to use the Telegram icon in my app, because actually, this is one of the most popular apps in the world.

Thanks!!

**Comment by alexbleggi** [comment]
Interesting, it would be usefull to have this icon in the library ...

**Comment by calvintam236** [comment]
Duplicate of #338

**Comment by brandyscarney** [comment]
Thanks for the issue, closing as a duplicate of #338
