### ISSUE TITLE
How to update the package

### ISSUE THREAD

**Issue by B0rrA** [ionic-team/ionicons#962]
I want to use some new icons that are on **V5.4.0**, I'm using V5.3.0 now, I don't find the any doc about how to upgrade the package. 

Maybe some way to add just one icon to my package wold work for me. `id-card` is the one that i want to use

**Comment by calvintam236** [comment]
Not sure what package you are using. Please let us know so we can help you.

**Comment by b0rrA** [comment]
@calvintam236 I'm using V5.3.0 of ionicons

**Comment by calvintam236** [comment]
Are you using React? Flutter? or others?

**Comment by b0rrA** [comment]
Ionic + Angular + Capacitor

**Comment by calvintam236** [comment]
https://www.npmjs.com/package/ionicons

Use npm to update: `npm install ionicons@latest`. You can also manually update `package.json`.

**Comment by B0rrA** [comment]
Thanks @calvintam236
