### ISSUE TITLE
Previous version of Ionic icons are no longer accessible

### ISSUE THREAD

**Issue by bhatmand** [ionic-team/ionicons#969]
Earlier, the previous version of Ionic Icons were accessible but, that's not the case anymore.

The URL to access previous versions were:
[https://ionicons.com/v1/](https://ionicons.com/v1/)
[https://ionicons.com/v2/](https://ionicons.com/v2/)
[https://ionicframework.com/docs/v3/ionicons/](https://ionicframework.com/docs/v3/ionicons/)
[https://ionicons.com/v4/](https://ionicons.com/v4/)

Except v3, they all now redirect to new website/URLs:
[https://ionic.io/ionicons/v1](https://ionic.io/ionicons/v1)
[https://ionic.io/ionicons/v2](https://ionic.io/ionicons/v2)
[https://ionic.io/ionicons/v4](https://ionic.io/ionicons/v4)

All of which show latest Ionic icons instead of the given version 😞 

Request you to please fix this. Some of us like me are stuck working with legacy products/projects which still use older Ionic icons like v1 and need access to them.

Thank you

**Comment by hexoh** [comment]
@bhatmand I have the same problem. Icon can not access the old version.Looking forward to solving it soon.

**Comment by awaken180-dev** [comment]
I am also having this same issue.  I am trying to access v4 icons.

**Comment by freddiescadding** [comment]
Also hoping to regain access to the v2 icons

**Comment by royscheepens** [comment]
Same here, would love to have access to the old icons (especially v4) again.

**Comment by awaken180-dev** [comment]
Looks like they're back:

- [Ionic v4](https://ionic.io/ionicons/v4)
- [Ionic v3](https://ionicframework.com/docs/v3/ionicons/?__hstc=13779304.a87b2dc55f69034d0edc19e24de3cd3d.1620050650226.1620824058016.1621340050741.3&__hssc=13779304.1.1621340050741&__hsfp=209863720&_gl=1*qsws7r*_ga*MjEzNjIyMDIwNy4xNjExMTcyMDIw*_ga_REH9TJF6KF*MTYyMTM0MDA0OS4xMTguMC4xNjIxMzQwMDUzLjA.)
- [Ionic v2](https://ionic.io/ionicons/v2)

**Comment by bhatmand** [comment]
Thank you so much team Ionic Icons. The old icons are back ❤️ Closing the issue now. Thanks again for helping us out.
