### ISSUE TITLE
Using same icon multiple times renders only once

### ISSUE THREAD

**Issue by dhruvkb** [ionic-team/ionicons#970]
When an icon is used multiple times on the same page, it renders only once. The first occurrence of the icon renders perfectly. The SVG is injected into `div.icon-inner` as expected.

At other places the element `div.icon-inner` shows up empty.
```html
<div class="icon-inner"></div>
```
This issue also causes icons to disappear if any event causes the icon to be re-rendered (such as developing with HMR or changing the class on the `<ion-icon>` component).

I suspect this to be an issue with the caching mechanism built into the component.

**Comment by kwiat1990** [comment]
I have a similar problem. In a production build (locally everything works always correctly) I've noticed that as soon as there is some change causing re-render of Vue components, all ionic icons disappear. In DOM I can see only mentioned element `<div class="icon-inner"></div>` without any children.

**Comment by TingHuang222324** [comment]
I have the same problem, in production mode
The first load can be injected normally,
After the route is converted, it will become invalid

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. Is anyone able to provide a sample repo I can use to verify this behavior?
