### ISSUE TITLE
Reflect "name" attribute as it's a useful target for custom styling

### ISSUE THREAD

**Issue by mattsteve** [ionic-team/ionicons#975]
Need the name attribute to be reflected in the DOM as it's useful for targeting styling based on which icon is displayed.
https://github.com/ionic-team/ionicons/blob/master/src/components/icon/icon.tsx#L58

Previous discussion here:
https://github.com/ionic-team/ionic-framework/issues/23323#issuecomment-847276374

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionicons/pull/981, and a fix will be available in an upcoming release of Ionicons.
