### ISSUE TITLE
iOS pencil icon

### ISSUE THREAD

**Issue by emil-malmgaard-rasmussen** [ionic-team/ionicons#980]
Am I the only one who can't find <icon name="edit" /> and must use <icon name="create" />?

Would rather preffer not to replace ion-icons from my react-native project, but if the only available "pen"-looking icon is "create" guess im forced, "create" looks really silly to be honest.

**Comment by brandyscarney** [comment]
This exists as:

```
<ion-icon name="pencil"></ion-icon>
```

![Screen Shot 2022-09-27 at 12 16 45 PM](https://user-images.githubusercontent.com/6577830/192580159-e56cd178-0a08-4df1-a24b-a27b9b6bc478.png)


Please see the docs here and search for `"pencil"`: https://ionic.io/ionicons

I am going to close this but let me know if I am misunderstanding you. Thanks!
