### ISSUE TITLE
Most Icons not showing with React

### ISSUE THREAD

**Issue by itsahmaneth** [ionic-team/ionicons#986]
I tried to use some Icons in a application but couldn't make it work.
Some Icons works, like "chevron-back" and "chevron-forward", but some like "play", "pause", actually many others doesn't shown.

Using the last update, 5.5.2. Tested in older versions too.
Both current project and brand new one acts the same.

I'm using the following code:

```
import { IonIcon } from '@ionic/react';

<IonIcon name="chevron-back"></IonIcon> // Works
<IonIcon name="close"></IonIcon> // Works

<IonIcon name="play"></IonIcon> // Don't Work
<IonIcon name="pause"></IonIcon> // Don't Work
```

The way I found out to use the Icons is to download the svg file from the Icons page and use them with src="path".

**Comment by dmartinjs** [comment]
In React,
you should do something like that
```JSX
import { IonIcon } from '@ionic/react';
import { chevronBack, close, play, pause } from 'ionicons/icons';

<IonIcon icon={chevronBack}/>
<IonIcon icon={close}/>

<IonIcon icon={play}/>
<IonIcon icon={pause}/>
```

You can find all icon names here
https://unpkg.com/ionicons@5.0.0/icons/index.js

**Comment by itsahmaneth** [comment]
It worked!
Thank you so much!
