### ISSUE TITLE
Ticket Icon not working

### ISSUE THREAD

**Issue by ssalcedo-gnt** [ionic-team/ionicons#989]
I'm trying to use the Ticket Icon but it don't work, it's not found or something like that.

'ticket-outline'

![image](https://user-images.githubusercontent.com/71837292/123355984-671a8280-d52c-11eb-965c-19cdc5edc19b.png)

**Comment by dmartinjs** [comment]
@ssalcedo-gnt can you share more details for us to help you ? 
code example ? what is the technology you are using (React, Vue, Angular, pure javascript...) ?

**Comment by ssalcedo-gnt** [comment]
I'm using React Native with JS
