### ISSUE TITLE
Some icons are broken on windows

### ISSUE THREAD

**Issue by vanackere** [ionic-team/ionicons#990]
Hi, some icons look broken when building my ionic application (angular-based) for windows (the same icons were fine on IOS).

Easy way to reproduce the symptoms:

loading the `node_modules/ionicons/dist/ionicons/svg/refresh.svg` file in a browser (Firefox, IE11 or Edge) gives the following image:

![image](https://user-images.githubusercontent.com/800632/123535393-d60dfc00-d723-11eb-8563-30fb900916a3.png)

However the correct image is displayed when loading `node_modules/ionicons/dist/svg/refresh.svg`

Why are the svg different and why is the svg broken in this case ?

For now i've worked around this by editing my angular.json to copy the files from `node_modules/ionicons/dist/svg` instead of `node_modules/ionicons/dist/ionicons/svg`

**Comment by liamdebeasi** [comment]
Thanks for the reply and apologies for the delay. Does this issue still reproduce on Windows?
