### ISSUE TITLE
Limited choice of icons

### ISSUE THREAD

**Issue by JoJk0** [ionic-team/ionicons#998]
I love the ionicons and the flexibility it offers but the choice of icons is not very wide. I have seen tons of PRs for adding new icons which are not merged yet as well as feature requests for adding icons that are left without response since last year. Are you still open for adding new icons?

**Comment by JoJk0** [comment]
I know you're busy guys now, but at least let others help you. Otherwise, people will go away from ionicons for alternatives.

**Comment by brandyscarney** [comment]
Thanks for the issue! We are currently working on triaging this repository to get through issues and pull requests and will soon begin going through icon requests.
